moneymanagerex/moneymanagerex

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2910)
> fix(#2893): tidy-up

- src/mmchecking_list.cpp
- src/mmchecking_list.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2911)
> fix(#2893): column sort fix

- license.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2913)
> fix(#2817): privacy notice change

- src/mmframe.cpp
- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2916)
> fix(#2893): trans report style now matches others

- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
- src/mmframe.cpp
- src/mmpanelbase.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2920)
> fix(#2915): print all fixed now

- src/filtertransdialog.cpp
- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2925)
> fix(#2883): report totals split

- src/transactionsupdatedialog.cpp
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2928)
> fix(#2418): combo popup for payee on text entry

- CMakeLists.txt
- contrib.txt
- src/build.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2933)
> chore(version): now beta 4

- docs/de/index.html
- docs/en/grm.html
- docs/en/index.html
- docs/es/grm.html
- docs/es/index.html
- docs/it/grm.html
- docs/it/index.html
- docs/pl/index.html
- docs/ru/grm.html
- docs/ru/index.html
> chore(html): open external links in browser

- dockers/debian.buster/Dockerfile
- dockers/ubuntu.focal/Dockerfile
- dockers/ubuntu.groovy/Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2947)
> fix(unix): update

- .travis.yml
> fix(dockers): update

- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2966)
> fix(#2918): All trans and checking panels sort col

- src/constants.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2969)
> fix(#2938): Now points to mmex android site

- src/stockdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2974)
> fix(#2919): url

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2975)
> fix(#2952): new variable

- CMakeLists.txt
- po/mmex.pot
- src/build.h
- src/filtertransdialog.cpp
- src/mmframe.cpp
> fix(#2929): menu items hot button

- src/mmchecking_list.cpp
- src/mmframe.cpp
- src/option.cpp
- src/reports/payee.cpp
- src/reports/summary.cpp
> fix(#2973): cleanup

- src/mmchecking_list.cpp
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2989)
> fix(#2982): Duplicate trx date logic changed

- src/accountdialog.cpp
- src/accountdialog.h
- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2994)
> feat(#2993): closed favourites not listed

- po/mmex.pot
- src/mmframe.cpp
- src/mmframe.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3000)
> fix(#2998): home page

- CMakeLists.txt
- src/build.h
- src/images_list.cpp
- src/mmframe.cpp
- src/option.cpp
- src/option.h
- src/optionsettingsview.cpp
- src/optionsettingsview.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3001)
> fix(#2996): icon sizes stage 1

- src/util.cpp
> chore(colors): softer colors

- resources/master.css
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3004)
> fix(2997): border overflow issue

- resources/home_page.htt
- src/general_report_manager.cpp
- src/mmframe.cpp
- src/reports/cashflow.cpp
- src/reports/categexp.cpp
- src/reports/forecast.cpp
- src/reports/htmlbuilder.cpp
- src/reports/incexpenses.cpp
- src/reports/summarystocks.cpp
#2965
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3008)
> fix(#2995): Stocks Report values

- src/option.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3009)
> fix(2996): icon sizes stage

- src/mmframe.cpp
- src/mmframe.h
> fix(#2987): Display Share Accounts

- po/mmex.pot
- src/mmframe.cpp
- src/mmframe.h
- src/mmreportspanel.cpp
- src/reports/myusage.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3013)
> fix(#2999): Report graph label translation issue

- src/mmchecking_list.cpp
> fix(#2891): status for statement date

- src/images_list.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3021)
> fix(#3019): memory leaks

- resources/master.css
- src/reports/htmlbuilder.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3026)
> fix(#2877): css update

- po/mmex.pot
- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3042)
> chore(i10n): crowdin.com

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3046)
> fix(#3040) share and asset trx dialog

- src/optionsettingsview.cpp
> fix(3019): view options redesign

- po/mmex.pot
- src/optionsettingsview.cpp
> fix(#3019): typo fix and pot update

- .travis.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3052)
> chore(travis-c): allow_failures test

- .travis.yml
- resources/themes/simple-black/master.css
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3056)
> chore(style): more black

- src/images_list.cpp
- src/images_list.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3057)
> fix(#3019): should now build on linux

- src/images_list.cpp
- src/images_list.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3065)
> chore(#3063): code tidy

- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3066)
> fix(#3012): duplicate button consistency

- .travis.yml
- src/images_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3071)
>  fix(#3019): simple warning when theme not found

- src/images_list.cpp
- src/images_list.h
- src/paths.cpp
- src/paths.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3074)
> feat(#3067): userthemes.zip processed

- resources/themes/colorful/status/DUPLICATE_STAT.svg
- resources/themes/default/status/DUPLICATE_STAT.svg
- resources/themes/simple-black/master.css
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3076)
> fix(#3067): white border

- src/reports/htmlbuilder.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3077)
> fix(#3075): tooltip fixed

- CMakeLists.txt
- resources/themes/default/status/DUPLICATE_STAT.svg
- resources/themes/default/status/EMPTY.svg
- resources/themes/default/status/FOLLOW_UP.svg
- resources/themes/default/status/RECONCILED.svg
- resources/themes/default/status/VOID_STAT.svg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3080)
> chore(#3079): circle

- CMakeLists.txt
- resources/themes/default/status/EMPTY.svg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3081)
> fix(#3079): revert cmake

- src/util.cpp
> fix(#651): new date mask

- resources/themes/colorful/readme.md
- resources/themes/colorful/status/UNRECONCILED.svg
- resources/themes/default/readme.md
- resources/themes/default/status/EMPTY.svg
- resources/themes/default/status/UNRECONCILED.svg
- resources/themes/simple-black/readme.md
- resources/themes/simple-black/status/UNRECONCILED.svg
- src/images_list.cpp
- src/images_list.h
- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3084)
> fix(#3079): added UNRECONCILED icon

- CMakeLists.txt
- src/build.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3086)
> chore(1.5.0): rc.1

- src/wizard_update.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3091)
> fix(#3087): refactoring

- .travis.yml
- src/mmex.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3097)
> fix(#3096): ignore .css in resorces

- src/images_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3098)
> fix(#3094): Protect from bad SVGs

- po/mmex.pot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3099)
> fix(#3094): pot file update

- src/images_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3102)
> fix(#3094): zip handling fixed

- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3108)
> chore(mmframe): nullptr

- CMakeLists.txt
- src/images_list.cpp
- src/mmex.cpp
- src/paths.cpp
- src/paths.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3109)
> fix(#3105): better use theme handling

- src/images_list.cpp
- src/paths.cpp
- src/paths.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3110)
> fix(#3106): to better understand the issue

- src/images_list.cpp
- src/images_list.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3112)
>  fix(#3111): check theme for compliance 

- po/mmex.pot
- src/images_list.cpp
> fix(#3111): format and translation

- src/paths.cpp
> chore(paths): enum

- src/images_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3119)
> fix(#3106): now starts OK on linux

- src/images_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3120)
> chore(#3106): cleanup

- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3122)
> chore(#3121): new ico change on event

- src/model/Model_Currency.cpp
- src/model/Model_Currency.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3124)
> chore(currency): speedup

- src/mmchecking_list.cpp
- src/stockspanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3128)
> fix(#3126): swapping column sort icons

- src/mmchecking_list.h
- src/mmcheckingpanel.cpp
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3132)
> fix(#3118): top item index calculation

- src/reports/mmDateRange.cpp
- src/reports/mmDateRange.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3133)
> fix(#3131): #3088

- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3135)
> fix(#3118): revert incorrect commit

- src/mmchecking_list.cpp
- src/mmchecking_list.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3138)
> fix(#3125): pasted transactions now selected

- src/reports/mmDateRange.cpp
- src/reports/mmDateRange.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3136)
> chore(mmDateRange): code format

- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3140)
> chore(mmframe): if to switch

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3141)
> fix(#3125): just select pasted

- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3143)
> chore(mmframe): if to switch revert incorrect changes

- resources/themes/yellow-blue/readme.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3144)
> fix(yellow-blue): added read.me

- src/accountdialog.cpp
- src/budgetingpanel.cpp
- src/budgetingpanel.h
- src/images_list.cpp
- src/mmchecking_list.h
- src/mmframe.cpp
- src/mmframe.h
- src/mmhomepage.cpp
- src/mmpanelbase.cpp
- src/mmpanelbase.h
- src/mmreportspanel.cpp
- src/reports/mmDateRange.cpp
- src/reports/mmDateRange.h
- src/webappdialog.cpp
@whalley I've made the changes. Could you test this on MAC and possibly on Linux?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3145)
> chore(test): simplification

- src/reports/mmDateRange.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3146)
> fix header file

- contrib.txt
> fix(donators): update

- src/accountdialog.cpp
- src/budgetingpanel.cpp
- src/budgetingpanel.h
- src/images_list.cpp
- src/mmchecking_list.h
- src/mmex.cpp
- src/mmhomepage.cpp
- src/mmpanelbase.h
- src/mmreportspanel.cpp
- src/reports/categexp.cpp
- src/reports/mmDateRange.cpp
- src/reports/mmDateRange.h
- src/reports/payee.cpp
- src/reports/reportbase.cpp
- src/reports/reportbase.h
- src/webappdialog.cpp
#3131 #3088
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3150)
> fix(revert): 231be73fb06f6734585d0645567842fb4e8c7d04

- src/mmcheckingpanel.cpp
- src/reports/mmDateRange.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3152)
> fix(#3131): future date

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3159)
> fix(#3157): fixed selection

- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3160)
> chore(VFS): simplification

- CMakeLists.txt
- src/build.h
> chore(version): up

- src/currencydialog.cpp
> fix(#3158): value

- CMakeLists.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3174)
> fix(#3172): Typo fixed

- src/themes.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3176)
> fix(#3170): memory

- src/currencydialog.cpp
- src/import_export/univcsvdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3181)
> V1.5.0 push to master

- src/themes.cpp
- src/themes.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3182)
> Theme Manager now uses wxHtmlWindow

- src/themes.cpp
@whalley please avoid fixed sizes for UI elements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3183)
> chore(UI): sizing

- src/payeedialog.cpp
- src/payeedialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3185)
> fix(#3184): wrong event

- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3186)
> fix(#3078): skip non Latin codes

- src/billsdepositspanel.cpp
- src/billsdepositspanel.h
- src/mmframe.cpp
- src/stockspanel.cpp
- src/stockspanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3191)
> fix(#3190): improvements

- src/mmframe.cpp
- src/mmframe.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3202)
> chore(mmframe): shared painter

- src/mmframe.cpp
> fix(mmframe): navigation panel selection

- src/assetspanel.cpp
- src/billsdepositspanel.cpp
- src/budgetingpanel.cpp
- src/mmchecking_list.cpp
- src/mmframe.cpp
- src/stockspanel.cpp
- src/util.cpp
- src/util.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3207)
> fix(#3166): gray background test

- src/CMakeLists.txt
- src/mmchecking_list.cpp
- src/stocks_list.cpp
- src/stocks_list.h
- src/stockspanel.cpp
- src/stockspanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3208)
> chore(cpp): split stocks files

- src/payeedialog.cpp
- src/payeedialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3211)
> fix(#3210): empty name

- src/assetspanel.cpp
- src/billsdepositspanel.cpp
- src/budgetingpanel.cpp
- src/images_list.cpp
- src/images_list.h
- src/mmchecking_list.cpp
- src/mmframe.cpp
- src/mmpanelbase.cpp
- src/optionsettingsview.cpp
- src/optionsettingsview.h
- src/stocks_list.cpp
- src/themes.cpp
- src/util.cpp
- src/util.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3213)
> fix(#3067): Metadata now supported

- src/images_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3215)
> fix(#3067): array indexing fix

- src/reports/budgetcategorysummary.cpp
- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3218)
> feat(#2130): bar/line for budget graphs

- src/reports/htmlbuilder.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3219)
> fix(#2877): small series resize

- src/images_list.cpp
- src/images_list.h
- src/import_export/univcsvdialog.cpp
- src/model/Model_Infotable.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3225)
> chore(wxColour): tidy

- src/assetspanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3229)
> fix(#3227): filter ico

- po/bg_BG.po
- po/cs_CZ.po
- po/de_DE.po
- po/el_GR.po
- po/en_GB.po
- po/en_US.po
- po/es_ES.po
- po/fr_FR.po
- po/he_IL.po
- po/hr_HR.po
- po/hu_HU.po
- po/id_ID.po
- po/it_IT.po
- po/ja_JP.po
- po/lt_LT.po
- po/nl_NL.po
- po/pl_PL.po
- po/pt_BR.po
- po/ru_RU.po
- po/sk_SK.po
- po/sq_AL.po
- po/sv_SE.po
- po/tr_TR.po
- po/vi_VN.po
- po/zh_CN.po
- po/zh_TW.po
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3232)
> fix(#3228): color

- contrib.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3235)
> chore(1.5.0): contributors

- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3243)
> fix(#3242): regex

- src/wizard_update.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3245)
> fix(#3237): hide unstable regarding options

- src/reports/htmlbuilder.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3248)
> fix(#3240): neg values in report data

- src/relocatepayeedialog.cpp
> fix(#3238): speedup

- src/import_export/univcsvdialog.cpp
> fix(#3252): Import info panel not expanded correctly

- src/wizard_update.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3259)
> fix(#3244): window fit

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3270)
> fix(#3267): simple implementation

- po/mmex.pot
- src/customfieldeditdialog.cpp
- src/customfieldeditdialog.h
- src/customfieldlistdialog.cpp
- src/customfieldlistdialog.h
- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmcheckingpanel.cpp
- src/model/Model_Checking.h
- src/model/Model_CustomField.cpp
- src/model/Model_CustomField.h
- src/model/Model_CustomFieldData.cpp
- src/model/Model_CustomFieldData.h
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3268)
> fix(#3265): custom fields for checking panel

- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3269)
> fix(#3239): goto transaction

- src/mmchecking_list.cpp
> fix(#3261): Transaction Balance and sort order

- src/CMakeLists.txt
- src/diagnostics.cpp
- src/diagnostics.h
- src/mmex.cpp
- src/mmframe.cpp
- src/mmframe.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3280)
> fix(#3222): added diagnostics menu

- src/customfieldeditdialog.cpp
- src/customfieldeditdialog.h
- src/customfieldlistdialog.cpp
- src/mmchecking_list.cpp
- src/model/Model_CustomField.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3284)
> fix(#3265): bug fixes

- src/billsdepositspanel.cpp
- src/billsdepositspanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3289)
> fix(#3267): bills panel user colors

- src/diagnostics.cpp
- src/diagnostics.h
- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3292)
> fix(#3222): current geometry added

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3296)
> fix(#3209): All Transactions panel currencies

- src/filtertransdialog.cpp
- src/filtertransdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3300)
> fix(#3298): from check points to listbox

- src/build.h
- src/mmcustomdata.cpp
- src/mmcustomdata.h
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3301)
> fix(#3299): bool value delete

- src/build.h
- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmcustomdata.cpp
- src/mmcustomdata.h
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3302)
> fix(#3299): #3298

- src/mmcustomdata.cpp
- src/mmcustomdata.h
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3305)
> fix(#3299): Customfielddata will not be delete

- src/budgetingpanel.cpp
- src/budgetingpanel.h
- src/optionsettingsview.cpp
- src/optionsettingsview.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3307)
> feat(#1292): new option - Budget Offset (days)

- src/import_export/univcsvdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3311)
> fix(#3310): negative withdrawals come in as zero

- src/import_export/export.cpp
- src/import_export/export.h
- src/import_export/qif_export.cpp
- src/import_export/qif_export.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3322)
> fix(#3319): simple csv export

- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3328)
> fix(#3326): UDFC01, 02... are not displayed in "All Transactions"

- src/optionsettingsgeneral.cpp
- src/util.cpp
- src/util.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3329)
> fix(#3323): wee DD Mon'YY date format

- src/themes.cpp
> fix(#3321): Theme manager window size

- src/import_export/univcsvdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3336)
> fix(#3315): tooltips

- src/mmex.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3338)
> fix(#3222): more 'loose' fit for screen

- src/maincurrencydialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3342)
> fix(#3340): minor fix

- src/budgetingpanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3344)
> fix(#3337): budget category translation

- CMakeLists.txt
- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3349)
> fix(#3348): Search by numbers on All Transactions view

- src/mmex.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3354)
> fix(mmex.cpp:362): useless cast to type 'double'

- src/maincurrencydialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3357)
> fix(#3340): flag and sizing

- src/mmhomepage.cpp
- src/mmhomepagepanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3358)
> fix(#3355): Upcoming transactions applet

- src/mmTextCtrl.cpp
- src/mmchecking_list.cpp
- src/model/Model_Currency.cpp
- src/model/Model_Currency.h
- src/stockspanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3366)
> fix(#3101): removed reliance on wxNumberFormatter

- src/model/Model_CustomField.cpp
> fix(linux): convert fix

- CMakeLists.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3371)
> fix(linux): cmake

- src/images_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3374)
> fix(linux): Implicit conversion failure from initializer list

- CMakeLists.txt
> fix(linux): build test

- src/currencydialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3383)
> fix(#3101):disable grp/dec/scale if locale used

- src/images_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3384)
> fix(#3382): refactoring

- src/currencydialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3385)
> fix(#3376): use last rate

- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3388)
> fix(#3362): shift key flipping

- src/mmex.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3389)
> fix(#3222): geometry bug fix

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3393)
> feat(#3375): multiple moves

- po/mmex.pot
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
- src/mmframe.h
- src/mmhomepagepanel.cpp
- src/mmhomepagepanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3398)
> fix(#3396): Account list loses focus when using keyboard navigation

- src/reports/categexp.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3402)
> fix(#3401): report date range fix

- src/currencydialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3404)
> fix(#3397): currency value/format

- src/import_export/export.cpp
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3406)
> fix(#3323): Date format display with Day name

- contrib.txt
- po/mmex.pot
- src/model/Model_Account.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3410)
> fix(#3409): Currency Manager right click issue

- src/util.cpp
cleanup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3421)
> fix(#3414): Crypto currencies exchange rate issue

- src/util.cpp
> fix(#3414): output format

- src/model/Model_Currency.cpp
- src/optionsettingsgeneral.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3426)
> fix(#3394): utf-8

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3428)
> fix(#3372): the ledger scrolls to the very last entry on ok

- src/optionsettingsgeneral.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3432)
> fix(#3394): locale name not valid

- src/stockspanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3444)
> fix(#3442): division by zero

- src/model/Model_Currency.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3446)
> fix(#3441): locale usage

- src/maincurrencydialog.cpp
> fix(#3448): to string

- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3451)
> fix(#3448): no matching function

- src/filtertransdialog.cpp
- src/model/Model_Category.cpp
- src/model/Model_Category.h
> fix(#3325): transaction report category settings

- src/import_export/univcsvdialog.cpp
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3461)
> fix(#3460): mon support

- src/mmchecking_list.cpp
- src/model/Model_Currency.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3467)
> fix(#3466): Inconsistent display of decimal places

- src/import_export/univcsvdialog.cpp
- src/util.cpp
- src/util.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3472)
> fix(#3469): date mask sort order

- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3475)
> fix(#3469): date mask new entries

- src/mmframe.cpp
Change ordering of Import & Export in the File menu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3476)
> fix(#3470): menu reordering

- src/import_export/univcsvdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3477)
> fix(#3471): Incorrect formatting of dates on Export dialog

- po/mmex.pot
- src/mmchecking_list.cpp
- src/mmchecking_list.h
'Delete all transactions in current view' and 'Delete Viewed "F / U" Transactions' does not delete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3481)
> fix(#3478): delete menu

- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3483)
> fix(#2914): multiselect transaction info

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3488)
> fix(#3482): paste transfer to correct account

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3489)
> v1.5.x to master (paste fix)

- src/mmcheckingpanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3490)
> fix(#2915): skip info panel on Mac

- src/import_export/univcsvdialog.cpp
- src/mmframe.cpp
- src/model/Model.h
- src/model/Model_Infotable.cpp
- src/model/Model_Infotable.h
> fix(#3484): rollback

- src/model/Model_Currency.cpp
> fix(#3494): value sign less than 1.0

- src/import_export/univcsvdialog.cpp
> fix(#3487): more transaction for preview

- src/mmframe.cpp
- src/mmframe.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3500)
> fix(#3498): Don't clear INUSE if never fully open

- po/mmex.pot
- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3501)
> fix(#3493): message

- src/import_export/univcsvdialog.cpp
> fix(#3504): notes multiple usage

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3506)
> fix(#3499): ensure visible

- src/import_export/univcsvdialog.cpp
> fix(#3504): notes place

- src/model/Model_Currency.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3511)
> fix(#3509): rounding fix

- src/model/Model_Currency.cpp
> fix(#3509): speedup

- src/optionsettingsgeneral.cpp
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3519)
> fix(#3518): date cache

- src/billsdepositspanel.cpp
- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
- src/stocks_list.cpp
> fix(#3517): att is added in notes

- src/attachmentdialog.cpp
- src/attachmentdialog.h
- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3522)
> fix(#3517): speedup

- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
> fix(#3517): tidy

- src/reports/categexp.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3524)
> feat(#35155): categories/monthly report also

- src/assetspanel.cpp
- src/billsdepositspanel.cpp
- src/budgetingpanel.cpp
- src/images_list.cpp
- src/images_list.h
- src/mmchecking_list.cpp
- src/mmframe.cpp
- src/stocks_list.cpp
@whalley make sure the code would work on osx, please
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3525)
> fix(#3510): background color

- .github/ISSUE_TEMPLATE/bug_report.md
- src/util.cpp
> fix(about): eol

- .appveyor.yml
- src/images_list.cpp
> fix(#3527): #3510

- src/images_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3531)
> fix(#3527): fix

- src/budgetingpanel.cpp
- src/images_list.cpp
- src/images_list.h
- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3533)
> fix(#3365): navigation panel font color

- 3rd/CMakeLists.txt
- src/images_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3534)
> fix(#3532): lunasvg library upgrade

- src/util.cpp
> fix(#3518): date mask

- src/model/Model_Currency.cpp
> fix(#3538): round before format

- src/model/Model_CurrencyHistory.cpp
- src/model/Model_CurrencyHistory.h
- src/reports/summary.cpp
> fix(#3479): simplification

- src/model/Model_Currency.cpp
> fix(#3538): compare with rounded value

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3542)
> fix(#3482): account check on paste

- contrib.txt
> fix(contrib): update

- po/mmex.pot
> fix(i10n): update pot file

- src/model/Model_Account.h
- src/reports/summary.cpp
> fix(#3479): annual results

- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3555)
> fix(lunasvg): version

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/billsdepositspanel.cpp
- src/billsdepositspanel.h
- src/mmhomepage.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Billsdeposits.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3553)
> fix(#3536): Recurring transaction fix / enhancement

- po/mmex.pot
- src/model/Model_Currency.cpp
- src/optionsettingsgeneral.cpp
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3560)
> fix(#3557): decimal separator

- src/billsdepositsdialog.cpp
- src/mmhomepage.cpp
- src/model/Model_Account.cpp
- src/model/Model_Currency.cpp
- src/model/Model_Currency.h
#3557
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3563)
> fix(#3558): only open account currency

- src/optionsettingsgeneral.cpp
> fix(#3559): locale widget rename

- po/mmex.pot
- src/mmframe.cpp
- src/mmframe.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3568)
> fix(#3319): MMEX CSV export menu

- src/wizard_update.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3569)
> fix(#3556): update wizard big link to new release

- src/billsdepositspanel.cpp
- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
- src/reports/transactions.cpp
- src/reports/transactions.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3570)
> fix(#3435): Transaction Report - multi-select for accounts

- resources/home_page.htt
- src/mmhomepage.cpp
- src/mmhomepagepanel.cpp
- src/reports/summary.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3571)
> fix(#3545): Asset & Share accounts are missing on Home Page

- po/en_US.po
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3572)
> fix(#3399): US favourites -> favorites

- CMakeLists.txt
- po/bg_BG.po
- po/cs_CZ.po
- po/de_DE.po
- po/el_GR.po
- po/es_ES.po
- po/fr_FR.po
- po/he_IL.po
- po/hr_HR.po
- po/hu_HU.po
- po/id_ID.po
- po/it_IT.po
- po/ja_JP.po
- po/lt_LT.po
- po/mmex.pot
- po/nl_NL.po
- po/pl_PL.po
- po/pt_BR.po
- po/ro_RO.po
- po/ru_RU.po
- po/sk_SK.po
- po/sq_AL.po
- po/sv_SE.po
- po/tr_TR.po
- po/vi_VN.po
- po/zh_CN.po
- po/zh_TW.po
- resources/home_page.htt
- src/mmhomepage.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3573)
> fix(#3545): sorting

- src/mmhomepagepanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3578)
> fix(#3545): totals

- .github/FUNDING.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3579)
> fix(#2200): add a sponsor button in MMEX GitHub repository

- BUILD.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3580)
> fix(#2406): MacOS build

- src/filtertransdialog.cpp
- src/images_list.cpp
- src/import_export/univcsvdialog.cpp
- src/mmreportspanel.cpp
- src/model/Model_CustomField.cpp
- src/util.cpp
- src/webapp.cpp
- src/wizard_update.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3581)
> fix(#3325): Transaction Report settings name utf8 support

- src/themes.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3582)
> fix(#2066): theme splitter

- src/general_report_manager.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3584)
> fix(#2066): grm splitter

- src/model/Model_Currency.cpp
- src/optionsettingsgeneral.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3586)
> fix(#3585): null pointer

- src/model/Model_Currency.cpp
> fix(#3587): test locale before use

- src/mmhomepage.cpp
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3592)
> fix(#3590): best font change and minor css fix

- CMakeLists.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3595)
> dark-mode theme added to system-themes

- src/assetspanel.cpp
- src/billsdepositspanel.cpp
- src/images_list.cpp
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
- src/stockspanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3600)
> fix(#1779): win specific update

- src/model/Model_Account.cpp
- src/model/Model_Account.h
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3605)
> fix(#3604): MacOS fix

- src/import_export/univcsvdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3609)
> fix(#3607): date format

- src/currencydialog.cpp
- src/optionsettingsgeneral.cpp
- src/optionsettingsgeneral.h
> fix(#3587): save invalid locale option

- src/accountdialog.cpp
- src/accountdialog.h
- src/model/Model_Currency.cpp
- src/optiondialog.cpp
- src/optiondialog.h
- src/optionsettingsgeneral.cpp
- src/optionsettingsview.cpp
- src/sharetransactiondialog.cpp
- src/sharetransactiondialog.h
- src/util.cpp
- src/util.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3612)
> fix(#3587): locale usage

- src/util.h
> fix(#3587): default to def

- CMakeLists.txt
- src/model/Model_Account.cpp
- src/model/Model_Account.h
- src/transactionsupdatedialog.cpp
- src/transactionsupdatedialog.h
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3618)
> fix(#3606): multi-trans edit fix

- src/categdialog.cpp
- src/general_report_manager.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3623)
> fix(#3620): wxTreeCtrls to use NAVPANEL theme

- src/reports/summary.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3628)
> fix(#3627): formatting fix

- po/zh_CN. po
Add part of simplified Chinese Translation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3635)
> 更新并将zh_CN.po重命名为zh_CN。波

- CMakeLists.txt
- po/mmex.pot
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3637)
> fix(#3632): plus linux

- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3641)
> fix(#3636): date format

- src/customfieldeditdialog.cpp
- src/mmcustomdata.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3642)
> fix(#3639): wxchoice index

- src/reports/budgetcategorysummary.cpp
- src/reports/budgetingperf.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3646)
> fix(#1832): Budget reports for financial year

- src/option.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3654)
> fix(#3651): bulk trans setting fix

- src/mmframe.cpp
- src/mmframe.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3655)
> fix(#3643): Manual WebApp refesh

- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3657)
> fix(#3643): added confirmation dialog

- src/optionsettingsview.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3661)
> fix(#3660): consistent naming

- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3662)
> fix(#3643): consistent naming

- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3663)
> fix(#3660): proper fix for inconsistency!

- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3664)
> fix(#3660): doh!

- src/maincurrencydialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3670)
> fix(#3667): Handling when base curr not yet set

- src/mmhomepage.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3674)
> fix(#3673): widget closure fix

- src/sharetransactiondialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3675)
> fix(#3644): commision fix

- src/sharetransactiondialog.cpp
- src/sharetransactiondialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3676)
> fix(#3644):commision plus or minus

- BUILD.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3688)
> fix(docs): build instructions typo

- CMakeLists.txt
- src/transactionsupdatedialog.cpp
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3712)
> fix(#3696): Wording change

- src/filtertransdialog.cpp
- src/filtertransdialog.h
@vomikan Can you test on Windows please... UPDATE: Have tested and looks OK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3713)
> fix(#3686): search by colour

- src/billsdepositsdialog.cpp
- src/option.h
- src/optionsettingsmisc.cpp
- src/payeedialog.cpp
- src/payeedialog.h
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3718)
> fix(#3711): default categories

- src/budgetingpanel.cpp
- src/categdialog.cpp
- src/filtertransdialog.cpp
- src/model/Model_Category.cpp
- src/model/Model_Category.h
- src/reports/budgetcategorysummary.cpp
- src/reports/categexp.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3725)
> fix(#3724): Do not always translate categories

- src/accountdialog.cpp
- src/assetdialog.cpp
- src/assetspanel.cpp
- src/attachmentdialog.cpp
- src/billsdepositsdialog.cpp
- src/billsdepositspanel.cpp
- src/budgetingpanel.cpp
- src/categdialog.cpp
- src/customfieldlistdialog.cpp
- src/filtertransdialog.cpp
- src/images_list.cpp
- src/images_list.h
- src/import_export/univcsvdialog.cpp
- src/maincurrencydialog.cpp
- src/mmcheckingpanel.cpp
- src/payeedialog.cpp
- src/sharetransactiondialog.cpp
- src/stockdialog.cpp
- src/stockspanel.cpp
- src/transdialog.cpp
- src/usertransactionpanel.cpp
- src/webappdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3726)
> fix(#3188): button icon size fixes

- src/model/Model_Category.cpp
- src/model/Model_Category.h
- src/reports/budgetingperf.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3734)
> fix(#3733): Financial year budget reporting

- .github/ISSUE_TEMPLATE/bug_report.md
- contrib.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3739)
> fix(up): update

- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3741)
> fix(#3738): original primary display size

- .github/PULL_REQUEST_TEMPLATE.md
> fix(pr): info

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3744)
> fix(#3740): logic fix

- po/mmex.pot
- src/maincurrencydialog.cpp
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3751)
> fix(#3743): toDouble -> toCDouble

- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3755)
> fix(#3748): transaction report transfers fix

- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
- src/reports/transactions.cpp
- src/reports/transactions.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3757)
> fix(#3756): advanced filter fix and tidy-up

- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmframe.cpp
- src/mmframe.h
- src/mmpanelbase.cpp
- src/mmpanelbase.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3760)
> feat(#3678): credit remaining display

- src/mmchecking_list.cpp
- src/mmpanelbase.cpp
- src/mmpanelbase.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3761)
> feat(#3678): code tidy

- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3762)
> feat(#1964): report per currency amount

- CMakeLists.txt
- src/assetspanel.cpp
- src/dbupgrade.cpp
- src/general_report_manager.h
- src/images_list.h
- src/import_export/export.h
- src/import_export/qif_import.cpp
- src/import_export/qif_import_gui.cpp
- src/mmSimpleDialogs.h
- src/mmTips.h
- src/mmcheckingpanel.h
- src/mmcombobox.h
- src/mmframe.cpp
- src/mmframereport.cpp
- src/mmhelppanel.h
- src/optiondialog.h
- src/reports/htmlbuilder.cpp
- src/splitdetailsdialog.h
- src/splittransactionsdialog.cpp
- src/stockdialog.cpp
- src/transdialog.h
- src/usertransactionpanel.h
- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3769)
> fix(c): Nikolay Akimov

- src/mmframe.cpp
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3773)
> fix(#3763): Crash fix

- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3782)
> fix(#3780): cat focus change fix

- src/reports/summarystocks.cpp
- src/reports/summarystocks.h
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3788)
> fix(#3785): trans type change behaviour

- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3792)
> fix(#3785): Payee/From label switching fix

- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/summarystocks.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3793)
> fix(#3786):report tidy

- src/import_export/univcsvdialog.cpp
- src/model/Model_Currency.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3798)
> fix(#3783): Type=Deposit now works

- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3801)
> fix(#3800): panel header fix for big currency

- po/mmex.pot
- src/model/Model_Attachment.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3806)
> fix(#3797): attachment label translation

- src/option.cpp
- src/option.h
- src/optionsettingsview.cpp
- src/optionsettingsview.h
- src/reports/categexp.cpp
- src/reports/forecast.cpp
- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/incexpenses.cpp
- src/reports/mmDateRange.cpp
- src/reports/mmDateRange.h
- src/reports/myusage.cpp
- src/reports/payee.cpp
- src/reports/summarystocks.cpp
- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3811)
> feat(#3781): user start of month

- src/reports/categexp.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3812)
> fix(#3781): cat monthly fix

- src/reports/categexp.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3813)
> fix(#3781): end date fix

- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3816)
> fix(#3781): fix transaction report

- src/images_list.cpp
- src/option.cpp
- src/option.h
- src/optionsettingsview.cpp
- src/optionsettingsview.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3827)
> feat(#3818): option to force theme variant

- src/billsdepositsdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3832)
> fix(#3830): fix disable spinner

- po/mmex.pot
- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/reports/transactions.cpp
- src/wizard_update.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3825)
> fix(#3804): git hub download page

- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/transactions.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3835)
> fix(#3820): color marker

- src/mmframe.cpp
- src/reports/budgetcategorysummary.cpp
- src/reports/budgetingperf.cpp
- src/reports/cashflow.cpp
- src/reports/categexp.cpp
- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/incexpenses.cpp
- src/reports/myusage.cpp
- src/reports/payee.cpp
- src/reports/summary.cpp
- src/reports/summarystocks.cpp
- src/reports/transactions.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3836)
> fix(#3820): html builder simplification

- docs/en/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3841)
> fix(#3828): typo fix

- src/reports/budgetingperf.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3844)
> fix(#3820): budget perf month column fix

- src/optionsettingsview.cpp
- src/optionsettingsview.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3848)
> fix(#3846): html scale spin workaround MacOS

- src/billsdepositsdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3850)
> fix(#3815): Recurring trans type switch fix

- src/model/Model_Currency.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3854)
> fix(#3800): long long

- src/optiondialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3856)
> fix(#3847): wxTRANSLATE not N_

- src/currencydialog.cpp
- src/mmcustomdata.cpp
- src/mmhomepage.cpp
- src/model/Model_Currency.cpp
- src/reports/htmlbuilder.cpp
- src/util.cpp
- src/util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3866)
> fix(#3865): speedup

- CMakeLists.txt
- contrib.txt
- src/filtertransdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3868)
> fix(ver): up

- src/reports/mmDateRange.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3871)
> fix(#3870): Date Range fix

- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3872)
> fix(#3763): ctrl+n global fix

- src/billsdepositspanel.cpp
- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
- src/reports/transactions.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3878)
> fix(#3863): stage 2

- src/import_export/univcsvdialog.cpp
- src/import_export/univcsvdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3881)
> fix(#3877): leave import view open after import

- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/reportbase.cpp
- src/reports/summary.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3891)
> feat(#3890): Stacked area chart

- CMakeLists.txt
- src/paths.cpp
- src/themes.cpp
- src/themes.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3962)
> fix(3961): separate folder for themes

- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3963)
> fix(3961): simplification

- .gitmodules
- CMakeLists.txt
- src/general_report_manager.cpp
- src/paths.cpp
- src/paths.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3964)
> fix(#3961): initialization

- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3966)
> fix(#3961): cmake for grm reports

- CMakeLists.txt
- src/paths.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3969)
> fix(#3961): subfolders removed

- src/CMakeLists.txt
- src/filtertrans.cpp
- src/filtertrans.h
- src/mmreportspanel.cpp
- src/reports/budgetingperf.cpp
- src/reports/budgetingperf.h
- src/reports/categexp.cpp
- src/reports/categexp.h
- src/reports/payee.cpp
- src/reports/payee.h
- src/reports/reportbase.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3971)
> feat(#3283): report transactions

- src/filtertrans.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3972)
> fix(#3283): simplification

- src/reports/summarystocks.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3973)
> fix(#3926): linux fix?

- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3974)
> feat(#3945): Period on transaction report

- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3975)
> fix(#3961): zip more report packages

- CMakeLists.txt
- src/paths.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3978)
> fix(#3961): grm packages

- README.TXT
- src/transdialog.cpp
- src/transdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3989)
> Autocomplete of "Account" not working on MacOS

- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3994)
> fix(#3988): bug fix

- src/billsdepositsdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4000)
> fix(#3995): copy notes and trans number

- src/relocatepayeedialog.cpp
- src/relocatepayeedialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4001)
> fix(#3996): reallocation dialog fix

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4003)
> fix(#4002): Duplicate now same and new

- src/mmcustomdata.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4005)
> fix(#3598): fix text save

- src/mmhomepage.cpp
- src/util.cpp
- src/util.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4008)
> fix(#4007): homepage notes for recurring trans

- src/mmex.cpp
- src/reports/transactions.cpp
- src/util.cpp
- src/util.h
fix(#4014): exclude grm from VFS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4015)
> fix(#2334): yahoo exchange rates issue

- src/maincurrencydialog.cpp
- src/model/Model_Account.cpp
- src/model/Model_Currency.cpp
- src/option.cpp
- src/option.h
- src/wizard_newdb.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4021)
> fix(#4019): is used

- CMakeLists.txt
- src/reports/htmlbuilder.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4026)
> fix(#4025): test disable animations

- src/mmreportspanel.cpp
- src/reports/budgetcategorysummary.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4027)
> fix(#4023): Bdgt Cat Summary cat links

- src/model/Model_Currency.cpp
- src/option.cpp
- src/optionsettingsview.cpp
- src/reports/categexp.cpp
- src/reports/mmDateRange.cpp
- src/reports/mmDateRange.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4040)
> fix(#4036): dates calculation

- src/reports/categexp.cpp
- src/wizard_update.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4043)
> fix(#4038): direct link for binary file

- src/reports/cashflow.cpp
- src/reports/forecast.cpp
- src/reports/htmlbuilder.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4050)
> fix(#4048): datetime iso format

- contrib.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4057)
> fix(v1.5.11): sync

- src/filtertransdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4064)
> feat(#4009): save presentation options

- src/transactionsupdatedialog.cpp
- src/transactionsupdatedialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4067)
> feat(#3897): multi-edit enhancements

- src/payeedialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4071)
> fix(#4070): case-insensitive payee name change

- src/payeedialog.cpp
- src/payeedialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4073)
> fix(#4032): faster payee dialog

- src/mmcheckingpanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4079)
> fix(#3669): wording clarification

- BUILD.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4083)
> Minor MacOS build changes

- src/model/Model_Category.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4088)
> fix(#4085): Categories split handling fix

- src/transactionsupdatedialog.cpp
- src/transactionsupdatedialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4093)
> fix(#3897): consider advanced transactions

- src/filtertrans.cpp
- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/reports/budgetcategorysummary.cpp
- src/reports/budgetingperf.cpp
- src/reports/cashflow.cpp
- src/reports/categexp.cpp
- src/reports/forecast.cpp
- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/incexpenses.cpp
- src/reports/mmDateRange.cpp
- src/reports/mmDateRange.h
- src/reports/myusage.cpp
- src/reports/payee.cpp
- src/reports/summarystocks.cpp
- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4094)
> fix(#4092): ignore future transactions

- src/mmchecking_list.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4109)
> fix(#4098): ctrl + a

- src/mmchecking_list.cpp
- src/mmchecking_list.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4111)
> feat(#4110): Jump between accounts for transfers

- src/mmhomepage.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4119)
> fix(#4118): rates as is

- src/reports/summarystocks.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4121)
> fix(#4120): stock graph fix?

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/billsdepositspanel.cpp
- src/billsdepositspanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4125)
> feat(#4124):Duplicate recurring option

- src/mmframe.cpp
- src/stockspanel.cpp
- src/stockspanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4128)
> fix(#4127): Stocks panel refresh fix

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4131)
> fix(#4065): hotkey addition

- docs/en_GB/index.html
- src/filtertransdialog.cpp
- src/mmchecking_list.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Checking.cpp
- util/fake.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4134)
> fix(#4065): "None" now "Unreconciled"

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4136)
> fix(#4065): 'Mark as' menu tidy

- po/de_DE.po
- src/reports/summary.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4140)
> fix(#4116): cleanup

- CMakeLists.txt
- contrib.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4146)
> chore(version): update

- BUILD.md
Updated:
3. Download Sources
4. Compile and Create Package
See https://forum.moneymanagerex.org/viewtopic.php?p=22666#p22666
Install section for Linux kept as it is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4148)
> Linux section of BUILD.md updated

- BUILD.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4149)
> Linux build formatting tidy

- src/reports/summary.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4153)
> fix(#4150): Summary report fix

- src/reports/mmDateRange.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4158)
> fix(#4155): last month

- src/reports/htmlbuilder.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4161)
> fix(#4150): rounding corrrection

- src/billsdepositsdialog.cpp
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4166)
> fix(#4139): UI change for Freq Used Notes

- src/mmchecking_list.cpp
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4169)
> fix(#4168): clone custom fields

- src/billsdepositsdialog.cpp
- src/payeedialog.cpp
- src/transdialog.cpp
- src/transdialog.h
@whalley could you, please, investigate this changes regarding how it would works in MAC?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4178)
> fix(#4031): call payee dialog by enter press

- src/attachmentdialog.cpp
- src/attachmentdialog.h
- src/billsdepositsdialog.cpp
- src/mmchecking_list.cpp
- src/optionsettingsattachment.cpp
- src/optionsettingsattachment.h
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4185)
> fix(#4183): clone attachments

- src/model/Model_Account.cpp
- src/model/Model_Currency.cpp
- src/optionsettingsgeneral.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4192)
> fix(#4191): fmt update

- src/optionsettingsgeneral.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4197)
> fix(#4191): cleanup

- src/reports/categexp.cpp
- src/reports/htmlbuilder.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4198)
> fix(#3998): refinements

- src/reports/summary.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4201)
> fix(#4200): fix yearly summary report

- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4211)
> fix(#4207): max size

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/billsdepositspanel.cpp
- src/billsdepositspanel.h
- src/mmchecking_list.cpp
- src/mmcustomdata.cpp
- src/model/Model_CustomFieldData.cpp
- src/model/Model_CustomFieldData.h
- src/transactionsupdatedialog.cpp
- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4218)
> fix(#4159): Add Custom Fields to Recurring Transactions 

- src/payeedialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4229)
> fix(#4227): fix to allow add new payee

- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4234)
> fix(#4233): HTLEncode fix

- src/categdialog.cpp
- src/categdialog.h
- src/db/DB_Table.h
- src/payeedialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4236)
> fix(#4235): case insensitive sorting

- src/constants.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4243)
> fix(#4242): RSS feed updated URL

- src/db/DB_Table.h
- util/sqlite2cpp.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4245)
> fix(#4235): db script fix

- src/images_list.cpp
- src/images_list.h
- src/mmframe.cpp
- src/optiondialog.cpp
- src/util.cpp
- src/util.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4246)
> fix(#4241): icon size fix

- src/filtertransdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4252)
> fix(#4240): Compress filter list text

- src/filtertransdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4254)
> fix(#4239): Transfer In/Out

- src/reports/mmDateRange.cpp
- src/reports/mmDateRange.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4259)
> fix(#4258): code tidy

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4261)
> fix(#4260): day of week on recurring dialog

- src/filtertransdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4262)
> fix(#4258): comparison between signed and unsigned integer expressions

- src/filtertransdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4263)
> fix(#4258): old-style cast

- contrib.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4267)
> fix(chore): update sponsors

- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4271)
> fix(#4269): wxgtk

- .appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4289)
> fix(#2590): test

- contrib.txt
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4292)
> fix(#4286): htm to be named

- .appveyor.yml
- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4294)
> fix(#4290): test

- .appveyor.yml
- CMakeLists.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4300)
> fix(#3241): test

- src/images_list.cpp
- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4303)
> fix(#4302): update

- src/import_export/export.cpp
- src/import_export/export.h
- src/import_export/qif_export.cpp
- src/model/Model_Category.cpp
- src/model/Model_Category.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4308)
> fix(#4307): all or used categories export

- src/mmpanelbase.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4309)
> fix(#4305): column id

- src/mmcustomdata.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4316)
> fix(#4314): All custom fields editable

- src/import_export/export.cpp
- src/import_export/qif_export.cpp
- src/import_export/univcsvdialog.cpp
- src/import_export/univcsvdialog.h
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4315)
> fix(#4312): transfer

- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmcustomdata.cpp
- src/mmcustomdata.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4318)
> fix(#4314: filter changes

- src/filtertransdialog.cpp
- src/mmchecking_list.cpp
- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4324)
> fix(#4319: custom fields in trans report

- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmcustomdata.cpp
- src/mmcustomdata.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4326)
> fix(4320): clear custom fields

- src/import_export/qif_import_gui.cpp
- src/import_export/qif_import_gui.h
- src/model/Model_Setting.cpp
- src/model/Model_Setting.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4342)
> fix(#4341): brows file enhancement

- src/model/Model_Setting.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4349)
> fix(#4341): simplification

- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4351)
> fix(#4159): auto execute fix for custom fields

- src/import_export/qif_import_gui.cpp
> fix(#4341): account name

- src/import_export/qif_import_gui.cpp
- src/util.cpp
> fix(#4341): date parser

- src/model/Model_Checking.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4364)
> fix(#4352): Frequently used notes sort order

- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/model/Model_Infotable.cpp
- src/model/Model_Infotable.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4369)
> fix(#4250): allow more than 10 saved transaction filters

- src/billsdepositsdialog.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Billsdeposits.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4372)
> fix(#4360): fix

- src/mmframe.cpp
- src/mmframe.h
- src/mmframereport.cpp
- src/model/Model_Setting.cpp
- src/model/Model_Setting.h
- src/util.cpp
- src/util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4373)
> fix(#3750): refactoring

- src/filtertransdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4375)
> fix(#4250): accounts and payee list empty

- src/mmframe.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4385)
> fix(#4250): refresh on changes

- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmframe.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4386)
> fix(#4250): change settings

- CMakeLists.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4387)
> chore(v1.5.15beta2): We are still on 1.5.15

- src/filtertransdialog.cpp
- src/model/Model_Infotable.cpp
- src/model/Model_Infotable.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4392)
> fix(#4250): erase and update functions added

- src/filtertransdialog.cpp
- src/mmframe.cpp
- src/model/Model_Infotable.cpp
- src/reports/htmlbuilder.cpp
> fix(#4250); date validation

- src/filtertransdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4397)
> fix(#4250): date fix

- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmframereport.cpp
- src/model/Model_Infotable.cpp
- src/model/Model_Infotable.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4406)
> fix(#4250): Filters now sorted

- src/filtertransdialog.cpp
- src/filtertransdialog.h
The non-obvious redundant menu has been removed.
> fix(#4250): simplification

- po/mmex.pot
- src/mmframe.cpp
> fix(#4334): phrases update

- contrib.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4413)
> chore(contrib.txt): Update

- src/reports/transactions.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4414)
> fix(#4401): kbd style added

- src/filtertransdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4415)
> fix(#4401): boolean options support

- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/reports/transactions.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4421)
> fix(#4419): refactoring

- src/filtertransdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4422)
> fix(#4419): show real dates for ranges

- src/filtertransdialog.cpp
- src/filtertransdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4425)
> fix(#4419): cleanup

- src/appstartdialog.cpp
- src/appstartdialog.h
- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4426)
> fix(#4418): change language at startup

- src/filtertransdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4440)
> fix(#4419): payee list

- .appveyor.yml
- util/sqlite2cpp.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4442)
> fix(#4436): python 3

- po/mmex.pot
- src/billsdepositsdialog.cpp
- src/filtertransdialog.cpp
- src/import_export/qif_import_gui.cpp
- src/import_export/qif_import_gui.h
- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- src/transactionsupdatedialog.cpp
- src/transactionsupdatedialog.h
- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4455)
> fix(#4420): color for QIF

- src/filtertransdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4458)
> fix(#4419): startday fix

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/import_export/qif_import_gui.cpp
- src/import_export/qif_import_gui.h
- src/transactionsupdatedialog.cpp
- src/transactionsupdatedialog.h
- src/transdialog.cpp
- src/transdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4460)
> fix(#4459): unification

- src/filtertransdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4461)
> fix(#4419): del filter selection

- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmframe.cpp
- src/mmframe.h
- src/model/Model_Infotable.cpp
- src/model/Model_Infotable.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4466)
> fix(#4419): nav mendu edit/delete

- po/mmex.pot
- src/general_report_manager.cpp
- src/general_report_manager.h
- src/mmhomepagepanel.cpp
- src/mmreportspanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4467)
> fix(#4465): cleanup

- src/filtertransdialog.cpp
- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4468)
> fix(#4419): tidy

- src/filtertransdialog.cpp
- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4471)
> fix(#4459): color id

- src/mmcustomdata.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4474)
> fix(#4472): deafult fix

- po/mmex.pot
- src/customfieldeditdialog.cpp
- src/customfieldeditdialog.h
- src/customfieldlistdialog.cpp
- src/customfieldlistdialog.h
- src/mmframe.cpp
- src/model/Model_CustomField.cpp
- src/model/Model_CustomField.h
- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4475)
> fix(#4159): attribute of

- src/mmframe.cpp
- src/mmframe.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4479)
> fix(#4478): rename filter setting

- po/mmex.pot
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4482)
> fix(#4480): advanced filter save removed

- src/mmcheckingpanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4486)
> fix(#4480): account switch

- src/mmframe.cpp
- src/mmframe.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4487)
> fix(#4483): disable HOME collapse

- src/filtertransdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4488)
> fix(#4480): fix

- src/filtertransdialog.cpp
- src/filtertransdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4502)
> fix(#4480): separate filter settings for all transactions

- src/billsdepositsdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4513)
> fix(#3277): ok button focus

- src/filtertransdialog.cpp
- src/mmSimpleDialogs.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4522)
> fix(#4439): reference

- src/mmSimpleDialogs.cpp
- src/model/Model_Category.cpp
- src/model/Model_Category.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4525)
> fix(#4439): MacOS autocomplete handling

- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- src/model/Model_Account.cpp
- src/model/Model_Account.h
- src/transdialog.cpp
- src/transdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4530)
> fix(#4439): refactoring

- src/mmchecking_list.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4541)
> fix(#3419): extra info on focused deleted

- src/categdialog.cpp
- src/categdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4553)
> fix(#4550): #4548

- src/filtertransdialog.cpp
- src/reports/transactions.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4557)
> fix(#2232): advanced regexp

- src/filtertransdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4558)
> fix(#4419): all accounts label

- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/incexpenses.cpp
- src/reports/summary.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4559)
> fix(#4542): support sortable tables

- src/import_export/univcsvdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4578)
> fix(#4577): color button from other button size

- po/ru_RU.po
- src/import_export/univcsvdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4579)
> fix(v1.5.15): sync

- src/mmSimpleDialogs.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4586)
> fix(#4439):fix wxcombo fill on Mac

- contrib.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4589)
> chore(contrib.txt): add new sponsor

- src/billsdepositsdialog.cpp
- src/transactionsupdatedialog.cpp
- src/transdialog.cpp
- src/usertransactionpanel.cpp
- src/wizard_newdb.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4595)
> fix(#4290): sizer changes  to accomodate wx3.1.7

- src/splittransactionsdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4596)
> fix(#4591): wrong constant

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/splittransactionsdialog.cpp
- src/splittransactionsdialog.h
- src/transdialog.cpp
- src/transdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4597)
> fix(#4439): category for transaction dialog

- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4598)
> fix(#4439): mistakes

- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4599)
> fix(#4439): transfer

- src/wizard_newaccount.cpp
- src/wizard_newdb.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4600)
> fix(#4290): Minor textctrl size changes

- src/splittransactionsdialog.cpp
- src/transdialog.cpp
- src/wizard_newaccount.cpp
- src/wizard_newdb.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4606)
> fix(#4439): mac build fix

- src/billsdepositsdialog.cpp
- src/mmTextCtrl.h
- src/splitdetailsdialog.cpp
- src/splitdetailsdialog.h
- src/splittransactionsdialog.cpp
- src/splittransactionsdialog.h
- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4608)
> fix(#4591): old school dialog added

- src/splitdetailsdialog.cpp
- src/splitdetailsdialog.h
- src/splittransactionsdialog.cpp
- src/splittransactionsdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4613)
> fix(#4591): tuning

- contrib.txt
- src/mmreportspanel.cpp
- src/reports/reportbase.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4626)
> fix(#4621): save BUDGET_DATES

- src/billsdepositsdialog.cpp
- src/filtertransdialog.cpp
- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- src/optionsettingsgeneral.cpp
- src/splitdetailsdialog.cpp
- src/splittransactionsdialog.cpp
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4629)
> Combobox simplification?

- src/mmSimpleDialogs.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4632)
> fix(#4625): sorting/filtering

- src/mmSimpleDialogs.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4634)
> fix(#4439): change insertion point

- src/billsdepositspanel.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Billsdeposits.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4635)
> fix(#4633): payee name consistency

- src/mmcheckingpanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4636)
> fix(#4625): speedup

- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- src/model/Model_Billsdeposits.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4638)
> fix(#4633): fix and tidy

- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4639)
> fix(#4237): fix size check

- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4640)
> fix(#4620): last used for payee

- src/mmchecking_list.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4653)
> fix(#4652): extra info

- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4667)
> fix(#4663): test compact size

- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- src/transdialog.cpp
- src/transdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4668)
> fix(#4620): options implemented

- src/filtertransdialog.cpp
- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- src/model/Model_Payee.cpp
- src/model/Model_Payee.h
- src/relocatecategorydialog.cpp
- src/relocatecategorydialog.h
- src/relocatepayeedialog.cpp
- src/relocatepayeedialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4669)
> fix(#4439): relocates refactoring

- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4670)
> fix(#4662): category splits fix

- src/relocatepayeedialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4671)
> fix(#4439): Mac clang compatibility

- src/mmcustomdata.cpp
> fix(#4651): invalid id

- src/filtertransdialog.h
- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4689)
> fix(#4680): add label to title

- src/mmex.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4693)
> fix(#4692): disallow closure if dialog open

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/transdialog.cpp
- src/transdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4697)
> fix(#4620): existing tran payee chg and tidy

- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4703)
> fix(#4439): #3634

- CMakeLists.txt
- contrib.txt
- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- src/transactionsupdatedialog.cpp
- src/transactionsupdatedialog.h
- src/transdialog.cpp
- src/transdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4709)
> mmDatePickerCtrl

- src/splittransactionsdialog.cpp
- src/splittransactionsdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4718)
> fix(#4712): stage 1

- src/transdialog.cpp
- src/transdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4721)
> fix(#4710): advanced transfer simplification

- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4722)
> fix(#4716): calc fix on enter

- src/assetdialog.cpp
- src/assetdialog.h
- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- src/mmcustomdata.cpp
- src/mmcustomdata.h
- src/mmex.cpp
- src/stockdialog.cpp
- src/stockdialog.h
- src/transactionsupdatedialog.cpp
- src/usertransactionpanel.cpp
- src/usertransactionpanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4729)
> fix(#4708): mmDataPickerCtrl - part 2

- src/categdialog.cpp
- src/mmSimpleDialogs.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4732)
> Select new category

- src/splittransactionsdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4737)
> fix(#4712): tuning

- src/splittransactionsdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4746)
> fix(#4712): fix for MacOS

- src/import_export/univcsvdialog.cpp
- src/import_export/univcsvdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4750)
> fix(#4745): export type

- src/import_export/univcsvdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4751)
> fix(#4745): export type case unsensitive

- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4760)
> fix(#4717): stop onward event processing

- src/budgetingpanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4764)
> fix(#4763): increase size

- .appveyor.yml
- CMakeLists.txt
- util/FindwxWidgets.cmake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4766)
> fix(#4759): experiment 2

- contrib.txt
- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4769)
> fix(#4768): void amount representation

- src/accountdialog.cpp
- src/accountdialog.h
- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/import_export/qif_export.cpp
- src/import_export/qif_export.h
- src/import_export/qif_import_gui.cpp
- src/import_export/qif_import_gui.h
- src/maincurrencydialog.cpp
- src/maincurrencydialog.h
- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- src/mmreportspanel.cpp
- src/mmreportspanel.h
- src/model/Model_Report.cpp
- src/sharetransactiondialog.h
- src/stockdialog.cpp
- src/stockdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4771)
> fix(#3139): MacOS calendar control for dates

- src/mmSimpleDialogs.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4773)
> fix(#4708): avoid weekday name clipping

- src/billsdepositsdialog.cpp
- src/mmSimpleDialogs.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4774)
> fix(#4759): fix cast

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4776)
> fix(#4772): recurring dialog consistency

- src/mmSimpleDialogs.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4777)
> fix(#4708): reposition week day name

- src/mmSimpleDialogs.cpp
- src/util.cpp
- src/util.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4781)
> fix(#4371): test

- src/wizard_newaccount.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4782)
> fix(#2704): change to wording

- src/billsdepositsdialog.cpp
- src/optionsettingsview.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4788)
> fix(#4786): MacOS scale factor fix

- src/filtertransdialog.cpp
- src/filtertransdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4790)
> fix(#4789): checkbox for including sub categories

- src/util.cpp
non latin chars support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4795)
> fix(#47450: date parser

- src/mmframe.cpp
- src/mmframe.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4799)
> fix(#4791): wxAuiToolBar

- .appveyor.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4800)
> fix(#4759): v3.2.0 GA

- src/optionsettingsattachment.cpp
- src/optionsettingsgeneral.cpp
- src/optionsettingshome.cpp
- src/optionsettingsmisc.cpp
- src/optionsettingsnet.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4801)
> fix(#4754): wxScrolledWindow for options

- po/en_GB.po
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4810)
> fix(#4804): colour

- src/categdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4831)
> fix(#4828): duplicate check fix

- src/mmframereport.cpp
- src/mmreportspanel.cpp
- src/mmreportspanel.h
- src/reports/cashflow.cpp
- src/reports/cashflow.h
- src/reports/reportbase.cpp
- src/reports/reportbase.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4839)
> fix(#4830): part 1

- src/mmreportspanel.cpp
- src/reports/cashflow.cpp
- src/reports/cashflow.h
- src/reports/reportbase.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4842)
> fix(#4830): part 2

- src/billsdepositsdialog.cpp
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4847)
> fix(#4838): fill category on payee from dialog

- src/accountdialog.cpp
- src/assetdialog.cpp
- src/assetspanel.cpp
- src/attachmentdialog.cpp
- src/attachmentdialog.h
- src/mmframe.cpp
- src/payeedialog.cpp
- src/stockdialog.cpp
- src/stocks_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4848)
> fix(#3226): reference name used where available

- src/mmreportspanel.cpp
- src/mmreportspanel.h
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4849)
> fix(#4154): allows Linux build

- src/attachmentdialog.cpp
- src/model/Model_Asset.cpp
- src/model/Model_Asset.h
- src/model/Model_Stock.cpp
- src/model/Model_Stock.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4851)
> fix(#3226): reworked

- src/optionsettingsnet.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4856)
> fix(#4827): options fit

- src/mmSimpleDialogs.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4864)
> fix(#4863): macOS calendar improvement

- src/optionsettingsattachment.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4866)
> fix(#4827): attachment combobox sizing

- src/mmcustomdata.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4873)
> fix(#4867): decimal precision fix

- .circleci/config.yml
- CMakeLists.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4884)
> chore(v1.5.19): beta 1

- src/relocatecategorydialog.cpp
- src/relocatepayeedialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4889)
> fix(#4887): button naming change

- src/mmSimpleDialogs.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4893)
> fix(#4892): combobox pattern match anywhere

- .circleci/config.yml
- src/payeedialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4894)
> fix(moneymanagerex#4880): added MacOS build

- dockers/ubuntu.bionic/Dockerfile
- dockers/ubuntu.focal/Dockerfile
- dockers/ubuntu.jammy/Dockerfile
- src/accountdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4898)
> #4880 and #4897

- src/transdialog.cpp
- src/transdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4906)
> fix(#4886): category for a payee test 2

- src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4908)
> fix(#4905): make toolbar plain

- src/categdialog.cpp
- src/categdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4910)
> fix(#4885): category dialog search addition

- src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4912)
> fix(#4886): default category

- .circleci/config.yml
- dockers/fedora.36/Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4916)
> fix(#4880): added fedora 36

- src/filtertransdialog.h
- src/mmcustomdata.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4929)
> fix(#4922): field id calculation fix

- src/categdialog.cpp
- src/categdialog.h
- src/mmcustomdata.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4930)
> fix(#4919): don't allow colon in name

- src/mmcustomdata.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4936)
> fix(#4921): space as thousands sep

- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/summary.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4937)
> fix(#4934): summary as stacked bar / line

- src/mmcustomdata.cpp
- src/mmcustomdata.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4942)
> fix(#4921): mmTextCtrl for decimal

- src/mmTextCtrl.cpp
- src/mmTextCtrl.h
- src/mmcustomdata.cpp
- src/mmcustomdata.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4944)
> fix(#4921): fixes

- src/mmcustomdata.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4947)
> fix(#4921): decimal checkbox selection on typing

- .circleci/config.yml
- CMakeLists.txt
- src/accountdialog.cpp
- src/accountdialog.h
- src/assetdialog.cpp
- src/assetdialog.h
- src/currencydialog.cpp
- src/currencydialog.h
- src/mmTextCtrl.h
- src/sharetransactiondialog.cpp
- src/sharetransactiondialog.h
- src/splittransactionsdialog.cpp
- src/stockdialog.cpp
- src/stockdialog.h
- src/transdialog.cpp
- src/transdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4958)
> fix(#4946): mmTextCtrl fixes part 1

- src/reports/summary.cpp
- src/reports/summary.h
Fixed incorrect 'Summary of Accounts' report due to not applying historic exchange rates. Issue: #4116
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4959)
> Fixed: Incorrect 'Summary of Accounts'

- src/mmhomepage.cpp
- src/model/Model_Stock.cpp
- src/stocks_list.cpp
Calculate Gain/Loss based on current stocks prices and stock transactions history
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4952)
> Fix: Invalid calculation Stocks Gain/Loss (Issue #4122)
