- doc/version.txt
- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/billsdepositspanel.cpp
- src/billsdepositspanel.h
- src/mmframe.cpp
- src/mmhomepagepanel.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Billsdeposits.h
On existing databases, all Repeating Transactions need to be edited to reset the due date.
> feat(Repeating.Transactions): replace next occurance with payment and due dates

- src/import_export/qif_import_gui.cpp
- src/import_export/qif_import_gui.h
Issue #377. Parse the !Account "type" line and create the
appropriate MMEX type of account for newly created accounts.
> fix(QIF.Import): QIF import of accounts

- src/budgetingpanel.cpp
- src/model/Model_Attachment.cpp
- src/model/Model_Attachment.h
- src/model/Model_Category.cpp
- src/model/Model_Category.h
- src/model/Model_Infotable.cpp
- src/model/Model_Infotable.h
- src/payeedialog.cpp
- src/payeedialog.h
- src/reports/budget.cpp
- src/reports/budgetcategorysummary.cpp
- src/reports/budgetingperf.cpp
- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/webapp.cpp
- src/webapp.h
- src/webappdialog.cpp
- src/webappdialog.h
- src/wizard_update.cpp
- src/wizard_update.h
We get the best performance from passing primitive types by value. This is because:
- primitives are blitable, so the cost of the copy depends on the size
- primitives are small, only double and long long are bigger than a reference in most environments
- pass-by-value avoids aliasing, allowing the optimizer to really do its thing
> fix(Code): passing primitive types by value not reference

- src/billsdepositspanel.cpp
- src/mmcheckingpanel.cpp
- src/mmpanelbase.cpp
> fix(ColumnWidthSettings): saving settings in list destructor

- Makefile.in
- build/bakefiles/mmex.bkl
Put help files in the correct place for app bundle. Bakefile not tested, changes to Makefile.in work as expected.
> chore(Mac.Build): fixes to build commands for mac

- src/mmframe.cpp
@loki36 please check where a function\code is used befor change it (#454).
Here we need to show privacy at startup to inform users that we will collect usage statistics.
Thanks
> fix(aboutdialog): Show privacy tab at startup

- src/reports/cashflow.cpp
It looks like there were extra numRepeats decrementation and caused a bug with double counting repetitions.
> fix(cashflow): remove extra numRepeats decrement, fixes issue #459

- build/bakefiles/mmex.bkl
Help files currently can't access master.css. This provides a copy of it in the same location as the help files so they can access it
> refactor(help.bakefile): Allow help files to access css

- doc/help/budget.html
- doc/help/french/index.html
- doc/help/french/investment.html
- doc/help/general_report_manager.html
- doc/help/hungarian/budget.html
- doc/help/hungarian/index.html
- doc/help/hungarian/investment.html
- doc/help/index.html
- doc/help/italian/index.html
- doc/help/italian/investment.html
- doc/help/polish/budget.html
- doc/help/polish/index.html
- doc/help/russian/index.html
- doc/help/russian/investment.html
- doc/help/spanish/budget.html
- doc/help/spanish/index.html
- doc/help/spanish/investment.html
* Removed absolutely redundant formatting in English help files
* Table of Contents in English help files is now generated by Javascript
* Redid the <h*> formatting in the English to generate above table of contents
* English files are virtually HMTL5 compliant
* All languages now link to the stylesheet
> Help clean

- resources/mmex.desktop
- setup/linux/build_rpm.sh
- setup/linux/variables.sh
* Added some build-deps
* Removed some deprecated things from spec file and made more use of in built macros
* rpmlint now comes back clean
* wxGTK3-devel provides wx-config-3.0 instead of wx-config as needed by the build scripts
* Problem with languages
* Don't think I've got all build-deps
* Haven't listed the runtime deps
> refactor(linux.rpm): Improved RPM build script

- po/italian.po
- src/constants.cpp
- src/constants.h
- src/currencydialog.cpp
- src/currencydialog.h
- src/maincurrencydialog.cpp
- src/maincurrencydialog.h
- src/mmOptionGeneralSettings.cpp
- src/model/Model_Currency.cpp
- src/model/Model_Currency.h
- src/model/Model_CurrencyHistory.cpp
- src/model/Model_CurrencyHistory.h
- src/model/Model_Infotable.cpp
- src/model/Model_Infotable.h
- src/wizard_newdb.cpp
Unfortunately there isn't any free service to download currency history, so I've implemented download from BCE (European Central Bank) website, but it's a quite big XML (4MB) from 1999 until today so a bit slow to download & parse.
I've implemented a sort of cache that won't re-download the file until stay in Currency Dialog, but first time executed it will take some time. Do you think we need to add a warning that could take some time to execute? On my i5 Notebook it's quite fast (about 6 sec) but I don't know on slowest machines..
Now remains open only step 3: implement values in total and amount logics.
> feat(currency.history): Download history from BCE

- src/model/Model_Currency.cpp
This closes issue #489
(Added `BTC` at the end of the vector)
> fix(bug.489): Added Bitcoin (Ƀ) support

- src/maincurrencydialog.cpp
- src/model/Model_CurrencyHistory.cpp
- src/model/Model_CurrencyHistory.h
- src/reports/incexpenses.cpp
I've converted IncExpenses with new CurrencyHistory.
Please test and, if working fine, I'll update also other reports.
We should think about a way to obtain nearest currency value if not present for a specific date.
I've tried with the commented code in Model_CurrencyHistory.cpp but it's quite slow so I preferred to use BASECONVRATE for now.
> feat(CurrencyHistory): converted IncExpenses

- src/paths.cpp
Fixes an issue where the homepage will not display if wxGetUserName() returns a string with special characters (') on Mac.
> fix(issue.559): additional mac fix

- resources/home_page.htt
- src/general_report_manager.cpp
- src/mmframereport.cpp
- src/model/Model_Report.cpp
- src/reports/htmlbuilder.cpp
- src/reports/myusage.cpp
See https://msdn.microsoft.com/en-us/library/ee330730(v=vs.85).aspx and https://kevinragsdale.net/windows-10-and-the-web-browser-control/
I've noticed that on my system also Avira Antivirus add a keys and sets to 11001.
Tested and working fine with VS2015 too.
PS: I've replaced fixed "mmex.exe" with EXE name so it will works fine with renamed EXE too
> fix(IE): revert #606 with minor changes

- build/msw-vc-2015/mmex_mmex.vcxproj
- build/msw-vc-2015/mmex_mmex.vcxproj.filters
- src/import_export/parsers.cpp
- src/import_export/parsers.h
- src/import_export/univcsvdialog.cpp
- src/import_export/univcsvdialog.h
- src/mmframe.cpp
- src/mmframe.h
Can now import transactions for a file saved by excel in XML format (Save as->Other formats-> XML Spreadsheet 2003).
* I debated between creating a new dialog or adding it to the CSV dialog. I chose to use the CSV dialog and simply cut out the parser sections. This actually removes duplicate code that was used for both preview and import.
* Only import is currently supported, not export.
* Data is imported from first spreadsheet in workbook.
* The concept of printing a few lines of the source file to an edit box to allow the user to choose fields doesn't work with XML. Instead of having the fields list determine the number of columns, the parser determines the number of columns. Any column that does not have a corresponding field we be set to "Don't care". This will now be the case for …
> feat(Import.XML): import XML files in excel format

- src/import_export/univcsvdialog.cpp
- src/model/Model_Currency.cpp
- src/model/Model_Currency.h
- Don't try to delete the export file if it didn't exist.
- Export raw numbers with no formatting except precision.
so that they can be easily parsed by external programs (e.g. Excel)
> fix(Export.XML): existing file bug and thousand separator bug

- src/billsdepositsdialog.cpp
- src/filtertransdialog.cpp
- src/import_export/univcsvdialog.cpp
- src/mmframe.cpp
- src/mmhelppanel.cpp
- src/reports/reportbase.cpp
- src/splittransactionsdialog.cpp
The final string in the issue is caused by all of the wxTRANSLATE calls in src/db/DB_Table_Currencyformats_V1.h
> fix(strings): Fix extra spaces in strings (#757)

- src/reports/summary.cpp
> fix(#768) dateStart field re-declaration

- src/currencydialog.cpp
- src/maincurrencydialog.cpp
- src/mmcheckingpanel.cpp
- src/mmtextctrl.h
- src/model/Model_Currency.cpp
- src/model/Model_Infotable.cpp
- src/model/Model_Infotable.h
- src/option.cpp
- src/option.h
- src/optionsettingsgeneral.cpp
- src/wizard_newaccount.cpp
- src/wizard_newdb.cpp
- prevent event generation in middle of calculation
- set Base Currency in Option.h
- Clarification in Option dialog for Base Currency settings
- Updated Database submodule.
> fix(BaseCurrency.Option.Setting): prevent system failure

- src/mmex.cpp
- src/mmex.h
Best to stop another instance rather than having MMEX crash.
Stop gap measure until problem with mongoose initialisation fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/830)
> fix(Multiple.Instance): prevent 2nd instance crash

- appveyor.yml
- doc/version.txt
- src/util.cpp
- Update Version Details
- Change alternate colour on transactions to allow better distinction between transaction selection and the alternate line.
- Addition of build number to the **mmex.exe** file produced by AppVeyor. Allows easy addition to test platform and test comparison between builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/870)
> Miscellaneous Updates

- src/mmcheckingpanel.cpp
Affects issues #788 and #841
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/874)
> fix(issue.#788): Transaction colour tag lost in specific case

- src/import_export/univcsvdialog.cpp
Hi MMX team
Very attracted by MMEX for its very customisable reporting, I found my first bug when importing my first CSV file with custom format:  only the Deposit lines are taken into account, Withdraw lines are discarded with error message ".
Could you please have a look? Thanks!
* MMEX 1.2.7
* Mac OSX 10.11.3
1. Create a fresh new database
* Single account with GBP currency
* Create a CSV file with the following two lines (minimal example, anything bigger will exhibit the same problem):
2016-06-29,PaymentOut,10.0,0.0
2016-06-30,PaymentIn,0.0,10.0
* Import with `Date Format` set to `YYYY-MM-DD` and the following fields list:
a. Date
b. Payee
c. Withdrawal
d. Deposit
* Click `Import`.
* Two new lines in the account:
1. one for the PaymentOut with a Withdrawal of 10.0
2. one for the …
> Withdrawals not imported from CSV

- src/model/Model_Asset.cpp
This uses the Actual / 365 (fixed) method which is a very commonly used method and appears to be the one the user is expecting although his number is off by one day. This is the method that I would recommend using but if we want to use the Actual / Actual method (or another method), I can change the math to do that but it is a little more involved because you have to count the number of days that apply to 365 and the number of days that apply to 366 (leap year) and then combine the two interest values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/946)
> fix(#846): Changed appreciation and depreciation to be compounded daily

- src/import_export/qif_import_gui.cpp
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
Mark as "Duplicate" the same transactions if present as 'Transfer' in QIF file for another account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1010)
> fix(#1008): dublicate status for the same trx

- src/sharetransactiondialog.cpp
m_commission_ctrl is NULL when this function runs for the first several times.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1190)
> fix(#1111): fix crash on Linux when adding stock transactions

- src/general_report_manager.cpp
This removes following compile warning:
```
/moneymanagerex/src/general_report_manager.cpp: In member function 'bool mmGeneralReportManager::openZipFile(const wxString&, wxString&, wxString&, wxString&, wxString&, wxString&)':
/moneymanagerex/src/general_report_manager.cpp:577:18: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
std::auto_ptr<wxZipEntry> entry;
^~~~~~~~
In file included from /usr/include/c++/6/bits/locale_conv.h:41:0,
from /usr/include/c++/6/locale:43,
from /usr/include/c++/6/iomanip:43,
from /moneymanagerex/3rd/cajun/json/writer.inl:16,
from /moneymanagerex/3rd/cajun/json/writer.h:62,
from /moneymanagerex/src/db/DB_Table.h:31,
from /moneymanagerex/src/model/Model.h:35,
from /moneymanagerex/src/model/Model_Report.h:22,
from …
```
> fix(compile): remove deprecated std::auto_ptr

- src/import_export/univcsvdialog.cpp
Implemented add/remove item if double clicked on fields list in CSV import/export dialog. No need to select list element and then click on Add or Remove button!
[Tested](https://github.com/slodki/moneymanagerex/releases/tag/test-dblclk-import) on linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1202)
> feat(import.csv.dialog): implement LISTBOX_DCLICK

- src/dbupgrade.cpp
- src/general_report_manager.cpp
This will add `MMEX` application ID (=1296909656) to a newly created or updated sqlite database file header as described in #1206.
```
$ hexdump -C test.mmb | head
00000000  53 51 4c 69 74 65 20 66  6f 72 6d 61 74 20 33 00  |SQLite format 3.|
00000010  10 00 01 01 00 40 20 20  00 00 00 5a 00 00 00 40  |.....@  ...Z...@|
00000020  00 00 00 00 00 00 00 00  00 00 00 2e 00 00 00 04  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 01 00 00 00 07  |................|
00000040  00 00 00 00 4d 4d 45 58  00 00 00 00 00 00 00 00  |....MMEX........|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 5a  |...............Z|
00000060  00 2d fd 71 05 00 00 00  02 0f f6 00 00 00 00 35  |.-.q...........5|
00000070  0f fb 0f f6 0c e5 0b b1  0b 5a 0a 4c 0b 1b 09 d8  |.........Z.L....| …
```
> feat(sqlite): add Application ID to sqlite database header

- src/filtertransdialog.cpp
- src/import_export/qif_export.cpp
- src/import_export/univcsvdialog.cpp
- src/mmcheckingpanel.cpp
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
- src/reports/transactions.cpp
- src/transdialog.cpp
- src/transdialog.h
This sets the status of a transfer as a 2 character token instead of one.
The database status is recorded as NN for both sides being unreconciled but is viewed as normal in Account View.
When the A side is reconciled and B side as Follow-up the database shows RF.
Viewing the transactions, the A side will show the status as R and viewing the B side will show as F
On changeover, both sides of a transaction will assume the current status for both sides until it is modified by the update. Reverting back and remodifying the transaction will restore to original.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1208)
> #1180 Split transaction Status for Transfers

- src/optionsettingsview.cpp
A little wider version using foreground color working with wxGTK2 port (should close #1226):
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1227)
> fix(#1226): use foreground button color in View Options dialog

- .github/ISSUE_TEMPLATE.md
- src/constants.cpp
- src/dbupgrade.cpp
- src/mmframe.cpp
Pre-fill bug report template for Help->Report a Bug.
Update GitHub ISSUE_TEMPLATE.md.
When user use `Help`->`Report a Bug` menu command following page will be opened:
Rendered as:
Similar changes are introduced to issues created directly from GitHub website:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1225)
> feat(bug.report): new pre-filled bug report template for GitHub

- CMakeLists.txt
Don't use hard-coded build system versions.
Use official redist files for target build architecture.
This fixes #1228
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1258)
> fix(#1228): distribute build target architecture matched Windows dlls

- src/mmframe.cpp
- src/optionsettingsview.cpp
Also correct compile warnings for Unicode characters \u2b25 \u2588
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1263)
> fix(#1256): disable toolbar icons when no database

- src/import_export/univcsvdialog.cpp
- src/mmframe.cpp
Add details to diagnostic messages (for user and log).
Fix wrong total lines number displayed.
Update progress meter to show real values.
Change all counters to the same type (long).
Select summary pop-up icon and buttons depending on import result.
Commented out messages never displayed to user.
This should help users to diagnose problems with CSV imports (like #1277).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1291)
> Fix errors and add detailed messages in mmUnivCSVDialog

- CMakeLists.txt
Allows the mmexini.db3 file to be excluded from the build
when using the CMake GUI to produce project files for MSVS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1317)
> fix(CMake.GUI.Build): allow portable installation option in build

- README.md
Docker Hub markdown doesn't support indented multiline links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1332)
> fix(doc): make readme links syntax docker hub markdown compatible

- src/webserver.cpp
Using %zu is portable way to print size_t
This will fix #1347 compile warning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1350)
> fix(#1347): use %zu from C99

- .travis.yml
- dockers/opensuse/Dockerfile
openSUSE Tumbleweed doesn't have wx webview (no webkitgtk support)
See issue #1331 on GitHub
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1356)
> fix(travis): don't build openSUSE Tumbleweed

- src/budgetingpanel.cpp
- src/budgetingpanel.h
- src/option.cpp
- src/option.h
- src/optionsettingsview.cpp
- src/optionsettingsview.h
- src/reports/budgetcategorysummary.cpp
- src/reports/budgetingperf.cpp
This option advances or retards the start date from the 1st of the
month or year for a budget by the budget offset in days.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1355)
> feat(#1292): new option - Budget Offset (days)

- src/maincurrencydialog.cpp
- src/maincurrencydialog.h
We shouldn't use *History...* function name while downloading current values...
@lexa2 #1391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1394)
> clean(#1391): fix function names in PR#1391

- .travis.yml
- dockers/linuxmint.sonya/Dockerfile
- dockers/linuxmint.sylvia/Dockerfile
Mint 18.3 is prepared but not build because Docker Hub image is not available so far.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1416)
> feat(docker): add support for new Linux Mint releases to fix #1409

- .appveyor.yml
My CMake patches where included in upstream CMake 3.10 version
used in latest AppVeyor environment.
They are still usable for users using older CMake version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1425)
> fix(appveyor): skip CMake patches already applied in AppVeyor env

- dockers/ubuntu.zesty.x86/Dockerfile
- dockers/ubuntu.zesty/Dockerfile
Ubuntu moved zesty repos to old-releases as no longer maintained.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1428)
> fix(docker): update ubuntu zesty repos after EOL

- .travis.yml
- util/Brewfile
This reverts commit 532956ffcaf8df2804297c74a84bd965706b8699, reversing
changes made to 7ee698c8f3d9083b4dc0aa7e459668c9822a8e42.
Changes introduced by @stephengroat #1359 breaks Travis CI builds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1457)
> Revert "Merge pull request #1359 from stephengroat/brew-bundle"

- src/images_list.cpp
- src/images_list.h
- src/stockdialog.cpp
- src/stockspanel.cpp
Use icon from #1397 for stock updates too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1494)
> feat(icons): replace LED_OFF icon with CURRATES in stock dialogs

- dockers/debian.jessie.x86/Dockerfile
- dockers/debian.jessie/Dockerfile
This is fix for #1511. lua5.3 is available only from backports in Jessie
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1518)
> fix(docker): use lua5.2 for Ubuntu Jessie

- BUILD.md
There is CMake patch for MSVC compiler included in #1547 from upstream
CMake 3.12.0 release and build instructions should be updated as stated in #1553
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1554)
> fix(#1553): update BUILD.md after #1547

- 3rd/CMakeLists.txt
- dockers/debian.buster.x86/Dockerfile
- dockers/debian.buster/Dockerfile
- dockers/debian.jessie.x86/Dockerfile
- dockers/debian.jessie/Dockerfile
- dockers/debian.stretch.x86/Dockerfile
- dockers/debian.stretch/Dockerfile
- dockers/ubuntu.xenial.x86/Dockerfile
- dockers/ubuntu.xenial/Dockerfile
- po/pl.po
- src/aboutdialog.cpp
- src/constants.cpp
- src/dbwrapper.cpp
- src/dbwrapper.h
- src/mmframe.cpp
- src/mmframe.h
- src/util.cpp
- src/util.h
Allow to create new encrypted db.
Consolidate and reuse code.
Fix accidental wxSQLite3 downgrade in #1558 
Fixes #1493 too.
Enforces old MMEX cipher used.
We must wait for wxSQLite3 packages upgrade in Linux distros to use #1321 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1562)
> refactor(encryption): don't store db password in memory

- src/constants.cpp
- src/mmframe.cpp
- src/mmframe.h
- src/model/Model_Infotable.cpp
Check if new db can be loaded before closing current db
Check if file selected from recent files is already opened
Refactor common code in mmFrame
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1569)
> fix(#1566): clean GUI before ShutdownDatabase() call

- src/dbwrapper.cpp
- src/mmTips.h
- src/mmframe.cpp
- src/mmframe.h
- src/optionsettingsattachment.cpp
Use .mmb extension for both encrypted and unencrypted db files
Allow encrypt/decrypt database on-the-fly without need to open/close file and extension change
Autodetect if password is required for file to open
File->New and File->Save As allow to select between encrypted or not file
but creates .mmb files in both cases
File->Open displays .mmb and .emb in one view and ask for password when required
Tools->Database->Set Password encrypts current database or change password if encrypted already
Tools->Database->Remove Password decrypts current database file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1573)
> feat(encryption): autodetect encrypted databases

- src/mmCalculator.cpp
- src/mmCalculator.h
See results below:
```
20:41:38: Debug: check_syntax: input = "434", res = 1
20:42:12: Debug: check_syntax: input = "))(((34656345)", res = 1
20:45:38: Debug: check_syntax: input = "*56)+((5647562-)", res = 1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1599)
> clean(mmCalc): remove useless check_syntax()

- src/constants.cpp
- src/constants.h
- src/optionsettingsnet.cpp
- src/optionsettingsnet.h
- src/wizard_update.cpp
- src/wizard_update.h
This implements #1278
Manually prepare update records for website is no longer required.
Latest release description from GitHub is presented to user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1640)
> Use GitHub Releases API for update checking

- src/reports/cashflow.cpp
Cash flow report crashes if recurring transaction different then transfer is defined.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1682)
> fix(cashflow): fix SEGFAULT in cashflow report

- src/mmframe.cpp
Resolve #658 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1766)
> Fix disappearing items

- src/mmframe.cpp
All GNU/Linux software I know (except maybe for EagleCAD) use Ctrl-Q as "Exit" hotkey. Having Alt-X in mmex renders the function keyless for anyone who's used to typical key combination
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1765)
> Enhancement: change exit hotkey to Ctrl-Q on Linux

- src/reports/cashflow.cpp
This fixes bug from #1644
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1781)
> fix(cashflow): don't crash on an account without transactions

- .appveyor.yml
AppVeyor uses latest CMake 3.12.1 now: https://www.appveyor.com/updates/2018/08/29/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1790)
> fix(appveyor): AppVeyor environment upgrade

- src/splitdetailsdialog.cpp
Split amount will have the same look&feel like trans amount.
Added missing call to calculator after click on OK button (we don't use focus change here).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1793)
> fix(#1750): remove std::fabs from amount field in SplitDetailDialog

- src/wizard_update.cpp
There will be error response returned from GitHub Releases API:
> HTTP/1.1 403 Forbidden
> Date: Tue, 20 Aug 2013 14:50:41 GMT
> Status: 403 Forbidden
> X-RateLimit-Limit: 60
> X-RateLimit-Remaining: 0
> X-RateLimit-Reset: 1377013266
> {
>    "message": "API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
>    "documentation_url": "https://developer.github.com/v3/#rate-limiting"
> }
if user check for MMEX updates more then 60 requests per hour. This brakes current implementation expecting array of releases in JSON response.
It will be detected and handled now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> fix(checkUpdates): workaround for GitHub API rate limit exceeded error

- src/categdialog.cpp
While fixing this issue I noticed the other buttons suffered similar errors due to the early return in some situations, this PR means that those states are now handled at the end of the function based on the resulting state, so fixes them all as far as I can tell from my testing. Feel free to edit if I've misunderstood the expected behaviour in any circumstance but this seems intuitive to me as a user now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1943)
> fix(#1942): fix categories dialog button enable state behaviour

- INSTALL.md
Workaround for #1801 using original `script.deb.sh` quick-install script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2081)
> fix(#1801): update INSTALL for Linux Mint

- docs/de/index.html
- docs/en/index.html
- docs/es/index.html
- docs/fr/index.html
- docs/hu/index.html
- docs/it/index.html
- docs/js/lang_menu.js
- docs/manual.css
- docs/pl/index.html
- docs/ru/index.html
Removes external `flag-icon.min.css` from user manual pages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2095)
> style(lang_menu): use pure UTF-8 for flag icons

- src/CMakeLists.txt
`#pragma execution_character_set("utf-8")` is added in-the-fly to all MMEX sources when compiled with VS2013. VS2015 and later uses `/utf-8` compiler option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2113)
> Remove compiler warnings for VC2013

- dockers/debian.jessie.x86/Dockerfile
- dockers/debian.jessie/Dockerfile
This will fix #2114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2115)
> fix(docker): jessie-backports moved to archive.debian.org

- src/reports/htmlbuilder.cpp
It's unclear if some reports' values are calculated in the account currency or default currency.
This PR will always print currency symbol in reports.
This simply replaces `Model_Currency::toString()` with `Model_Currency::toCurrency()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2162)
> feat(htmlbuilder): always print curr symbol

- resources/home_page.htt
- src/general_report_manager.cpp
- src/mmreportspanel.cpp
- src/reports/budgetingperf.cpp
- src/reports/categexp.cpp
- src/reports/reportbase.cpp
- src/reports/summary.cpp
- src/reports/transactions.cpp
There are multiple problems with reports panel's toolbar:
1. `wxStaticText` labels are cropped
2. labels are not vertically aligned with controls
3. right-most controls are invisible when MMEX window is resized
The first problem can be easily fixed by resizing the MMEX window, but 2nd and 3rd problems remain.
All problems are fixed:
1. `mmSetOwnFont()` is added to fix `wxStaticText` with changed font settings
2. `wxALIGN_CENTER_VERTICAL` is added to the text labels
3. `wxBoxSizer` is replaced with `wxWrapSizer` to always display all report controls
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2163)
> Fix reports panel layout

- src/mmframe.cpp
- src/mmreportspanel.cpp
- src/model/Model_Usage.cpp
- src/model/Model_Usage.h
- src/reports/myusage.cpp
Simplified usage data as proposed in #1699.
BTW: All `USAGE_V1.JSONCONTENT` values are not valid JSON !
```
22:07:25: Debug: ===== mmGUIApp::OnExit ===========================
22:07:25: Debug: RapidJson
{
"start": "2019-06-18 22:05:05",
"end": "2019-06-18 22:07:25",
"usage": [
{"module":"Home Page","seconds":0.453},
{"module":"Report","name":"Category Income/Expenses - Last 12 Months","seconds":0.115},
{"module":"Report","name":"Categories - Over Time","seconds":0.061},
{"module":"Report","name":"Cash Flow","seconds":0.072},
{"module":"Report","name":"mmReportTransactions","seconds":0.311},
{"module":"Report","name":"Where the Money Goes - Over Time","seconds":0.059},
{"module":"Checking Panel","seconds":0.069},
{"module":"Checking Panel","seconds":0.091},
{"module":"Checking …
```
> refactor(usage): replace date and time with msecs

- src/billsdepositsdialog.cpp
- src/model/Model_Billsdeposits.cpp
Billsdeposits dialog crashes without warning when the dialog is saved without account selected.
Now pop-up about account will be displayed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2289)
> fix(billsdepositsdialog): check if account is not null

- CMakeLists.txt
Update to avoid errors when running CMake on Arch. 
Checks if the "arch-release" file exists to identify an Arch distro.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2619)
> fix(CMakeList.txt): Fix to detect Arch Linux

- src/util.cpp
fix for dates like this:
```D8/ 1' 7```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2755)
> fix(#1718): yy parser

- src/mmreportspanel.cpp
Alignment was slightly inconsistent when present edon MacOs. Have given all the elements same alignment that fixes this.
Tested on OSX and windows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2774)
> made reports panel alignment consistent

- src/mmex.cpp
- src/mmex.h
Added correct closure method for __WXMAC__ builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2781)
> fix(#2405): Now closes gracefully when closed from OSX dock

- src/mmframe.cpp
Test on OSX and Windows.
OSX seems a bit more particular about the control/toolbar ordering when the toolbar is hidden!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2783)
> fix(2766): toolbar creation order caused OSX issue

- src/reports/categexp.cpp
- src/reports/htmlbuilder.cpp
- src/reports/incexpenses.cpp
- src/reports/myusage.cpp
- src/reports/payee.cpp
Added support for presenting negative values in tooltips for Pie Charts. Had to revert recent change to donut charts as the central labels on these don;t seem to support formatters that allow the negative values to be presented. Moving back to Pie charts has not lost any real value with the bonus of this fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2821)
> fix(#2028): Negative values on tooltips for pie

- src/reports/htmlbuilder.cpp
Used std::ostringstream with a 'classic' locale to avoid locale dependent output from usual string formatters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2834)
> fix(#2832): chartdata now locale independent

- src/mmcheckingpanel.h
Won't build on MacOS without the class def.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2869)
> fix(mmex): big file split - clang needed

- src/constants.cpp
- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/util.cpp
I'm hoping that by avoiding having to keep track of leftclick/select/unselect/focus events it will make the logic easier to understand. Just need to pull the list of selected transactions when needed.
Have done testing to check that major functionality works, possibly a few edges cases....  Please test.
Todo: Consider ditching the class wide m_selected_id and just use as a local variable, also need to consider if we should add back in the 'Number of Selected Transactions, etc (though not convinced about usefulness of date range and balance, etc. Could also easily support MOVE of multiple transactions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2899)
> fix(#2848): refactor to avoid click counting

- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
Regardless of what GetSelectedItemCount says, when OnListItemFocused is called I think we always have more than one transaction highlighted
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2901)
> fix(#2848): updateExtraTransactionData correction

- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
Another few fixes as I spotted things...
One thing I did notice is that it always opens an account on the first transaction irrespective of ordering... Don't think I changed that behavior but I don't think it worked like that in earlier releases (unless I'm going mad - could be possible!)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2902)
> fix(#2848): fixed a few bugs

- src/filtertransdialog.cpp
> fix(#3325): utf8 support for settings name

- src/mmchecking_list.cpp
Key events should use captured key in event rather than reading current active keystate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3438)
> fix(#3396): tidy key handling to use event data

- src/reports/budgetingperf.cpp
> fix(#1832): useless cast to type 'int'

- src/mmex.cpp
- src/mmex.h
Works for me in Linux (Fedora 34, Spanish locale), but I'm a light user. Please don't merge until someone confirms it doesn't break anything and works for the other systems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3690)
> fix(#3619): set locale

- src/mmex.cpp
MMEX always opens on display 0, which may not always be the primary display. This PR adds a small loop to find the primary display and use it instead. If `IsPrimary()` returns false for all displays display 0 is used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3728)
> Default to primary display when creating mmGuiFrame

- src/constants.cpp
- src/constants.h
- src/maincurrencydialog.cpp
- src/util.cpp
- src/util.h
Quick hack to search coincap.io after yahoo if Yahoo can't find a crypto symbol.
fixes #3743
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3747)
> fix(#3743): use coincap if yahoo can't find crypto price

- src/maincurrencydialog.cpp
- src/util.cpp
Fixes some issues with the coincap.io fallback (#3743)
Fixed:
1. only run `getCoincapAssetHistory` if the previous call succeeded
2. try coincap even if yahoo fails
3. small style change to how USD conversion rates were handled
There's still two main issues that are a bit more tricky:
1. coincap.io has some pretty harsh rate limits, which leads to `invalid value` if the user presses the update currency too many times
2. USD conversion rate is required, if it's not updated the conversion rates fetched will be in USD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3759)
> Coincap fallback fixes

- src/optiondialog.cpp
- util/update-po-files.sh
Not sure it's worth merging, as many other GUI strings are still in the "old" language. In particular, the page titles in the options dialog, as it is still open when the changed message is shown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3855)
> fix(#3847): Don't mix languages in the "Apply" message of the options dialog

- CMakeLists.txt
- src/paths.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3981)
> fix(#3961): move themes and reports to subdirs

- src/aboutdialog.cpp
Fix https://github.com/moneymanagerex/moneymanagerex/issues/3796
Error:
undefined reference to 'mmHTMLBuilder::init(bool)'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4030)
> Fix: Compilation with "CMake 3.21"

- src/images_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4076)
> fix(#3980): graceful exit on missing themes

- src/mmchecking_list.cpp
Disable event handler before items state change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4108)
> fix(#4098): ctrl + a

- src/images_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4253)
> fix(#4223): navtree_images Loan Acc size fix

- src/splittransactionsdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4601)
> fix(#4591): define textctrl size

- src/transdialog.cpp
Maybe fixes #4648 but fixes manually entering "to amount" for sure. The logic had a typo and the "from amount" was set to the "to amount" after focusing out of the text box.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4657)
> fix(transdialog): Fix entering "to amount" for transfers

- src/accountdialog.cpp
- src/assetdialog.cpp
- src/assetspanel.cpp
- src/attachmentdialog.cpp
- src/attachmentdialog.h
- src/mmframe.cpp
- src/payeedialog.cpp
- src/stockdialog.cpp
- src/stocks_list.cpp
This reverts commit ad45abe9c03534af7768ea2c0073c5da01619306.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4850)
> Revert "fix(#3226): reference name used where available"

- src/mmcustomdata.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4940)
> fix(#4921): use standard currency ToString

- src/billsdepositsdialog.cpp
- src/transdialog.cpp
- src/transdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4964)
> fix(#4946): mmTextCtrl - revert some changes

- src/billsdepositsdialog.cpp
- src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4968)
> fix(#4946): Calculate precision not needed

- src/mmcheckingpanel.cpp
- src/reports/transactions.cpp
- src/reports/transactions.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4993)
> fix(#4987): bug fix

- .circleci/config.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5011)
> chore(circleci.yml): disable MacOS build

- src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5025)
> fix(#5019): split tooltip

- src/assetspanel.cpp
- src/billsdepositspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5055)
> fix(#5054): sort icon reversal

- src/categdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5063)
> fix(#5059): constrain width

- src/categdialog.cpp
#5056 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5064)
> fix(#5056):Correct sorting of child nodes

- src/reports/summarystocks.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5071)
> fix(#4087):Share precision in Stock Summary report

- src/model/Model_Stock.cpp
- src/model/Model_Stock.h
- src/model/Model_Translink.cpp
- src/reports/summarystocks.cpp
- src/reports/summarystocks.h
- src/sharetransactiondialog.cpp
- src/stockdialog.cpp
- src/stockdialog.h
- src/stocks_list.cpp
- src/stocks_list.h
- src/stockspanel.cpp
Fix #3892, #4969, and #5049.
Adds a new "Realized Gain/Loss" column to the stock list and renames the "Gain/Loss" as "Unrealized Gain/Loss" to better describe what the value represents. Realized Gain/Loss is calculated based on the difference between the sale transaction share price and the weighted average price of all currently owned shares at the time of the transaction (less any sales commission).
Various other corrections have been made:
- Adding/deleting the most recent price for a stock will update the CURRENTPRICE for that stock on all accounts. New transactions will also update the CURRENTPRICE if the transaction date is newer than the latest date in history.
- In stock list the "*Share Price" column now holds the weighted average cost per share for currently held shares. …
> fix(#3892):Stock fixes & enhancements

- src/model/Model_Stock.cpp
- src/model/Model_Stock.h
- src/model/Model_StockHistory.cpp
- src/model/Model_Translink.cpp
- src/reports/summary.cpp
- src/sharetransactiondialog.cpp
- src/stockdialog.cpp
- src/stockdialog.h
Fix for issues #1868 and #5058 where wrong number of shares is used to calculate the daily balance of an investment account.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5076)
> fix(#1868): numshares in daily balance calc

- src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5102)
> fix(#5101): Hide blank UDFC fields

- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5135)
> fix(#5122): secondary sort default is ID

- dockers/fedora.36/Dockerfile
This need not be downloaded separately
Not sure this needs an update of release notes. Can do so though.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5184)
> fmt is available in fedora repositories

- src/accountdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5192)
> Fix(#5191): Initialize account image vector

- src/currencydialog.cpp
- src/currencydialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5190)
> fix(#1158): disable fields if locale used

- src/mmframe.cpp
- src/model/Model_Billsdeposits.cpp
This is a fix (plus a small improvement) of the Recurring Transaction Check.
Currently, the check is performed for all recurring transactions, regardless of whether they will be applied.
This results in an incorrect calculation in case the sum of all the transactions, even the ones that would not be immediately applied, would bring the balance below the minimum balance.
In short:
- The check is now performed just before the transaction is applied.
- The message box shows some details to help the user decide
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Recurring Transaction Check Fix

- src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5287)
> fix(#2963): ignore color accelerators

- src/transdialog.cpp
Fixes the validation of a new transaction against the minimum balance and the credit limit for the target account.
- The check is performed only for withdrawals and transfers
- The reference account is specifically the source one; this fixes an issue when the transaction is created from the target account page (the balance was incorrectly the target account's).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5291)
> #5290 Fix new transaction data validation

- src/mmchecking_list.cpp
- src/mmframe.cpp
- src/option.cpp
Default to auto show/hide based on deleted transactions present, but allow user to suppress the node in the Nav Panel via View menu.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5300)
> fix(#5298): Default to autoshow "Deleted Transactions" node

- src/categdialog.cpp
- src/mmchecking_list.cpp
- src/mmframe.cpp
- src/model/Model_Category.cpp
- src/model/Model_Checking.cpp
- src/model/Model_Payee.cpp
- src/payeedialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5307)
> fix(#5296): Allow delete categories & payees used in deleted transactions

- src/mmhomepagepanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5317)
> fix(#5310): save asset widget state

- src/splittransactionsdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5332)
> fix(#5331): refresh improvment

- src/currencydialog.cpp
- src/images_list.cpp
- src/reports/cashflow.cpp
- src/reports/myusage.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5373)
> fix(#5372): clear MSVC compiler warnings

- src/reports/htmlbuilder.cpp
Adds report-table class to table tags generated by htmlbuilder. This allows report tables to be targeted by the theme master.css.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5380)
> fix(#4295): html class for report tables

- src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5399)
> fix(#5394): enable copy/paste in "all transactions"

- src/mmchecking_list.cpp
- src/mmchecking_list.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5555)
> fix(#5521): add LASTUPDATEDTIME to account view

- src/model/Model_Stock.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5569)
> fix(#5564): fix crash when all historical stock prices deleted

- src/filtertransdialog.cpp
- src/filtertransdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5605)
> fix(#5599): always allow subcategory filter on txn report

- src/dbwrapper.cpp
- src/dbwrapper.h
- src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5623)
> fix(#5550): allow debug on corrupt databases

- src/model/Model_Checking.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5634)
> fix(#5630): don't update timestmp if txn not found in DB

- src/model/Model_Currency.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5679)
> fix(#5643): remove default locale for curr string conversion

- src/model/Model_Currency.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5700)
> fix(#5204): fix default locale for non-US

- src/import_export/export.cpp
- src/import_export/qif_import_gui.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5708)
> fix(#5706): export split notes in QIF

- src/billsdepositsdialog.cpp
- src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5757)
> fix(#5668): don't include custom panel in saved size

- src/import_export/univcsvdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5794)
> fix(#5791): save & restore color settings

- src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5831)
> fix(#5830): halt event generation during combobox init

- src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5829)
> fix(#5828): disable paste foreign transactions

- src/reports/budgetcategorysummary.cpp
- src/reports/budgetingperf.cpp
- src/reports/categexp.cpp
Fix missing ';' after "&nbsp" in a few strings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5837)
> Fix HTML nbsp tags in output

- src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5839)
> fix(#5835): retain selection during autocomplete init

- src/import_export/univcsvdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5841)
> fix(#3148): clear payee patterns before reinit

- src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5856)
> fix(#5769): replace delimiters in saved category filter

- src/budgetentrydialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5899)
> fix(#5892): restrict categname display width

- src/maincurrencydialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5927)
> fix(#5920): parse value using base currency format

- src/maincurrencydialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5928)
> fix(#5920): use selected currency format for text box

- src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5960)
> fix(#5894): store Yahoo cookie & crumb in mmexini.db3

- src/mmframe.cpp
- src/mmframe.h
- src/model/Model.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5967)
> fix(#5964): clear Model caches on database shutdown

- src/db/DB_Table_Currencyformats_V1.h
- util/sql_tables.sql
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5972)
> fix(#5969): database submodule update for USD group separator

- src/import_export/univcsvdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6012)
> fix(#5790): save default preset for export

- 3rd/CMakeLists.txt
Fixes https://github.com/moneymanagerex/moneymanagerex/issues/5953
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6017)
> Enable flags for x86_64 only to improve aarch64 build compatibility

- src/stockdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6034)
> fix(#6030): use current date on save

- src/mmSimpleDialogs.cpp
- src/mmframe.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Budgetsplittransaction.cpp
- src/model/Model_Budgetsplittransaction.h
- src/model/Model_Splittransaction.cpp
- src/model/Model_Splittransaction.h
- src/tagdialog.cpp
- src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6095)
> fix(#5439): delete split taglinks when txn is deleted

- src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6105)
> fix(#6098): remove lock restriction for statement date filter

- src/mmframe.cpp
- src/relocatecategorydialog.h
- src/relocatepayeedialog.h
https://github.com/moneymanagerex/moneymanagerex/issues/5439#issuecomment-1636655697
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6109)
> Remove ` Dialog` from a dialog title

- src/import_export/univcsvdialog.cpp
- src/import_export/univcsvdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6124)
> fix(#6057): use std category delimiter ':' for CSV export

- src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6131)
> fix(#5439): Initialise caret color

- src/mmframe.cpp
- src/reports/cashflow.cpp
Hopefully this works.
An improvement would be to have singular `%1$s (%2$i month)` and plural `%1$s (%2$i months)` working.
@n-stein are you able to advise the code to do the improvement?
Thank you
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6165)
> fix (#5328): months

- src/payeedialog.cpp
- src/payeedialog.h
Hi,
this is my first ever pull request (so sorry if this isn't the right way)
I have modified _payeedialog.cpp_ to allow select multiple items and delete all in once.
I tested it a little on my PC and it seems workinng right.
Maybe Yuo fidn a better way to implement this (so take this like a suggested feature)
for this issue:
https://github.com/moneymanagerex/moneymanagerex/issues/6181
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6184)
> adding multiple payees delete at once

- src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6209)
> fix(#6040): workaround for cURL UA block

- src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6220)
> fix(#6212): fix category filter regex check

- src/billsdepositsdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6263)
> fix(#6200): select amount fields on focus

- src/model/Model_Usage.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6286)
> use model_usage.m_start as session_id

- src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6292)
> Add session type alongside desktop environment in about dialog

- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6306)
> fix(#6305): Revert to native DatePicker on MacOS

- src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6309)
> fix(#6308): sort share accounts in nav panel by STOCKNAME

- src/mmframe.cpp
fix　TRUE was specified even though the argument type was bool.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6325)
> fix　TRUE was specified even though the argument type was bool.

- org.moneymanagerex.MMEX.yml
wxWidgets in the MMEX builds on Flathub has already been updated:
https://github.com/flathub/org.moneymanagerex.MMEX/pull/14
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6328)
> Update wxWidgets in flatpak manifest to v3.2.4

- BUILD.md
Corrected the cmake commands for the Windows build to use updated arch syntax. Corrected the curl build instruction to use native SChannel SSL library.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6348)
> update steps for Windows build

- src/model/Model_Billsdeposits.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6413)
> fix(#6390): format order

- CMakeLists.txt
Reverts moneymanagerex/moneymanagerex#6415
@joshua-stone  This fails to build. https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/1180/workflows/fb401f1a-ac0f-4b46-8acf-195fcdd7a31a/jobs/1173
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6418)
> Revert "Add validation to the metainfo file generated at build time"

- CMakeLists.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6417)
> Add --no-net to metainfo validation

- CMakeLists.txt
- resources/dist/linux/share/metainfo/org.moneymanagerex.MMEX.metainfo.xml.in
It would appear that the metainfo file needs additional fields to work with the newest appstream spec:
https://gitlab.gnome.org/GNOME/loupe/-/blob/bee10be168639a082576e8a6eea34d40a364c680/data/org.gnome.Loupe.metainfo.xml.in.in#L6
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6421)
> Update developer ID to be compliant with appstream 1.0

- po/common.po
- src/optionsettingsgeneral.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6436)
> fix(#6404): translate language list in options

- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/reports/htmlbuilder.h
- src/reports/transactions.cpp
Transaction Report has now option to show a chart.
If "grouping" is enabled, it considers the grouping item total, otherwise it considers the single transaction.
Three new "Group By" have been added: day, month, year:
Chart types are all ones supported by MMEX graphing library:
Result:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6440)
> feat(#5685): add charts to Transaction Report

- src/import_export/univcsvdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6454)
> fix(#6452): remove newline at end of notes

- src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6477)
> fix(#6476): protect filter parsing

- src/mmframe.cpp
https://github.com/moneymanagerex/moneymanagerex/issues/6481
@whalley @n-stein can you please check that this patch works? If not, please help.
Thank you
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6482)
> fix(#6481): `MMB Files (*.mmb)`: 1. Add a space ` `; and, 2. allow translation

- src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6483)
> fix(#6480): prevent value clearing on combobox autocomplete init

- src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6484)
>  fix(#5512): store last unsaved transaction filter 

- src/mmTextCtrl.cpp
- src/validators.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6485)
> fix(#6474): use decimal of defined locale

- src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6494)
> fix(#6493): apply conversion factor for CHF base currency

- src/optionsettingsattachment.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6540)
> fix(#6155): fix browse button width

- src/splittransactionsdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6552)
> fix(#6548): split notes dialog enable vertical resize

- src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6564)
> fix(#6553): translate db debug dialog labels

- src/accountdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6578)
> fix(#6572): linux fix notebook width in account dialog

- src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6586)
> fix(#6583): use non-reserved ids in freq notes menu

- src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6587)
> fix(#6584): fix spin button height in mmDatePickerCtrl

- src/mmhomepage.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6612)
> fix(#6608): align "Other Assets" current value on dashboard

- src/attachmentdialog.cpp
- src/categdialog.cpp
- src/dbupgrade.cpp
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
- src/payeedialog.cpp
- src/reports/bugreport.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6615)
> fix(#6614): fix translation of FromUTF8 strings

- src/mmTextCtrl.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6619)
> fix(#6618): default '.' for undefined decimal

- src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6661)
> fix(#6658): save txn filter dialog size in report mode only

- src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6655)
> fix(#6503): reset column view only after options dialog

- docs/css/manual.css
* Use free font which is available on Linux so that an "i" looks different to an "l".
* Keep the fallback to the generic-family font name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6674)
> Free font so "i" and "l" are distinguishable on Linux too

- src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6683)
> fix(#6503): fix crash when not on a checking panel

- resources/dist/linux/share/metainfo/org.moneymanagerex.MMEX.metainfo.xml.in
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6696)
> fix(#6693): remove developer_name tag deprecated by appstream 1.0.3

- src/dbwrapper.cpp
- src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6532)
> switch default cipher to SQLCipher4(AES256) from AES128

- src/import_export/qif_import_gui.cpp
- src/import_export/univcsvdialog.cpp
- src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6762)
https://github.com/moneymanagerex/moneymanagerex/issues/6703#issuecomment-2119107775
fixes "1. Should the decimal point . and 0 be interchanged?"
> `&Browse...` and swap `0` and `.` buttons on calculator

- src/reports/htmlbuilder.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6782)
> Fix #6781 by removing ".UTF-8" suffix from locale for apexchart

- BUILD.md
I could compile MMEX on macOS from master branch using wxWidgets v3.2.5, but there were compilation errors when I tried with wxWidgets v3.1.5, as instructed in BUILD.md. Apparently MMEX has been updated to use wxWidgets v3.2.5 (as seen in commit messages), but BUILD.md was not updated.
There is one more reference to wxWidgets v3.1.5 in BUILD.md, in the instructions for Linux. Most probably this also needs to be updated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6825)
> fix wxWidgets version for macOS in BUILD.md

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/billsdepositspanel.cpp
- src/billsdepositspanel.h
- src/mmframe.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Billsdeposits.h
Change billsdeposits model as proposed in #6827
- Change `None` to `Once` and `REPEAT_NONE` to `REPEAT_ONCE`.
- An empty `Period` in the edit form for type `REPEAT_IN_*` or `REPEAT_EVERY_*`, means `1`.
- After the first execution, `REPEAT_IN_*` entries are converted to `REPEAT_ONCE`.
- All entries created by the edit form (with new/edit/duplicate) are active.
The old inactive entries (of type `REPEAT_IN_*`, `REPEAT_EVERY_*` and with `NUMOCCURRENCES == -1`) are handled as follows:
- They are not executed automatically.
- If they are executed manually (by pressing the `Enter` button), they are converted to `REPEAT_ONCE`, therefore they are removed after execution. (In MMEX 1.8.0 they can be executed manually, as described in #6827, probably due to a bug.)
- If they are edited, they are …
> fix(#6827), part 2: inactive billsdeposits; None -> Once

- src/billsdepositsdialog.cpp
- src/billsdepositspanel.cpp
- src/mmhomepage.cpp
- src/reports/cashflow.cpp
The auto execution mode of scheduled transactions is multiplexed into the `REPEATS` field. The choices are defined in enum `Model_Billsdeposits::REPEAT_AUTO`.
Changes:
- Multiplex/demultiplex the `REPEATS` field into/from auto execution mode and repeat type, using `BD_REPEATS_MULTIPLEX_BASE`, but without any other assumption about the encoding of auto execution mode.
- Use the symbols in `Model_Billsdeposits::REPEAT_AUTO` instead of raw values for the encoding of auto execution mode.
- Use the symbols in `Model_Billsdeposits::REPEAT_TYPE` instead of raw values for repeat type.
- Ignore inactive scheduled transactions (of type `REPEAT_IN_*`, `REPEAT_EVERY_*` with `NUMOCCURRENCES == -1`) in `src/mmhomepage.cpp` and `src/reports/cashflow.cpp`.
- - -
This change is [<img …
> fix(#6827): encapsulate auto execute values

- src/billsdepositsdialog.cpp
- src/mmframe.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Billsdeposits.h
- src/transdialog.cpp
`Model_Account::balance(a)`, which calculates the balance of account `a`, has the following properties:
- Transactions with `STATUS == VOID` or with non-empty `DELETEDTIME` are ignored.
- `TRANSAMOUNT` is added to the balance of `ACCOUNTID` if `TRANSCODE == DEPOSIT`.
- `TRANSAMOUNT` is subtracted from the balance of `ACCOUNTID` if `TRANSCODE == WITHDRAWAL` or `TRANSCODE == TRANSFER`.
- `TOTRANSAMOUNT` is added to the balance of `TOACCOUNTID` if `TRANSCODE == TRANSFER`.
`htmlWidgetAccounts::get_account_stats()`, which calculates and stores the sum of transactions per account, is consistent with `Model_Account::balance()`.
`mmTransDialog::ValidateData()`, which checks the limits of new or duplicated transactions, is inconsistent with `Model_Account::balance()`:
- It aborts transactions with …
> fix(#6827): Model_Billsdeposits::AllowTransaction

- src/billsdepositsdialog.cpp
`mmBDDialog::OnOk()` calls `Model_Billsdeposits::.AllowTransaction()` in order to check if the execution of a scheduled transaction would exceed an account limit.
- The check is performed before `m_bill_data.TRANSAMOUNT` is updated. If the user changed the amount in the dialog form and then immediately pressed OK (without changing focus in between), the old amount in the dialog form is checked.
- This check makes sense only when the scheduled transaction is executed, i.e., only if the dialog form was created by the Enter button. For all other actions (New, Edit, Duplicate), a scheduled transaction is just created/updated in the `BILLSDEPOSITS_V1` table, but it is not executed, therefore no check is needed. Actually a premature check is misleading, e.g., the scheduled transaction may …
> fix(#6827): mmBDDialog::OnOk

- src/billsdepositsdialog.cpp
- src/dbcheck.cpp
- src/mmchecking_list.cpp
- src/mmhomepage.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Billsdeposits.h
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
- src/reports/cashflow.cpp
- src/transactionsupdatedialog.cpp
- src/transdialog.cpp
The following definitions in `Model_Billsdeposits` are identical to the corresponding definitions in `Model_Checking`.
- enum `TYPE`
- vector `TYPE_CHOICES`
- `all_type()`
- `type(const wxString& r)`
- enum `STATUS_ENUM`
- vector `STATUS_ENUM_CHOICES` (rename to `STATUS_CHOICES`)
- `all_status()`
- `status(const wxString& r)`
- `toShortStatus(const wxString& fullStatus)`
The references to all `Model_Billsdeposits` definitions above have been replaced with references to `Model_Checking`.
- in enum `Model_Billsdeposits::REPEAT_TYPE`: `REPEAT_INACTIVE`
- in `Model_Billsdeposits`: typedef `AccountBalance` (was commented out)
- in `Model_Checking`: `toShortStatus()` -> `status_key()`
- `Model_Checking::all_status_key()`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> fix(#6827): refactoring model checking, bills deposits and cleanup

- src/billsdepositsdialog.cpp
- src/dbcheck.cpp
- src/filtertransdialog.cpp
- src/import_export/export.cpp
- src/import_export/qif_export.cpp
- src/import_export/qif_import_gui.cpp
- src/import_export/univcsvdialog.cpp
- src/import_export/univcsvdialog.h
- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
- src/mmhomepage.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Billsdeposits.h
- src/model/Model_Category.cpp
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
- src/model/Model_Translink.cpp
- src/optionsettingsmisc.cpp
- src/reports/cashflow.cpp
- src/reports/forecast.cpp
- src/reports/incexpenses.cpp
- src/reports/payee.cpp
- src/reports/transactions.cpp
- src/sharetransactiondialog.cpp
- src/transactionsupdatedialog.cpp
- src/transdialog.cpp
- src/transdialog.h
- src/usertransactionpanel.cpp
- src/webapp.cpp
This PR improves a few design weaknesses in `TYPE` and `STATUS` choices in `Model_Checking`. If accepted, other PRs will implement similar improvements in other model choices.
- The order of the entries in vector `TYPE_CHOICES` and `STATUS_CHOICES` is not checked. If the order is wrong (by mistake) and this becomes unnoticed, the database may be corrupted, since the choice values presented by the gui are different than the choice values processed by the program.
- The cases in enum `TYPE` and `STATUS_ENUM` pollute the `Model_Checking` class namespace, especially if they have a common short name like `VOID`. Since they are not prefixed, they are sometimes confusing when used outside of `Model_Checking`.
- The single-letter keys of `STATUS` appear as raw values in several places, i.e., …
> refactor choices in Model_Checking

- README.TXT
- resources/dist/linux/share/metainfo/org.moneymanagerex.MMEX.metainfo.xml.in
1. Alphabetical by locale code
2. Add magyar
Can README.TXT be deleted as information is now contained in org.moneymanagerex.MMEX.metainfo.xml.in?
1. Attempt to correctly apply the localize <description> tag to show correctly at https://flathub.org/hu/apps/org.moneymanagerex.MMEX
2. Add <description> to other locales to attempt to show correctly at:
* https://flathub.org/de/apps/org.moneymanagerex.MMEX
* https://flathub.org/fr/apps/org.moneymanagerex.MMEX
* https://flathub.org/ru/apps/org.moneymanagerex.MMEX
* https://flathub.org/ta/apps/org.moneymanagerex.MMEX
* …
> Attempt to correctly display localized `<description>` tags at Flathub

- .circleci/config.yml
- org.moneymanagerex.MMEX.yml
There's a new version of the Gnome runtime available for MMEX:
```
$ flatpak remote-info flathub org.gnome.Platform//47
GNOME Application Platform version 47 - Shared libraries used by GNOME
applications
ID: org.gnome.Platform
Ref: runtime/org.gnome.Platform/x86_64/47
Arch: x86_64
Branch: 47
License: GPL-2.0+
Collection: org.flathub.Stable
Download: 383.8 MB
Installed: 1.0 GB
Commit: 5a76da0daccad115565c2bf2279c85e487203af01ef3bde34bb149fe048c54ab
Subject: Export org.gnome.Platform
Date: 2024-09-18 04:26:21 +0000
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6891)
> Update Gnome SDK to latest version in flatpak manifest

- .circleci/config.yml
- org.moneymanagerex.MMEX.yml
A continuation from https://github.com/moneymanagerex/moneymanagerex/pull/6891 where merging failed due to the container image not being updated. The newest runtime should be available now:
```
$ skopeo list-tags docker://bilelmoussaoui/flatpak-github-actions
{
"Repository": "docker.io/bilelmoussaoui/flatpak-github-actions",
"Tags": [
"elementary-juno",
"freedesktop-20.08",
"freedesktop-21.08",
"freedesktop-22.08",
"freedesktop-23.08",
"freedesktop-24.08",
"gnome-3.38",
"gnome-40",
"gnome-41",
"gnome-42",
"gnome-43",
"gnome-44",
"gnome-45",
"gnome-46",
"gnome-47",
"gnome-nightly",
"kde-5.15",
"kde-5.15-21.08",
"kde-5.15-22.08",
"kde-5.15-23.08",
"kde-6.2",
"kde-6.3",
"kde-6.4",
"kde-6.5",
"kde-6.6",
"kde-6.7",
"latest"
]
}
```
Please do not forget to update the mmex.pot file and write …
> Update flatpak runtime to Gnome 47

- src/reports/reportbase.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6911)
> fix(#6897): use translated report title in acct selection dialog

- src/mmpanelbase.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6918)
> fix(#6847): fix column width after move

- src/payeedialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6934)
> fix(#6863): disallow blank payee name in edit dialog

- po/CMakeLists.txt
- po/common.po
- src/mmex.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6941)
> fix(#6938): fix common UI Language List translation catalog location

- src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6946)
> fix(#6945): correct encoding of "LAST_USED" transaction filter

- src/reports/budgetingperf.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6960)
> fix(#6957): reset total for each category

- src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6982)
> fix(#6975): save/restore column order by account type

- src/model/Model_Infotable.cpp
- src/model/Model_Infotable.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7010)
> fix(#7009): set infotable key with int64 value

- .github/workflows/crowdin-download.yml
- .github/workflows/crowdin-upload.yml
- .github/workflows/update-po-template.yml
- crowdin.yml
- util/update-po-files.sh
Three new GitHub Actions to automate Crowdin integration:
1.    An "Update PO Template" action. On every pull request merged to master the po/mmex.pot file is regenerated. If there are changes, a new PR is opened with the updated po/mmex.pot.
2.    A "Crowdin Upload" action. Whenever a pull request that contains po/mmex.pot is merged to master, it uploads the new po/mmex.pot source to Crowdin.
3.    A "Crowdin Download" action. When the action is triggered, it downloads the translations from Crowdin to the po directory and opens a PR with the new translations. It runs automatically at midnight every Friday, but can be triggered manually at any time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> fix(#6990): crowdin sync workflows

- src/import_export/parsers.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7035)
> fix(#7030): import CSV with in-field newline chars

- src/import_export/parsers.cpp
- src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7038)
> fix(#7030): fix regex for double quote at start of field

- src/splittransactionsdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7040)
> fix(#6956): round split total to curr precision before validation

- src/mmcheckingpanel.cpp
MMEX version:
Operating system:
The application crashes when "View Since Statement Date" is selected in the filter of "Deleted Transactions". This option does not make sense for deleted transactions and should not be available.
- Disable `FILTER_ID_STATEMENTDATE` if `isTrash_`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7062)
> fix(#7059): filter by statementdate in mmCheckingPanel

- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
- When a new `mmFilterTransactionsDialog` is created, its `accountID` is set to `m_account_id` (instead of `m_checking_id`).
`mmFilterTransactionsDialog` shows an account filter when its `accountID` argument is equal to -1. `m_account_id` in `mmCheckingPanel` is equal to -1 for all multi-account checking panels (All Transactions, Deleted Transactions, account group).
In `mmFilterTransactionsDialog` for an account group, the list of available accounts is not limited, since the account group itself is an account filter. This feature allows for a search in which any other account appears in a transfer transaction, together with an account from the account group.
In MMEX 1.8.1, `mmFilterTransactionsDialog` for Deleted Transactions does not show an account filter.
- - -
This change is [<img …
> new(#7059), part 4: refine mmCheckingPanel

- src/fusedtransaction.h
- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmcheckingpanel.cpp
- src/model/Model_Account.cpp
- src/model/Model_Account.h
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
- src/reports/cashflow.cpp
- src/reports/summary.cpp
This PR adds a sequence number in transaction panels.
The transaction ID used to be assigned by SQLite and it was essentially a sequence number, indicating the order of creation. With the introduction of SUID (see #6964), the transaction ID is a long number and its appearance in transaction panels becomes less convenient.
The ID column in transaction panels is useful for sorting (by order of creation), although the exact value of a transaction ID is essentially opaque (i.e., of little interest to the user).
This PR adds one more column in transaction panels, containing a sequence number (SN) for each transaction, which is assigned sequentially (starting with 1) when a transactions list is generated. The order of SN is equivalent to the order of Date/ID, i.e., transactions are sorted by …
> new: add sequence number in transactions panel

- src/fusedtransaction.h
- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmcheckingpanel.cpp
- src/model/Model_Account.cpp
- src/model/Model_Account.h
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
- src/reports/cashflow.cpp
- src/reports/summary.cpp
- src/reports/transactions.cpp
This PR depends on (includes) #7080.
- Refactor and rename `UDFC0*_Type` -> `UDFC_type[5]`, `UDFC0*` -> `UDFC_content[5]`, `UDFC0*_val` -> `UDFC_value[5]`.
- Refine `filterTable()`: add custom fields in scheduled transactions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7081)
> new(#6860), part 7: add custom fields in scheduled transactions

- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmcheckingpanel.cpp
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
- src/reports/transactions.cpp
This PR depends on (includes) #7081.
- Refine `updateExtraTransactionData()`: add `notesStr` for scheduled transactions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7084)
> new(#6860), part 8: add notes for scheduled transactions

- src/mmframe.cpp
The order of items in Navigator is:
- Dashboard
- All Transactions
- ... account groups (Favorites and account types)
- Scheduled Transactions
- Deleted Transactions
- Budget Planner
- ... reports
- Help
Scheduled Transactions are used quite often. This PR moves them closer to the top (after All Transactions), so it is a little easier/faster to find them.
Deleted Transactions are rarely used. This PR moves them at the bottom (before Help).
The proposed order is:
- Dashboard
- All Transactions
- Scheduled Transactions
- ... account groups (Favorites and account types)
- Budget Planner
- ... reports
- Deleted Transactions
- Help
- Move "Scheduled Transactions" after "All Transactions"
- Move "Deleted Transactions" before "Help".
- - -
This change is [<img …
> refine order of items in navtree

- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
The keyword SN for Sequence Number introduced in #7080, may be confusing or cryptic to users in the beginning (see also the discussion in #6964).
This PR shows the following tip in `m_info_panel` (bottom area of transaction panels), when SN is selected as the primary sorting column: "SN (Sequence Number) has the same order as Date/ID."
Note: A tooltip on the SN header would be more suitable, however wxWidgets does not support it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7095)
> add tip for SN in transactions panel

- src/mmchecking_list.cpp
- src/mmpanelbase.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7100)
> fix(#7099): handle missing column enums in sort & ordering

- src/constants.cpp
- src/constants.h
- src/filtertransdialog.cpp
- src/mmSimpleDialogs.cpp
- src/reports/mmDateRange.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7115)
> fix(#6924): restrict date controls to DATE_MAX

- src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7116)
> fix(#7109): revert sort column change

- src/assetspanel.cpp
- src/attachmentdialog.cpp
- src/billsdepositspanel.cpp
- src/categdialog.cpp
- src/dbupgrade.cpp
- src/defs.h
- src/general_report_manager.cpp
- src/images_list.cpp
- src/import_export/qif_export.cpp
- src/import_export/qif_import_gui.cpp
- src/import_export/univcsvdialog.cpp
- src/mmchecking_list.cpp
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
- src/mmreportspanel.cpp
- src/payeedialog.cpp
- src/reports/bugreport.h
- src/stocks_list.cpp
- src/stockspanel.cpp
- src/wizard_newaccount.cpp
- util/update-po-files.sh
A small refactor which adds a macro to simplify translation of strings containing unicode characters
`wxGetTranslation(wxString::FromUTF8(wxTRANSLATE(unicode_string)))` can now be written `_u(unicode_string)`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7121)
> tidy: unicode translation macro

- src/mmSimpleDialogs.cpp
- src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7132)
> fix(#7130): allow '^' in stock symbols for online quotes

- src/assetspanel.cpp
- src/billsdepositspanel.cpp
- src/budgetingpanel.cpp
- src/filtertransdialog.cpp
- src/import_export/export.cpp
- src/import_export/qif_import_gui.cpp
- src/import_export/univcsvdialog.cpp
- src/maincurrencydialog.cpp
- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmframe.cpp
- src/model/Model_Account.cpp
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
- src/optionsettingsgeneral.cpp
- src/reports/htmlbuilder.cpp
- src/reports/transactions.cpp
- src/stockdialog.cpp
- src/stocks_list.cpp
- src/stockspanel.cpp
- src/transdialog.cpp
- src/util.cpp
- src/util.h
- src/webappdialog.cpp
This PR fixes the sorting by Date and Time in transaction panels.
- Rename and fix `mmGetDateForDisplay` -> `mmGetDateTimeForDisplay`.
- Match date pattern at the beginning of the string.
- Fix double translation of `mon` and `weekday`.
- Reset cache when it becomes too big (2000 entries).
- Add `mmGetDateForDisplay` (this is a new function).
- Copy from `mmGetDateTimeForDisplay`.
- Keep only the date part in the input ISO string.
- Do not format time.
- Add `SorterByTRANSDATE_DATE`.
- Rename and fix `SorterByTRANSTIME` -> `SorterByTRANSDATE_TIME`.
- Fix `allByDateId()`.
- Fix `transactionsByDateId()`.
- Refactor `SortTransactions()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> fix(#7109, #7110): Date and Time in transaction panels

- src/assetdialog.cpp
- src/assetdialog.h
- src/option.cpp
- src/option.h
- src/optionsettingsmisc.cpp
- src/optionsettingsmisc.h
This PR adds a choice for compounding period in asset dialog.
The asset value is appreciated/depreciated if `ASSETS_V1.VALUECHANGE` is "Appreciates" or "Depreciates", resp., using the "compounding interest formula" with annual rate equal to `ASSETS_V1.VALUECHANGERATE` and with daily compounding.
Although the rate is always stored into the database with daily compounding, the asset dialog shows the equivalent rate for the user's preferable compounding period.
- Add `ASSET_COMPOUNDING` of type string and values "Day", "Week", "Month", "Year".
- In Settings -> Other, add "Asset Compounding Period", connected to Infotable `ASSET_COMPOUNDING`.
- Add enum `COMPOUNDING_ID`.
- Add `COMPOUNDING_NAME`, `COMPOUNDING_N`.
- Add `AssetCompounding()`.
- Refine `LoadOptions()`.
- Refine `Create()`, …
> new(#7122): add compounding period in asset dialog

- src/assetspanel.cpp
- src/billsdepositspanel.cpp
- src/budgetingpanel.cpp
- src/filtertransdialog.cpp
- src/fusedtransaction.h
- src/import_export/export.cpp
- src/import_export/qif_import_gui.cpp
- src/import_export/univcsvdialog.cpp
- src/maincurrencydialog.cpp
- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
- src/model/Model_Account.cpp
- src/model/Model_Account.h
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
- src/optionsettingsgeneral.cpp
- src/reports/cashflow.cpp
- src/reports/htmlbuilder.cpp
- src/reports/summary.cpp
- src/reports/transactions.cpp
- src/stockdialog.cpp
- src/stocks_list.cpp
- src/stockspanel.cpp
- src/transdialog.cpp
- src/util.cpp
- src/util.h
- src/webappdialog.cpp
This PR depends on #7135.
- In transaction panels, scheduled executions have empty SN and ID, which may be confusing when sorting by these columns.
- SN has the same order as Date/ID, where Date is the date part (first 10 characters) in TRANSDATE. If Time is enabled, the order of SN is not identical to chronological order.
- Assign an SN also to scheduled executions.
- To distinguish scheduled executions from normal transactions, prepend a marker `*` in `displaySN`.
- Set the `displayID` of scheduled executions to the `BDID` of the corresponding scheduled transaction, and prepend a marker `*`.
- Refine `SorterByFUSEDTRANSSN`.
- Refine `SorterByFUSEDTRANSID`.
- Rename `allByDateId()` -> `allByDateTimeId()` and sort by Date/Time/ID if Time is enabled.
- Rename `transactionsByDateId()` -> …
> refine sequence number in transactions panel

- src/mmchecking_list.cpp
- src/optiondialog.cpp
- src/reports/myusage.cpp
- src/stockspanel.cpp
- src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7205)
> fix(#7204): correct usage of underscore translation macro

- src/mmSimpleDialogs.cpp
- src/splittransactionsdialog.cpp
- src/splittransactionsdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7219)
> fix(#7210): generate and process new tag events in split dialog

- src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7221)
> fix(#7220): parse filter json tag id as Int64

- src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7222)
> fix(#6949): prevent translation of menu hot keys

- src/assetspanel.cpp
- src/billsdepositspanel.cpp
- src/daterange2.cpp
- src/daterange2.h
- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
- src/mmframe.cpp
- src/mmhomepagepanel.cpp
- src/mmpanelbase.cpp
- src/mmpanelbase.h
- src/model/Model_Infotable.cpp
- src/model/Model_Infotable.h
- src/model/Model_Setting.cpp
- src/model/Model_Setting.h
- src/option.cpp
- src/primitive.h
- src/stocks_list.cpp
- src/util.cpp
- src/util.h
- Deprecate Infotable `CHECK_FILTER_ID_*`.
- Add Infotable `CHECK_FILTER_*` (JSON string), with fields:
- FILTER (string) is one of: Date, Advanced
- DATE (string) is a date range spec (label; name)
- SCHEDULED (bool)
- Add `dateISOStart()`, `dateISOEnd()`.
- Add `JSON_GetStringValue()`, `JSON_GetBoolValue()`.
- Add `Spec::hasPeriodS()`, `Spec::getLabelName()`.
- Add `getLabel()`, `getName()`, `getLabelName()`, `checking_start_str()`, `checking_end_str()`, `checking_tooltip()`.
- Add `setJdoc()`, `getJdoc()`.
- Remove `setViewTransactions()`, `getViewTransactions()`. Deprecate unused `VIEWTRANSACTIONS`.
- Add `GetColumnOrder()`.
- Rename `mmGetJsonSetings()` -> `mmGetJsonSettings().`
- Reorder class members (consistent order in .h and .cpp).
- Rename several variable and functions (e.g., …
> new(#7150), part 5: refine mmCheckingPanel, TransactionListCtrl

- src/assetspanel.cpp
- src/assetspanel.h
- src/billsdepositspanel.cpp
- src/billsdepositspanel.h
- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmcheckingpanel.cpp
- src/mmpanelbase.cpp
- src/mmpanelbase.h
- src/stocks_list.cpp
- src/stocks_list.h
Fix the appearance of sort icon (up/down arrow) after operations on columns.
- Add `c_icon_col_nr` (stores the column number with sort icon).
- Rename `m_col_nr` -> `m_sel_col_nr`.
- Add virtual `getSortIcon()`. Add implementation in derived classes.
- Add `updateSortIcon()`.
- Remove `TransactionListCtrl::setColumnImage()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7267)
> ref(#7200), part 3: fix sort icon in column headers

- src/assetspanel.cpp
- src/billsdepositspanel.cpp
- src/budgetingpanel.cpp
- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmpanelbase.cpp
- src/mmpanelbase.h
- src/model/Model_Setting.cpp
- src/model/Model_Setting.h
- src/stocks_list.cpp
- src/util.cpp
- src/util.h
This PR depends on #7287.
Deprecated in Setting: `*_COLUMNORDER`, `*_WIDTH`, `*_SORT_COL*`, `*_ASC*`.
Added Setting `LIST_<name>` (JSON string), with fields:
- `version` (int): equal to 2 (version 1 has been used for testing)
- `col_id_nr` (array of int `col_id`): map column number -> column id
- `col_width_id` (array of int `width`): map column id -> column width
- `col_hidden_id` (array of int `col_id`): set of hidden column ids
- `sort_col_id` (array of int `col_id`): primary/secondary sorting column id
- `sort_asc` (array of bool `asc`): primary/secondary sorting direction
Notes:
- `col_id_nr` is omitted if columns cannot be moved.
- `sort_col_id` may have one or two elements (primary, secondary); it is omitted if the list cannot be sorted.
- `sort_asc` has the same size as …
> ref(#7200), part 6: refine user preferences

- src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7297)
> fix(#7271): fix TransactionListCtrl::setSelectedId()

- src/billsdepositsdialog.cpp
- src/mmcheckingpanel.cpp
- src/sharetransactiondialog.cpp
- src/splittransactionsdialog.cpp
- src/splittransactionsdialog.h
- src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7348)
> Stock: simplify mmSplitTransactionDialog via totalAmount_ & transType_ removal

- src/assetdialog.cpp
- src/assetspanel.cpp
- src/model/Model_Account.cpp
- src/model/Model_Asset.cpp
- src/model/Model_Asset.h
- src/reports/summary.cpp
```
std::pair<double /*initial*/, double /*market*/> balance;
if (amount < 0) // sale, try your best to keep the principal
balance.first += std::min(balance.second + amount, 0.0);
else
balance.first += amount;
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7362)
> Asset: unify initial val and market val calculation

- src/mmframe.cpp
**Purpose:** Modernise appearance of toolbar.
When snapped to top, toolbar will automatically span width of application.
Rearranged icons, and separated utility icons (full screen, settings, help, news, about) to the right-hand side.
Toolbar can still be undocked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7382)
> Tidy toolbar icon arrangements and snap to width of application

- src/mmreportspanel.cpp
Recent change to int64 for SUID caused built-in category reports not to show any transactions for recently categories that had been created with a SUID-type identifier.
This is because the catID/subCatID/payeeID variables were initialised as int and not int64, causing an overflow.
Fixes #7392
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7401)
> Fix built-in category reports not showing newly created categories

- resources/home_page.htt
- src/mmhomepagepanel.cpp
Add currency formatting to the 'amount' on Apexcharts label for Income vs. Expense chart on MEMX dashboard homepage.
Labels are sensitive to the base currency configured in MMEX, and adjust accordingly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7404)
> Update Income/Expense chart on homepage to include currency formatting

- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
As a heavy Excel user, I can see how this one could be handy.
If a single transaction is selected, the value of the label (transaction memo) is copied to clipboard.
If multiple transactions are selected, the summed value of the selected transactions is copied to clipboard.
I tried to pushback the transaction sum value via SetHelpText to m_info_panel, however this function this doesn't appear to be supported by wxStaticText.
Last PR for a short while before my wife gets too upset :)
Closes #7334
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7405)
> Click transaction sum to copy to clipboard

- src/model/Model_Account.cpp
to fix #7406 
- #7406
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7407)
> Investment: use DB_Table_ASSETS_V1::ASSETTYPE instead of Model_Asset one

- src/mmex.cpp
https://docs.wxwidgets.org/3.2/overview_container.html#overview_container_std
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7442)
> Infra: use wxList::compatibility_iterator for wxWidgets STL Build

- src/mmex.cpp
Fixes #7445
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7487)
> fix(#7445): call mmGUIFrame destructor in app exit if not already done

- src/util.cpp
With old User-Agent both the generation of the crumb and refresh API fails with "Too Many Requests". Which when used as a crumb is an invalid URL, because it contains spaces and it is not a proper JSON, therefore the two error messages experienced in the bug report.
```
curl 'https://query1.finance.yahoo.com/v7/finance/quote?symbols=AAPL&fields=regularMarketPrice,currency,shortName&crumb=ptm/idCTN/J' -b 'A1S=d=AQABBADoKGgCEJpF1HOCWmtYWSSXt5_7j4wFEgABCAE3KmhaaN2iPTIBAiAAAAcIAOgoaJ_7j4w&S=AQAAAus3lu3i0-TjHCWbxi0Dngc; A1=d=AQABBADoKGgCEJpF1HOCWmtYWSSXt5_7j4wFEgABCAE3KmhaaN2iPTIBAiAAAAcIAOgoaJ_7j4w&S=AQAAAus3lu3i0-TjHCWbxi0Dngc; A3=d=AQABBADoKGgCEJpF1HOCWmtYWSSXt5_7j4wFEgABCAE3KmhaaN2iPTIBAiAAAAcIAOgoaJ_7j4w&S=AQAAAus3lu3i0-TjHCWbxi0Dngc' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; …
```
> fix: Yahoo finance api not working anymore #7482

- contrib.txt
- docs/de_DE/index.html
- docs/en_US/index.html
- po/de_DE.po
- po/mmex.pot
- src/filtertransdialog.cpp
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
- src/mmreportspanel.cpp
- src/mmreportspanel.h
- src/option.cpp
- src/option.h
- src/optionsettingsmisc.cpp
- src/optionsettingsmisc.h
- src/reports/reportbase.cpp
- src/reports/reportbase.h
Like discussed the change for #7577:
- remove the old date range handling
- add a switch to store the the date range either individually per account/report or globally
In addition three more related changes:
- I noticed that the report id is always set to -1 during filter storage, so there was no individual filter storage. 
- User manual update for the settings description. Is not complete but reflects the current structure
- German translation of the user manual update
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7655)
> Feature#7577 unified data update 2

- src/import_export/qif_import_gui.cpp
- src/import_export/qif_import_gui.h
This is my first attempt to contribute to this project. C++ is not my main language so I'm very open to feedback.
I tend to import QIF/CSV files from my bank a few times per month and I can't really use the date filtering to avoid duplicates because sometimes my bank would take a few days to include some transactions. Pretty much the same issue as described in https://github.com/moneymanagerex/moneymanagerex/issues/6771.
So I decided to try and add a few opt-in filtering features. Default behavior is exactly the same as before.
The options are:
* Duplicates:
- By transaction number
- By amount and exact date
- By amount and nearby date
* Action:
- Skip
- Flag as duplicate
The options are pretty much self-explanatory but, just in case, the "By amount and nearby date" option will try to …
> Feature: allow skipping or flagging duplicate transactions (QIF imports)

- src/categdialog.cpp
- src/categdialog.h
- src/images_list.cpp
- src/images_list.h
- src/import_export/ofx_import_gui.cpp
- src/import_export/ofx_import_gui.h
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
- src/mmreportspanel.cpp
- src/stocks_list.cpp
- src/stocks_list.h
This pull request contains the following changes:
1. Fixed a compile error and removed several warnings, which occurred during compilation under Linux .
2. Make stock in stock overview losses more visible:
Old: Losses are only indicated with a symbol:
New: Row in stock is colored:
3. Toggle Navigator with F6:
F6 did not work the show the navigator, if there was a previous click in account view window . Replaced with a more robust implementation.
4. Refactoring of the category dialog:
The current category dialog is not very intuitive, several changes were made to improve the user experience:
- Enhancement: Adapt and refactor category dialog
- Replace expand and hide toggle buttons with buttons
- New context menu options add and edit
- Move context menu option "clear settings" in own button …
> Pull request misc changes01

- NEWS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7753)
> chore(NEWS): remove old 1.9.1 beta reference
