- doc/version.txt
- src/constants.cpp
- src/mmframe.cpp
- src/model/Model_Infotable.cpp
- src/model/Model_Infotable.h
This updates the data of a version 2 database, and
sets the database version to 3
> feat(Database.Version): update the database version to 3

- src/import_export/univcsvdialog.cpp
- src/mmOption.cpp
- src/mmOptionGeneralSettings.cpp
- src/model/Model_Infotable.cpp
- src/model/Model_Infotable.h
- tests/db_init_model.cpp
- tests/test_filtertrans_dialog.cpp
- tests/test_relocate_category.cpp
- tests/test_relocate_payee.cpp
1. Provided global Model_Infotable.DateFornmat() function and redirected all functionality to it.
2. Test build failure fixed.
> fix(mmUnivCSVDialog.update_preview): selection of date format

- src/paths.cpp
Tested the fix mentioned at http://sourceforge.net/p/moneymanagerex/bugs/451/
> fix(paths.cpp) Help files not showing on ubuntu (#332)

- src/general_report_manager.cpp
- src/general_report_manager.h
https://github.com/moneymanagerex/moneymanagerex/issues/299
> feat(GRM.SQL): drag and drop for table elements

- Makefile.in
- setup/linux/debian/build.sh
create folder release during build.sh script in order to make compilation into
> refactor(Build.Debian): create folder release

- Makefile.in
- build/msw-vc-2013e/mmex_mmex.vcxproj
- build/msw-vc-2013e/mmex_mmex.vcxproj.filters
- build/msw/makefile.gcc
- build/msw/makefile.vc
- build/msw/mmex_mmex.vcproj
- build/msw_tests/makefile.gcc
- build/msw_tests/makefile.vc
- build/msw_tests/mmex_tests_mmex_tests.vcproj
- src/assetspanel.cpp
- src/assetspanel.h
- src/billsdepositspanel.cpp
- src/billsdepositspanel.h
- src/budgetingpanel.cpp
- src/budgetingpanel.h
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
- src/mmpanelbase.cpp
- src/mmpanelbase.h
- src/stockspanel.cpp
- src/stockspanel.h
- tests/Makefile.in
Add improved hide/show columns to panels.
> Siena123 dev

- Makefile.in
- configure
- src/import_export/qif_import_gui.cpp
- src/import_export/qif_import_gui.h
- src/model/Model_Account.cpp
- src/model/Model_Account.h
ability to chose account number instead of account name to match account #387
> feat(Import.qif.account): QIF import 

- src/accountdialog.cpp
- src/model/Model_Account.cpp
- src/model/Model_Account.h
Reverts moneymanagerex/moneymanagerex#416
> Revert "fix(Bug#.643): prevent name change to existing account"

- src/accountdialog.cpp
- src/model/Model_Account.cpp
- src/model/Model_Account.h
fix to previous patch which prevented creation of new accounts.
> fix(Bug#.643): prevent name change to existing account - correction

- src/billsdepositsdialog.cpp
- src/mmframe.cpp
Restrict when the date is set to today on entry.
> fix(Recurring.Transactions): date setting on entry

- doc/contrib.txt
- doc/license.txt
- src/aboutdialog.cpp
- src/aboutdialog.h
Adds a separate privacy tab in the about dialog to make it easier to find
> feat(aboutdialog): Add separate privacy tab

- lib/lua/Makefile
- lib/lua/README
- lib/lua/doc/contents.html
- lib/lua/doc/lua.css
- lib/lua/doc/manual.html
- lib/lua/doc/readme.html
- lib/lua/src/ldblib.c
- lib/lua/src/ldebug.c
- lib/lua/src/lgc.c
- lib/lua/src/llex.c
- lib/lua/src/lobject.h
- lib/lua/src/lopcodes.h
- lib/lua/src/ltablib.c
- lib/lua/src/lua.h
- lib/lua/src/luaconf.h
Update to Lua 5.2.4, which is a bugfix release
> update(lua): Updated lua to 5.2.4

- doc/help/french/investment.html
- doc/help/italian/index.html
- doc/help/italian/investment.html
- doc/help/spanish/budget.html
- doc/help/spanish/index.html
- doc/help/spanish/investment.html
Fixes problem with some characters caused by my last pull request
> chore(Help): Fix characters

- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
- src/transdialog.cpp
- src/transdialog.h
Preparations for the separation of functions for create new transaction as Transfer or Withdrawal/Deposit.
> refactor(Checking.Transaction): separate function for new transfer

- src/mmhomepagepanel.cpp
- src/stockspanel.cpp
Please cherrypick to 1.2.x branch
> fix(stocks): fix total value

- src/mmframe.cpp
> fix(mmframe): Fix typo in include

- src/transdialog.cpp
cherry pick, same fix as PR514
> fix(bug.sf707): properly handle from field for transfers

- src/accountdialog.cpp
- src/assetdialog.cpp
- src/billsdepositsdialog.cpp
- src/budgetentrydialog.cpp
- src/currencydialog.cpp
- src/filtertransdialog.cpp
- src/mmtextctrl.h
- src/splitdetailsdialog.cpp
- src/splittransactionsdialog.cpp
- src/stockdialog.cpp
- src/transdialog.cpp
- src/util.cpp
- src/validators.h
one method to enter numbers based on base currency
> fix(bug.716): numpad decimal char depend on currency settings

- po/italian.po
Translation updated;
Purged old translations;
Source code line references updated;
> fix(translations): italian translation updated;

- .gitignore
- build/msw-vc-2015/copy_files.bat
- build/msw-vc-2015/mmex.sln
- build/msw-vc-2015/mmex_lua.vcxproj
- build/msw-vc-2015/mmex_lua.vcxproj.filters
- build/msw-vc-2015/mmex_mmex.vcxproj
- build/msw-vc-2015/mmex_mmex.vcxproj.filters
- build/msw-vc-2015/mmex_wxsqlite.vcxproj
- build/msw-vc-2015/mmex_wxsqlite.vcxproj.filters
- build/msw-vc-2015/readme.txt
VS2015 raises some new warnings that will be fixed in another PR
> feat(build): Add build files for Visual Studio 2015

- src/transdialog.cpp
I think that should be backported to 1.2.x branch too
> fix(transaction): Add attachments on duplicate transaction

- doc/help/index.html
- src/import_export/parsers.cpp
- src/import_export/parsers.h
- src/import_export/univcsvdialog.cpp
- Add account name to template.
- Fix total number of rows reported by import.
- Remove unused function from parser classes
- Fix: parsing would complain if a line had less tokens than previous line.
- Help for XML import
> fix(Import): Some small fixes to import CSV/XML

- src/util.cpp
There are performance issues that come from wxDateTime::Format calling
wxGetTimeZone() that calls _tzset(). All this happens for every call to
wxDateTime::Format. mmGetDateForDisplay now implements a lookup
table that returns strings from previously queried dates.
The above issue relates particularly to visual studio but should improve
all compilations. I tested in mmCheckingPanel with ~60 transaction and
repaint time improved from fast to instantaneous.
> perf(Date.Formatting): improve performance by using lookup table

- src/model/Model_Checking.cpp
Refer to Issue: https://github.com/moneymanagerex/moneymanagerex/issues/620
> fix(Option.UseLastDate): fix option for new transactions

- resources/home_page.htt
- src/mmOption.cpp
- src/mmframe.cpp
- src/mmhomepagepanel.cpp
- src/model/Model_Account.cpp
- src/model/Model_Account.h
- src/model/Model_Asset.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Budget.cpp
- src/model/Model_Checking.cpp
This provides another separation for accounts.
Ref: Cash Account Type: https://github.com/moneymanagerex/moneymanagerex/issues/455
> feat(Account.Type.Cash): addition of new account type

- src/model/Model_CustomFieldData.h
This change is needed for me to be able to build the custom field changes on Linux
> fix(Customfield): Needed to build on Linux

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/billsdepositspanel.cpp
- src/mmframe.cpp
- src/model/Model_Billsdeposits.h
Ref: https://github.com/moneymanagerex/moneymanagerex/issues/561
> fix(Recurring.Transactions): reorganise transaction date on entry

- doc/help/index.html
- src/import_export/parsers.cpp
- src/import_export/parsers.h
- src/import_export/univcsvdialog.cpp
- src/import_export/univcsvdialog.h
- src/mmframe.cpp
- src/mmframe.h
Minor feature: option to output column headers.
> feat(Export.XML): export to XML format readable by Excel

- src/model/Model_Checking.cpp
> feat(note.freq): use pq to simplify most recent notes

- src/paths.cpp
see also pull request #593 from v1.2.x branch
> fix(issue.559): additional mac fix

- src/reports/htmlbuilder.cpp
- src/reports/transactions.cpp
> fix(#717): nowrap for date & money

- src/mmhomepagepanel.cpp
- src/reports/summary.cpp
> fix(HomePage) stock total value differs from single items stock value sum

- src/reports/summary.cpp
- src/reports/summary.h
> fix(report): monthly summary of accounts cleanup code

- src/constants.cpp
> fix(version): update

- src/db/readme.txt
- src/model/readme.txt
> fix(submodule.database): update submodule with updated instructions

- src/mmframe.cpp
- src/mmframe.h
> fix(#747): account type translation issue

- src/appstartdialog.cpp
- src/billsdepositsdialog.cpp
- src/constants.cpp
- src/mmex.cpp
- src/mmframe.cpp
- src/mmhelppanel.cpp
- src/reports/categexp.cpp
- src/wizard_newaccount.cpp
> fix(#757): fix incorrect translatable strings

- src/billsdepositsdialog.cpp
- src/budgetyearentrydialog.cpp
- src/categdialog.cpp
- src/customfieldeditdialog.cpp
- src/customfieldlistdialog.cpp
- src/mmOptionMiscSettings.cpp
- src/mmSimpleDialogs.cpp
- src/mmframe.cpp
- src/payeedialog.cpp
- src/stockdialog.cpp
- src/webapp.cpp
- src/wizard_newaccount.cpp
- src/wizard_newdb.cpp
> fix(#757): eol formating

- src/wizard_newaccount.cpp
- src/wizard_newaccount.h
> feat(#767): renamed and reordered pages

- src/appstartdialog.cpp
- src/general_report_manager.cpp
- src/import_export/qif_export.cpp
- src/import_export/qif_import_gui.cpp
- src/import_export/univcsvdialog.cpp
- src/mmHook.h
- src/mmOption.cpp
- src/mmOption.h
- src/mmOptionGeneralSettings.cpp
- src/mmSimpleDialogs.cpp
- src/mmframe.cpp
- src/mmframe.h
- src/mmhelppanel.cpp
- src/reports/budget.cpp
- src/reports/htmlbuilder.cpp
- src/stockdialog.cpp
- src/util.cpp
- src/wizard_newdb.cpp
> Class mmoptions update

- po/lithuanian.po
> fix(po): c-format

- .gitignore
- src/aboutdialog.cpp
- src/db/DB_Upgrade.h
- src/webappdialog.cpp
Need to upgrade DB submodule with this patch too:
https://github.com/moneymanagerex/database/pull/15
> fix(database): upgrade to version 5 for Android compatibility

- appveyor.yml
- build/bakefiles/presets/wx.bkl
- build/msw-vc-2013e/mmex_mmex.vcxproj
- build/msw-vc-2015/mmex_mmex.vcxproj
- build/msw/config.gcc
- build/msw/config.vc
- build/msw/mmex_mmex.vcproj
- build/msw_tests-vc-2013e/mmex_tests_mmex_tests.vcxproj
- build/msw_tests/mmex_tests_mmex_tests.vcproj
> Wxwidgets 3.1.0 upgrade

- appveyor.yml
- setup/win/update_mmex_build_files.bat
> feat(build.nightly): Add bin to Appveyor

- appveyor.yml
Should be fixed, but I cannot check until merged
> fix(build.nightly): fix caching issue

- appveyor.yml
> fix(build.nightly): remove unnecessary zip

- appveyor.yml
> fix(build.nightly): add build number

- src/currencydialog.cpp
> fix(Base.Currency.Crash): update

- src/db/DB_Upgrade.h
> fix(DB.Upgrade): new tables updates database revision to v6

- src/assetdialog.cpp
- src/assetdialog.h
- src/assetspanel.cpp
- src/assetspanel.h
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
- src/mmhomepagepanel.cpp
- src/model/Model_Category.cpp
- src/reports/cashflow.cpp
- src/reports/incexpenses.cpp
- src/reports/payee.cpp
- src/reports/transactions.cpp
- src/stockspanel.cpp
Addition of Asset transfers similar to Shares
Exclude foreign transfers in income/expense calculations
> Translink shares

- src/assetdialog.cpp
- src/assetdialog.h
- src/assetspanel.cpp
- src/mmcheckingpanel.cpp
- src/usertransactionpanel.cpp
> feat(Translink): update asset navigation

- src/model/Model_Billsdeposits.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/822)
> fix(attachments): Fix bug #806

- build/msw-vc-2013e/mmex_mmex.vcxproj
- src/mmcheckingpanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/823)
> Invalid Vector fix

- src/mmex.cpp
- src/mmframe.cpp
- src/model/Model_Usage.cpp
- src/option.cpp
- src/option.h
- src/optionsettingsnet.cpp
Set the setting as an Option
Sets the option for Model_Usage::pageview(...)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/825)
> style(Option.SendUsageStats): create option setting

- doc/help/index.html
- src/assetdialog.cpp
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
- src/reports/transactions.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/827)
> Updates to Assets and Shares

- src/mmcheckingpanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/828)
> fix(Popup.Menu.Items): foreign transactions

- build/msw-vc-2015/mmex_mmex.vcxproj
- build/msw-vc-2015/mmex_mmex.vcxproj.filters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/831)
> fix(vs2015): project files update

- src/constants.cpp
- src/constants.h
- src/filtertransdialog.cpp
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
- src/optionsettingsview.cpp
Ref #537
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/835)
> feat(Issue #537): enhancement of transaction filters

- src/optionsettingsnet.cpp
- src/webserver.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/837)
> fix(#836): disable by default web server

- src/import_export/export.cpp
- src/import_export/qif_import_gui.cpp
- src/import_export/univcsvdialog.cpp
- src/mmframe.cpp
- src/mmhomepagepanel.cpp
- src/reports/summary.cpp
- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/844)
> feat(include): simplification and cleanup

- src/model/Model_Translink.cpp
- src/option.cpp
- src/option.h
- src/optionsettingsmisc.cpp
- src/optionsettingsmisc.h
- src/sharetransactiondialog.cpp
- src/sharetransactiondialog.h
- src/stockdialog.cpp
- src/stockspanel.cpp
- src/usertransactionpanel.cpp
- src/usertransactionpanel.h
Fixes currency problems: issue #840   
Uses share precision as an option: issue #839 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/845)
> Stocks and Shares updates

- src/dbupgrade.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/849)
> fix(db.debug): improvements

- src/assetdialog.cpp
- src/assetspanel.cpp
- src/assetspanel.h
- src/model/Model_Translink.cpp
- src/model/Model_Translink.h
Allows multiple assets to use a single account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/848)
> feat(Asset.Management): refine asset transaction to any account

- src/reports/htmlbuilder.cpp
- src/reports/summarystocks.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/851)
> fix(Stock.Summary.Report): fix displayed currency

- src/constants.cpp
- src/maincurrencydialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/855)
>  fix(#853): currency exchange rate download

- src/mmhomepagepanel.cpp
- tests/test_date_range.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/858)
> bug: 893 Loss of Home page expansions on startup

- doc/version.txt
- setup/win/mmex_win32_setup.iss
- setup/win/mmex_x64_setup.iss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/860)
> setup updates

- src/billsdepositsdialog.cpp
- src/mmframe.cpp
- src/model/Model_Account.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Billsdeposits.h
- src/transdialog.cpp
Feature: 227 Overdraft limit on Current Accts
https://sourceforge.net/p/moneymanagerex/feature-requests/227/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/862)
> feat(Recurring.Transaction): activate account limit warnings

- doc/help/general_report_manager.html
- doc/help/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/863)
> doc(Update): Account types and Recurring Transactions

- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
Fault report: #867 
Also updated method names
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/868)
> fix(Duplicate.Transaction): issue #867

- src/accountdialog.cpp
- src/accountdialog.h
- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/currencydialog.cpp
- src/maincurrencydialog.cpp
- src/maincurrencydialog.h
- src/model/Model_Currency.cpp
- src/model/Model_Currency.h
- src/transdialog.cpp
- src/transdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/869)
> feat(BitCoin.Transaction): issue #866

- src/mmframe.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/871)
> fix(Navigation.Popup): provide for Cash and Loan accounts

- src/accountdialog.cpp
- src/accountdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/873)
> fix(SF.Bugs.901): Edit Account - Access Info not displayed

- src/maincurrencydialog.cpp
- src/maincurrencydialog.h
- src/mmframe.cpp
- src/model/Model_Currency.cpp
- src/model/Model_Currency.h
- src/model/Model_CurrencyHistory.cpp
- src/model/Model_CurrencyHistory.h
- src/option.cpp
- src/wizard_newdb.cpp
Ref: https://sourceforge.net/p/moneymanagerex/bugs/326/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/875)
> fix(Base.Currency): ensure base currency set in database

- .gitignore
- src/import_export/qif_import_gui.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/876)
> fix(#861): qif import fix

- build/bakefiles/mmex.bkl
Fix to bakefile so .app bundle is built properly on mac.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/877)
> chore(build): fix bkl for mac

- po/polish.po
- po/russian.po
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/885)
> fix(po): update

- russian.po
- src/customfieldeditdialog.cpp
- src/customfieldlistdialog.cpp
- src/general_report_manager.cpp
- src/import_export/parsers.cpp
- src/import_export/univcsvdialog.cpp
- src/model/Model_Attachment.cpp
typo fixex and uneused translations cleanup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/887)
> fix(#883): typo fixex and uneused translations cleanup

- src/categdialog.cpp
- src/categdialog.h
- src/mmframe.cpp
- src/payeedialog.cpp
- src/relocatecategorydialog.cpp
- src/transdialog.cpp
- src/transdialog.h
- provided transaction type for the categories manager (for future development)
- fix crash for hiden categorias
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/881)
> fix(#879): fix crash and improvements

- src/billsdepositsdialog.cpp
- src/categdialog.cpp
- src/categdialog.h
- src/filtertransdialog.cpp
- src/payeedialog.cpp
- src/relocatecategorydialog.cpp
- src/splitdetailsdialog.cpp
- src/transdialog.cpp
- src/usertransactionpanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/892)
> fix(#888): crash fix and improvements

- po/spanish.po
It needs to be reviewed again to see if they are all translated strings and once the language file is available for use with version 1.3.0 rc.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/895)
> fix(po): Update spanish.po

- po/russian.po
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/897)
> fix(Russian): update

- po/russian.po
> Fix(Russian.po): update

- src/customfieldeditdialog.cpp
- src/model/Model_CustomField.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/900)
> fix(#899): custom fiels type fix

- src/customfielddialog.cpp
- src/customfieldeditdialog.cpp
- src/customfieldeditdialog.h
- src/db/DB_Table_Customfield_V1.h
- src/db/DB_Upgrade.h
- src/model/Model_CustomField.cpp
- src/model/Model_CustomField.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/905)
> fix(#903): typo fixes

- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/907)
> perf(#906): transactions filters improvements

- po/dutch.po
- po/russian.po
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/915)
> fix(Dutch.po): update

- src/optiondialog.cpp
- src/optionsettingsgeneral.cpp
- src/optionsettingsgeneral.h
- src/reports/mmDateRange.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/914)
> fix(#782): datetime assertion

- src/filtertransdialog.cpp
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/911)
> refactor(Date.Range): cleanup

- po/italian.po
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/919)
> fix(translation): Update italian translation

- src/assetspanel.cpp
- src/billsdepositspanel.cpp
- src/filtertransdialog.cpp
- src/import_export/export.cpp
- src/import_export/qif_export.cpp
- src/import_export/qif_import_gui.cpp
- src/maincurrencydialog.cpp
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
- src/model/Model_Account.cpp
- src/model/Model_Account.h
- src/option.cpp
- src/reports/cashflow.cpp
- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/summary.cpp
- src/reports/summarystocks.cpp
- src/reports/transactions.cpp
- src/stockdialog.cpp
- src/stockspanel.cpp
- src/transdialog.cpp
- src/util.cpp
- src/util.h
- src/webapp.cpp
- src/webappdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/916)
> perf(#906): speedup, cache

- src/mmcheckingpanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/940)
> fix(#936): selected item fixes

- src/accountdialog.cpp
- src/webserver.cpp
- tests/defined_test_selection.h
- tests/test_stocks.cpp
- tests/test_stocks.h
- tests/test_translink.cpp
- tests/test_translink.h
Tests updated to track down bug #921 
Also addressed #942
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/944)
> Updated tests for #921

- src/billsdepositsdialog.cpp
- src/mmframe.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Billsdeposits.h
Here is the performance improvement that I mentioned could be done without doing the major overhaul in the way the account balance is handled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/945)
> fix(#923): performance improvement

- src/usertransactionpanel.cpp
- src/usertransactionpanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/947)
> fix(issue#921): investment fund error

- src/transdialog.cpp
Fix from Anonymous user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/948)
> fix(#957): Ensure lists are the same

- src/filtertransdialog.cpp
- src/mmcheckingpanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/951)
> fix(#949): remove memory leak

- src/mmcheckingpanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/955)
> fix(View.Statement.Date): prevent mmex crash

- src/transdialog.cpp
- src/transdialog.h
Ref: https://sourceforge.net/p/moneymanagerex/bugs/967/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/958)
> fix(bug.967): crash on new transaction

- appveyor.yml
Set AppVeyor Version to 1.3.xxx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/959)
> fix(AppVeyor.Version): version update

- src/mmframe.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/960)
> fix(issue#956): automatic database backup on start-up

- src/categdialog.cpp
Ref: https://sourceforge.net/p/moneymanagerex/bugs/969/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/961)
> fix(issue#969): Crash after adding first level category

- setup/win/mmex_win32_setup.iss
- setup/win/mmex_x64_setup.iss
- setup/win/update_mmex_build_files.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/962)
> fix(Win.Setup): build files

- doc/contrib.txt
- doc/version.txt
🔢
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/966)
> fix(docs): update sponsors info

- src/mmSimpleDialogs.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/970)
> fix(#969): assert fix

- doc/contrib.txt
- setup/win/update_mmex_build_files.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/973)
> fix to documantation and win setup

- src/import_export/qif_import_gui.cpp
- src/import_export/qif_import_gui.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/976)
> feat(#975): more messages for import errors

- resources/home_page.htt
- src/mmhomepagepanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/978)
> fix(#977): speedup & html formating

- src/maincurrencydialog.cpp
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/981)
> fix(#980): speedup by reducing the use of wxdatetime::today

- src/option.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/982)
> fix(#963): workaround

- src/maincurrencydialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/983)
> fix(#649): log only for used currencies

- src/billsdepositsdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/985)
> fix(#964): eol added

- src/images_list.cpp
- src/import_export/univcsvdialog.cpp
- src/mmframe.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/986)
> fix(#941): asserts condition correction

- po/abkhazian.po
- po/albanian.po
- po/burmese.po
- po/catalan.po
- po/finnish.po
- po/korean.po
- po/malayalam.po
- po/persian.po
- po/po.bkl
- po/thai.po
- setup/win/mmex_win32_setup.iss
- setup/win/mmex_x64_setup.iss
Abkhazian Albanian Burmese Catalan Finnish Korean Malayalam Persian Thai
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/992)
> feat(Languages): new

- doc/license.txt
- doc/version.txt
This will also bring v1.3 branch inline with master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/993)
> fix(Version.Info): update info for v1.3.1

- doc/version.txt
- po/MoneyManagerEx.pot
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/994)
> feat(#675): moreinfo for selected transactions

- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/995)
> feat(#953): transactions focus

- appveyor.yml
- setup/win/update_mmex_build_files.bat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/997)
> fix(Win.Build): Switch from MSVC_2013 to MSVC_2015 Stage 1 of 2

- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/998)
> fix(Win.Build): Switch from MSVC_2013 to MSVC_2015 Stage 2 of 2

- setup/win/mmex_win32_setup.iss
- setup/win/mmex_x64_setup.iss
Updating master from v1.3.x branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1000)
> fix(Executable): dll replace

- build/bakefiles/mmex.bkl
- doc/version.txt
- setup/win/mmex_win32_setup.iss
- setup/win/mmex_x64_setup.iss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1005)
> Setup info from branch v1.3.x also required in master branch

- src/billsdepositsdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1009)
> fix(#1006): open accounts only

- setup/win/mmex_win32_setup.iss
- setup/win/mmex_x64_setup.iss
Ref: https://sourceforge.net/p/moneymanagerex/bugs/972/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1011)
> fix(SF.Issue.972): Programs and Features icon in Windows

- po/albanian.po
http://forum.moneymanagerex.org/viewtopic.php?f=6&t=6912
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1014)
> fix(Albanian): lang file update

- src/import_export/export.cpp
- src/import_export/export.h
- src/import_export/qif_export.cpp
- src/import_export/qif_export.h
- src/import_export/qif_import_gui.cpp
- src/import_export/qif_import_gui.h
- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- src/reports/reportbase.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1018)
> chore(): code rebase

- src/mmhomepagepanel.cpp
Adds a null check to prevent a crash on my machine
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1020)
> fix(#1019): add null check

- doc/contrib.txt
- po/hebrew.po
- po/hungarian.po
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1022)
> fix(Translation): update

- src/import_export/export.cpp
- src/import_export/export.h
- src/import_export/qif_import_gui.cpp
- src/import_export/qif_import_gui.h
- src/util.cpp
- src/util.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1023)
> fix(#1015): account type support

- util/sqlite2cpp.py
This will allow for the generation of a patch file for currency data, as well as a database version upgrade file.
The upgrade file will contain only the currencies that have Unicode data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1029)
> feat(sqlite2cpp.py): generate currency data for upgrade or patch

- src/budgetyeardialog.cpp
- src/budgetyeardialog.h
- src/budgetyearentrydialog.cpp
- src/mmframe.cpp
- src/mmframereport.cpp
- src/mmreportspanel.cpp
- src/mmreportspanel.h
- src/reports/budget.cpp
- src/reports/budget.h
- src/reports/budgetcategorysummary.cpp
- src/reports/budgetcategorysummary.h
- src/reports/budgetingperf.cpp
- src/reports/budgetingperf.h
- src/reports/reportbase.cpp
- src/reports/reportbase.h
Initial changes to budget reports for feature #626
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1031)
> feat(reports): updates to budget reports

- src/mmframe.cpp
- src/mmframe.h
Add a popup menu option to display balances of an account
at the account currency and at base currency
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1032)
> feat(HomePage.Navigation): Foreign Currency Account balance

- src/aboutdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1034)
> fix(#1033): file exists check

- src/budgetyearentrydialog.cpp
- src/mmframe.cpp
- src/mmframereport.cpp
- src/mmreportspanel.cpp
- src/mmreportspanel.h
- src/reports/budget.cpp
- src/reports/budget.h
- src/reports/budgetingperf.cpp
- src/reports/budgetingperf.h
- src/reports/reportbase.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1035)
> style(reports): change tabs to spaces

- src/mmframe.cpp
Changed  wxTRANSLATE to _(
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1037)
> feat(Issue.#1036): Foreign Currency Account balance (update)

- src/model/Model_Usage.cpp
- src/model/Model_Usage.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1039)
> chore(#1030): simplification

- src/mmpanelbase.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1041)
> fix(Issue#1038): build with msvc_2017 on win10

- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/reports/transactions.cpp
- src/reports/transactions.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1044)
> fix(#1043): null account

- src/billsdepositspanel.cpp
- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Billsdeposits.h
- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1046)
> feat(#1045): split amount search

- src/mmframe.cpp
- src/mmframereport.cpp
- src/option.cpp
- src/option.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1055)
> refactor(reports): combine common code to single location

- po/MoneyManagerEx.pot
- po/russian.po
- src/webserver.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1054)
> chore(*): pot update and web server sql api fix

- src/mmreportspanel.cpp
- src/mmreportspanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1059)
> feat(#789): custom dates on reports

- src/model/Model_Usage.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1061)
> fix(#979): check for null pointer

- src/mmframe.cpp
- src/mmpanelbase.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1067)
> fix(#1064): html report export

- .gitignore
- Makefile.in
- build/msw-vc-2015/mmex_mmex.vcxproj
- build/msw-vc-2015/mmex_mmex.vcxproj.filters
- src/mmcheckingpanel.cpp
- src/transactionsupdatedialog.cpp
- src/transactionsupdatedialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1062)
> feat(#909): #1025

- src/mmreportspanel.cpp
- src/option.cpp
- src/option.h
- src/reports/budgetcategorysummary.cpp
- src/reports/budgetingperf.cpp
- src/reports/reportbase.cpp
- src/reports/reportbase.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1068)
> Retain report settings between sessions

- src/mmcheckingpanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1072)
> feat(#1060): more columns for search

- src/reports/reportbase.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1073)
> fix(#1069): report title

- src/assetspanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1075)
> fix(#1074): assets

- src/reports/reportbase.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1079)
> fix(#1021): correct macro

- src/reports/summary.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1077)
> fix(#1021): summary report

- src/mmreportspanel.cpp
- src/mmreportspanel.h
- src/model/Model_Report.cpp
- src/model/Model_Report.h
- src/reports/categexp.cpp
- src/reports/categexp.h
- src/reports/forecast.cpp
- src/reports/forecast.h
- src/reports/incexpenses.cpp
- src/reports/incexpenses.h
- src/reports/myusage.cpp
- src/reports/myusage.h
- src/reports/payee.cpp
- src/reports/payee.h
- src/reports/reportbase.cpp
- src/reports/reportbase.h
- src/reports/summarystocks.cpp
- src/reports/summarystocks.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1088)
> feat(#1085): parameters for grm stage 1 

- build/msw-vc-2017/mmex_lua.vcxproj
- build/msw-vc-2017/mmex_mmex.vcxproj
- build/msw-vc-2017/mmex_mmex.vcxproj.filters
- build/msw-vc-2017/mmex_wxsqlite.vcxproj
- build/msw_tests_vc_2017/mmex_tests_cppunit.vcxproj
- build/msw_tests_vc_2017/mmex_tests_lua.vcxproj
- build/msw_tests_vc_2017/mmex_tests_mmex_tests.vcxproj
- build/msw_tests_vc_2017/mmex_tests_mmex_tests.vcxproj.filters
- build/msw_tests_vc_2017/mmex_tests_wxsqlite.vcxproj
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1092)
> fix(VS2017): update project

- build/msw-vc-2017/mmex_mmex.vcxproj
- build/msw-vc-2017/mmex_mmex.vcxproj.filters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1093)
> chore(project): added missing files to VS2017 project

- src/general_report_manager.cpp
- src/mmreportspanel.cpp
- src/model/Model_Report.cpp
- src/model/Model_Report.h
- src/reports/reportbase.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1094)
> fix(#1085): single date, cleanup, fixes

- src/reports/summary.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1095)
> chore(summary.report): cleanup

- src/reports/reportbase.cpp
- src/reports/summary.cpp
- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1100)
> fix(#1098): assert failure

- src/mmreportspanel.cpp
- src/model/Model_Report.cpp
- src/reports/budget.cpp
- src/reports/budget.h
- src/reports/budgetcategorysummary.cpp
- src/reports/budgetcategorysummary.h
- src/reports/budgetingperf.cpp
- src/reports/budgetingperf.h
- src/reports/categexp.cpp
- src/reports/htmlbuilder.cpp
- src/reports/incexpenses.cpp
- src/reports/payee.cpp
- src/reports/reportbase.cpp
- src/reports/summary.cpp
- src/reports/summarystocks.cpp
Isuue #1099 also fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1101)
> fix(#1085): post update fixes

- src/mmcheckingpanel.cpp
Ref: https://sourceforge.net/p/moneymanagerex/bugs/1026/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1121)
> fix(bug.1026): disallow duplicate for foreign transaction

- src/import_export/qif_import_gui.cpp
- src/import_export/qif_import_gui.h
- src/util.cpp
- src/util.h
Sort order for date masks recovered
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1125)
> fix(#1109): new date masks

- .travis.yml
- .travis.yml.in
- CMakeLists.txt
- appveyor.yml
- appveyor.yml.in
- src/constants.h.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1129)
> docs(mmex.version): include information about version settings

- src/mmframe.cpp
- src/mmframe.h
- src/mmreportspanel.cpp
- src/mmreportspanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1130)
> Feat 990 (add prev/next option to reports)

- CMakeLists.txt
- doc/INSTALL.Fedora.md
- doc/INSTALL.Ubuntu.md
- doc/INSTALL.Windows.md
- doc/INSTALL.macOS.md
- doc/INSTALL.openSUSE.md
- resources/mmex.rc.in
Based on @vomikan code review I simplified install commands and added generation of VS resource script via CMake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1133)
> refactor(docs,cmake)

- src/mmframe.cpp
- src/mmframe.h
- src/mmreportspanel.cpp
- src/mmreportspanel.h
Reverts moneymanagerex/moneymanagerex#1130
what we need is previous/next period or time window.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1134)
> Revert "Feat 990 (add prev/next option to reports)"

- update_cmake_build.bat
- util/update_cmake_build_for_msv.bat
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1137)
>  fix(msvc.cmake): update locations for support files

- po/MoneyManagerEx.pot
- po/albanian.po
- po/dutch.po
- po/dutch_be.po
- po/english.po
- po/french.po
- po/hebrew.po
- po/hungarian.po
- po/italian.po
- po/polish.po
- po/russian.po
- po/serbian.po
- po/swedish.po
- src/billsdepositsdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1138)
> fix(translaions): update

- src/splitdetailsdialog.cpp
- src/splitdetailsdialog.h
sure that code would work on both windows, linux and osx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1139)
> fix(#1120): set focus

- src/currencydialog.cpp
- src/currencydialog.h
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1141)
> fix(#1115): division by zero

- .travis.yml
- dockers/Dockerfile.ubuntu.zesty
tested on Ubuntu Zesty amd64 https://travis-ci.org/slodki/moneymanagerex/builds/229272411
build package https://github.com/slodki/moneymanagerex/releases/tag/publish_test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1148)
> fix(dockerfile): Add build support for Ubuntu Zesty

- src/currencydialog.cpp
- src/currencydialog.h
- src/maincurrencydialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1157)
> fix(Currencies): #1154 #1155 #1156 #1153

- .travis.yml
- CMakeLists.txt
Just changed the way of setting runtime requirements for linux package.
https://github.com/moneymanagerex/moneymanagerex/issues/1149
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1159)
> fix(fedora): #1149

- po/MoneyManagerEx.pot
- po/dutch.po
- po/portuguese_br.po
- po/russian.po
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1163)
> fix(translations): update

- src/stockdialog.cpp
- src/stockdialog.h
- src/stockspanel.cpp
Improved tooltips and closes main Stock screen on creating new initial stock.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1164)
> Stock shares update sf.bugs.1015

- src/dbupgrade.cpp
- src/dbupgrade.h
This also provides automatic solution to #1162 and
https://sourceforge.net/p/moneymanagerex/bugs/927/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1165)
> fix(#1147): provide database version correction

- src/dbupgrade.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1167)
> fix(#1166): compile warning

- src/mmex.cpp
- src/model/Model_Setting.cpp
- src/model/Model_Setting.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1168)
> fix(#1144): delete records in usage table when it gets too big

- CMakeLists.txt
- appveyor.yml
- src/constants.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1171)
> fix(version): 1.4.0-alfa-1

- doc/version.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1173)
> docs(Version.History): update for v1.4.x series

- src/mmcheckingpanel.cpp
- src/mmpanelbase.cpp
- src/mmpanelbase.h
Also add in support to wxListCtrl to get all selected indices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1186)
> feat(checking.panel): Add in support to move multiple selected transactions for a checking panel

- appveyor.yml
- appveyor.yml.in
- src/assetdialog.cpp
- src/mmtextctrl.h
- src/sharetransactiondialog.cpp
- src/usertransactionpanel.cpp
- src/usertransactionpanel.h
- src/util.cpp
Bug report Ref: https://sourceforge.net/p/moneymanagerex/bugs/1032/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1187)
> fix(sf.bug.1032): Miscalculation of Shares

- src/filtertransdialog.cpp
- src/filtertransdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1191)
> fix(Issue.#1189): auto saving transaction filter options

- src/paths.cpp
This fixes #1177 (tested)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1200)
> fix #1177: update broken filename

- src/db/DB_Table_Currencyformats_V1.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1152)
> fix(Currencyformats): Updated default PLN definition

- .travis.yml
this is small fix for c688324 from #1220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1222)
> fix(docker): don't copy sources to container but use volume to share

- src/mmcheckingpanel.cpp
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
These were rolled back in recent commit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1236)
> chore(Submodule.Database): update

- src/reports/cashflow.cpp
- src/reports/cashflow.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1246)
> fix(#1234): Cash flow for specific accounts

- src/dbupgrade.cpp
- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1249)
> fix(#1245): crash with no database using Reallocate Account

- po/french.po
I reviewed all the content of the file French.po
Some translations would have to be edited because of the context, which is hard to visualize with PoEdit.
The file need to be tested on the different OS. French langage uses specials char like : 'é', 'î' etc...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1252)
> fix(translations):update

- util/build_db_tables.bat
- util/sqlite2cpp.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1274)
> cleanup(sqlite2cpp.py): generate a Unicode currency fix patch

- .travis.yml
- README.md
- appveyor.yml
See https://github.com/moneymanagerex/moneymanagerex/wiki/Deploying-build-artifacts-from-CI-platforms
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1282)
> fix(ci.deployment): fix deployments from CI to GitGub Releases

- CMakeLists.txt
- appveyor.yml
- doc/version.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1284)
> feat(release.alpha): bump version to alpha3

- src/mmframe.cpp
fixes bug #1300 in 72bdfec06462eedf50ff1779069ccfbb36d4dbf6 from #1221
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1309)
> fix(#1300): display Privacy tab at startup

- BUILD.md
- INSTALL.md
macOS instructions to be updated by someone
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1312)
> feat(doc): add INSTALL.md file with installation procedures

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1316)
> fix(readme): update links and format

- 3rd/CMakeLists.txt
- dockers/debian.buster/Dockerfile
- dockers/debian.jessie/Dockerfile
- dockers/debian.stretch/Dockerfile
- dockers/opensuse.42.2/Dockerfile
- dockers/ubuntu.artful/Dockerfile
- dockers/ubuntu.xenial/Dockerfile
- dockers/ubuntu.zesty/Dockerfile
**update** wxSQLite submodule to latest 3.5.7 (SQLite to 3.20.1)
use distribution Lua 5.2.x or wxSQLite in docker image where available
Generated  binary packages [ready to download](https://github.com/slodki/moneymanagerex/releases/tag/test1)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1321)
> feat(cmake): use system shared Lua/wxSQLite lib version if avaiable

- po/ru.po
:)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1329)
> fix(i18n): ru.po update

- src/mmreportspanel.cpp
- src/reports/htmlbuilder.cpp
- src/reports/reportbase.cpp
- src/util.cpp
- src/util.h
Should fix #1327 & #1328
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1330)
> fix(#1328): date format for reports

- src/mmframereport.cpp
- src/option.cpp
report name translation on init fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1333)
> fix(#1324): report name translation on init

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1344)
> fix(travis): workaround for travis-ci/travis-ci#8552

- .travis.yml
- CMakeLists.txt
This should fix #1342 and add package for latest macOS 10.13 High Sierra
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1346)
> fix(#1342): prefer static linking while building Mac binary package

- src/mmframereport.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1351)
> fix(#1334): reports sorting

- .travis.yml
- dockers/slackware.14.2/Dockerfile
- dockers/ubuntu.artful/Dockerfile
- dockers/ubuntu.xenial/Dockerfile
- dockers/ubuntu.zesty/Dockerfile
Don't build Debian Buster and Ubuntu Artful broken by issue #1331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1352)
> fix(docker): optimize docker files for Travis CI builds

- BUILD.md
- contrib.txt
- license.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1379)
> fix build and copyright information

- src/budgetingpanel.cpp
- src/reports/budgetcategorysummary.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1380)
> fix(#1311): fix budget summary variance values

- BUILD.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1381)
> doc(build): restore build instructions

- src/model/Model_Currency.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1393)
> fix(currency): prevent crash when currency not exist in database

- src/assetdialog.cpp
- src/assetspanel.cpp
- src/billsdepositsdialog.cpp
- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
- src/sharetransactiondialog.cpp
- src/usertransactionpanel.cpp
- src/usertransactionpanel.h
Retry to fix appveyor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1408)
> Fix for Git Issues

- developers.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1417)
> doc(map): add a developer

- version.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1418)
> docs(Version.History): update for v1.4.0 release

- src/mmSimpleDialogs.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1426)
> fix(#1408): fixed typo

- dockers/el.7/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1427)
> fix(docker): use proper way to add epel repo in CentOS

- BUILD.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1429)
> fix(build): typo fix

- src/constants.cpp
- src/mmframe.cpp
\u2022 ("&bull;") is avaiable in windows cp1252 too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1430)
> style(about): change bullet char used in about dialog window

- .travis.yml
- util/Brewfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1359)
> Use brew bundle

- src/maincurrencydialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1458)
> fix(currency): guard against nullptr in dialog

- src/mmex.cpp
- src/mmex.h
- src/mmframe.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1459)
> fix(#1456): set locale

- src/maincurrencydialog.cpp
- src/model/Model_Account.cpp
- src/model/Model_Account.h
- src/stockspanel.cpp
- src/util.cpp
- src/util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1471)
> fix(#1460): refactoring

- po/ru.po
- src/reports/transactions.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1470)
> fix(#1463): header

- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1479)
> fix(#1476): assets visible

- src/mmframe.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1478)
> fix(#1460): account selection

- src/filtertransdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1480)
> fix(#1472): warnings added

- src/mmcheckingpanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1482)
> fix(#1481): future transactions

- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1483)
> fix(#1083): simple validation

- src/currencydialog.cpp
- src/currencydialog.h
- src/maincurrencydialog.cpp
- src/maincurrencydialog.h
- src/model/Model_Currency.cpp
- src/wizard_newdb.cpp
improvements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1490)
> fix(#1489): null pointer

- .appveyor.yml
see [Release Notes](https://wxwidgets.org/news/2018/02/wxwidgets-3.1.1-released/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1499)
> chore(AppVeyor): update wxWidgets to 3.1.1 for windows builds

- src/import_export/univcsvdialog.cpp
- src/maincurrencydialog.cpp
- src/mmframe.cpp
- src/mmhomepagepanel.cpp
- src/reports/myusage.cpp
- src/stockdialog.cpp
- src/util.cpp
TBC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1502)
> fix(#1207): update

- src/db/DB_Table.h
- src/import_export/univcsvdialog.cpp
- src/mmframe.cpp
- src/search/Search.h
- src/webapp.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1510)
> fix(#1207): next step

- 3rd/CMakeLists.txt
- dockers/debian.buster.x86/Dockerfile
- dockers/debian.buster/Dockerfile
- dockers/debian.jessie.x86/Dockerfile
- dockers/debian.jessie/Dockerfile
- dockers/debian.stretch.x86/Dockerfile
- dockers/debian.stretch/Dockerfile
- dockers/opensuse.42.2/Dockerfile
- dockers/ubuntu.artful.x86/Dockerfile
- dockers/ubuntu.artful/Dockerfile
- dockers/ubuntu.xenial.x86/Dockerfile
- dockers/ubuntu.xenial/Dockerfile
- dockers/ubuntu.zesty.x86/Dockerfile
- dockers/ubuntu.zesty/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1511)
> chore(lua): upgrade to latest v5.3.4

- po/pl.po
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1523)
> fix(i18n): Polish translation update

- .travis.yml
- dockers/linuxmint.sonya/Dockerfile
- dockers/linuxmint.sylvia.x86/Dockerfile
- dockers/linuxmint.sylvia/Dockerfile
- dockers/linuxmint.tara.x86/Dockerfile
- dockers/linuxmint.tara/Dockerfile
- dockers/ubuntu.artful.x86/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1524)
> fix(#1409): add Dockerfiles for latest Linux Mint

- src/filtertransdialog.cpp
- src/import_export/univcsvdialog.cpp
- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1520)
> fix(#1207): improvements

- src/model/Model_Report.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1525)
> fix(Model_Report): case structure

- .appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1532)
> chore(libcurl): update Windows builds to latest libcurl 7.59.0

- src/relocatecategorydialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1535)
> fix(#1498): cancel default if nothing to replace

- src/mmframe.cpp
- src/mmhomepagepanel.cpp
- src/option.cpp
- src/option.h
- src/reports/reportbase.cpp
- src/wizard_update.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1543)
> fix(#1542): more json checks

- src/reports/myusage.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1546)
> fix(#1203): initial value

- src/import_export/univcsvdialog.cpp
- src/mmframe.cpp
- src/mmhomepagepanel.cpp
- src/model/Model_Category.cpp
- src/platfdep.h
- src/relocatecategorydialog.cpp
- src/reports/payee.cpp
- src/reports/summarystocks.cpp
- src/webapp.cpp
- src/webserver.cpp
- src/win/platfdep.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1544)
> fix(warnings): eliminate compile warnings, dead code and typos

- .appveyor.yml
- 3rd/CMakeLists.txt
- util/MSVC-C.cmake.patch
This adds new ciphers:
* ChaCha20 - Poly1305 HMAC (sqleet, new wxSQLite3 default)
* AES 256 Bit CBC - SHA1 HMAC (SQLCipher, database versions 1, 2, and 3)
See https://github.com/utelle/wxsqlite3/releases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1547)
> chore(wxsqlite3): update wxsqlite3 to v4.0.2 and sqlite3 to v3.23.1

- src/mmcheckingpanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1551)
> fix(#1482): ignore future dates

- src/mmframereport.cpp
- src/reports/incexpenses.cpp
- src/reports/reportbase.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1556)
> fix(#1545): two var with the same name

- src/reports/reportbase.cpp
#1545
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1557)
> chore(reportbase): json settings format update

- src/relocatecategorydialog.cpp
- src/relocatecategorydialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1558)
> fix(#1497): Relocate Category Dialog disable/enable OK button

- src/model/Model_Report.cpp
- src/reports/mmDateRange.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1560)
> fix(#1559): oldest date

- src/mmreportspanel.cpp
- src/model/Model_Report.cpp
- src/reports/reportbase.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1561)
> fix(#1085): update

- src/model/Model_Infotable.cpp
thx @vomikan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1572)
> fix(#1569): fix typo

- src/relocatepayeedialog.cpp
- src/relocatepayeedialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1575)
> fix(#1564): cleanup

- src/model/Model_CustomField.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1597)
> fix(#1089): typo fix

- src/dbupgrade.cpp
- src/general_report_manager.cpp
- src/mmframe.cpp
Please try following mmdbg scripts:
```sql
-- MMEX Debug SQL - Update --
-- This SQL script will ...
-- Please remember to ...
-- Do not use if ...
SELECT * FROM ACCOUNTLIST_V1;
```
```sql
-- MMEX Debug SQL - Read --
-- MMEX db version required 23
-- This SQL script will ...
-- Please remember to ...
-- Do not use if ...
SELECT * FROM ACCOUNTLIST_V1;
```
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1604)
> New features for mmdbg scripts

- .appveyor.yml
- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1606)
> always use fresh regenerated database files in CI

- util/sqlite2cpp.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1607)
> fix(sqlite2cpp): fix and update currencies update scripts

- src/customfieldeditdialog.cpp
- src/customfieldlistdialog.cpp
- src/customfieldlistdialog.h
- src/mmcustomdata.cpp
- src/mmcustomdata.h
- OK and Cancel buttons has replaced with Close button;
-  First field  "Description" has changed to  "Name";
- Default field disabled for all widgets except String
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1616)
> fix(#1585): check if data changed

- src/mmcustomdata.cpp
- src/mmcustomdata.h
- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1618)
> chore(#1585): show valued fields

- .appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1650)
> fix(AppVeyor): add force_update for nightly builds

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1654)
> chore(#1647): many fixes

- src/filtertransdialog.cpp
- src/mmcustomdata.cpp
- src/mmcustomdata.h
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1655)
> fix(#1585): improvements

- README.md
https://github.com/slodki/moneymanagerex/blob/new-badges/README.md
based on travis-ci/travis-ci#9579
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1653)
> New badges in README.md

- src/filtertransdialog.cpp
- src/filtertransdialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1656)
> fix(#1642): settings

- src/reports/summary.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1657)
> fix(#1656): montly grouping data

- src/filtertransdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1660)
> fix(#1658): wxRadioBox selection

- src/mmcheckingpanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1661)
> fix(#1624): sorting

- src/customfieldeditdialog.cpp
- src/customfieldeditdialog.h
- src/customfieldlistdialog.cpp
- src/mmcustomdata.cpp
- src/model/Model_CustomField.cpp
- src/model/Model_CustomField.h
Fixes:
- Massive Content Update - unclear function description, user is asked questions without meaning steps executed
- There is arbitrary precision forced for decimals (2 digits)
- Cleanup of fields when changing type
- Delete data when changing type
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1649)
> fix(#1585): various fix & improvements

- src/dbupgrade.cpp
fixing bug introduced in PR #1636
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1669)
> fix(#1667): correct table name from db v7

- src/db/DB_Table.h
- src/db/DB_Table_Currencyformats.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1671)
> fix(#1670): update submodule update missing in #1644

- util/sqlite2cpp.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1672)
> feat(sqlite2cpp): make script python ver 2 & 3 compatible

- src/db/DB_Upgrade.h
cosmetic fix for bug detected by @grumpy235 in #1670
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1673)
> fix(#1644): update db version in pragmas

- .mailmap
- util/list-authors.sh
requires bash, git, sort
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1685)
> feat(authors): add script to list commit authors with years

- CMakeLists.txt
- src/option.cpp
- src/reports/myusage.cpp
This fixes problems listed in #1204:
- report title changed to MMEX Usage Frequency
- unused code commented out
- chart size not limited
- time scale used for X axis
- ticks for Y axis as integers
- data placed on chart using date value
- line chart option removed
- all strings can be translated
- labels removed from X axis - ChartNew has problem with date labels on time scaled axis
- date format is using current locale - not using MMEX settings for date format or UI language selected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1688)
> refactor(myusage): redesign My Usage report

- contrib.txt
- docs/index.html
- docs/index_de.html
- docs/index_fr.html
- docs/index_hu.html
- docs/index_it.html
- docs/index_pl.html
- docs/index_sp.html
- license.txt
- src/aboutdialog.cpp
- src/billsdepositsdialog.h
- src/images_list.cpp
- src/import_export/qif_export.h
- src/import_export/qif_import.h
- src/import_export/qif_import_gui.h
- src/import_export/univcsvdialog.cpp
- src/maincurrencydialog.cpp
- src/mmSimpleDialogs.h
- src/mmTextCtrl.cpp
- src/mmTextCtrl.h
- src/mmTips.h
- src/mmframereport.cpp
- src/reports/budgetingperf.cpp
- src/reports/cashflow.cpp
- src/reports/incexpenses.cpp
- src/stockspanel.cpp
- src/util.cpp
- src/validators.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1680)
> fix(#1257): refresh copyright info

- src/model/Model_CustomField.cpp
fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1694)
> fix(#1693): null pointer exception

- src/model/Model_Payee.cpp
- src/model/Model_Payee.h
- src/payeedialog.cpp
- src/relocatepayeedialog.cpp
- src/relocatepayeedialog.h
this fixes #1696
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1702)
> UX improvement for Relocate Payee Dialog

- src/filtertransdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1713)
> fix(#1675): exception for save for unselected dropdown menu

- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1719)
> fix(#1718): new date mask DD/MM'YY

- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1720)
> fix(#1718): date parser update

- src/import_export/univcsvdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1721)
> chore(csv.import) missing account warning

- .travis.yml
- dockers/debian.buster.x86/Dockerfile
- dockers/debian.buster/Dockerfile
- dockers/ubuntu.cosmic.x86/Dockerfile
- dockers/ubuntu.cosmic/Dockerfile
This will fix #1331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1723)
> Support latest Ubuntu and Debian versions

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1725)
> chore(travis): update Xcode used to build Mac packages

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1731)
> refactor(travis): move nightly Travis jobs to separate branch

- po/nl_NL.po
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1739)
> fix(#1715): update monday name

- .appveyor.yml
- .travis.yml
- CMakeLists.txt
- src/versions.h.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1741)
> feat(cmake): autodetect mmex version from git tags

- INSTALL.md
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1743)
> fix(doc): Add snap usage instructions

- src/model/Model_Category.cpp
patch by @lonemadmax - thx!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1749)
> fix(#1738): fix idx value calculation

- docs/stocks_and_shares.html
- resources/home_page.htt
- src/constants.cpp
- src/general_report_manager.cpp
- src/mmframereport.cpp
- src/reports/forecast.cpp
- src/reports/htmlbuilder.cpp
- src/reports/myusage.cpp
- src/webapp.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1769)
> Fix html and add https to weblinks

- src/wizard_update.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1772)
> fix(#1771): don't overwrite with the same value

- .travis.yml
- INSTALL.md
- dockers/fedora.24/Dockerfile
- dockers/fedora.25/Dockerfile
- dockers/fedora.27/Dockerfile
- dockers/fedora.28/Dockerfile
- dockers/fedora.29/Dockerfile
- dockers/fedora/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1783)
> chore(travis): update Fedora builds

- po/pl.po
- src/currencydialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1787)
> fix(l10n): update pl translation

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1795)
> fix(travis): do not build unstable linux distributions

- .travis.yml
- dockers/debian.stretch.armhf/Dockerfile
- dockers/debian.stretch.x86/Dockerfile
- dockers/debian.stretch/Dockerfile
- dockers/ubuntu.xenial.x86/Dockerfile
- dockers/ubuntu.xenial/Dockerfile
- dockers/ubuntu.zesty.x86/Dockerfile
- dockers/ubuntu.zesty/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1799)
> fix(#1798): file tool is required for CPack to build deb with dependencies

- .travis.yml
- README.md
- snapcraft.yaml
Every commit will be published to the edge channel at https://snapcraft.io/mmex
Packages are build for amd64, i386, arm64, armhf architectures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1800)
> Use build.snapcraft.io to build and publish snap packages

- src/import_export/univcsvdialog.cpp
- src/mmcheckingpanel.cpp
- src/util.cpp
Also don't duplicate date formats every time CSV preset is selected at univcsvdialog - initialize once then only move selection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1797)
> Fix compile warnings

- CMakeLists.txt
- src/constants.cpp
- src/defs.h
- src/general_report_manager.cpp
- src/general_report_manager.h
- src/mmex.cpp
- src/mmframe.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1803)
> Clean sources from unused code and fix cmake (wxwidgets part)

- src/mmhomepagepanel.cpp
- src/mmhomepagepanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1794)
> fix(#1687): fix amount and add acc/payee to Upcoming Transactions applet

- .appveyor.yml
https://curl.haxx.se/changes.html#7_61_1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1812)
> chore(appveyor): update libcurl to 7.61.1 for windows packages

- .travis.yml
it will speed up the xcode builds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1823)
> feat(travis): use ccache for xcodebuild too

- INSTALL.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1827)
> fix(doc): update Mac part of INSTALL.md

- dockers/archlinux/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1830)
> fix(docker): fix archlinux image

- CMakeLists.txt
- util/FindwxWidgets.cmake
Using https://gitlab.kitware.com/cmake/cmake/merge_requests/2447
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1836)
> fix(cmake): use patched FindwxWidgets.cmake module

- po/de.po
The German translation is really messy in many points. I took some time to fix some of the translations. Sadly I had not enough time to go through all the translations, but this should already fix a lot.
If you have questions, feel free to ping me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1843)
> Fixing many German translations

- src/CMakeLists.txt
fixes bug in #1831
thx @grumpy235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1847)
> fix(#1846): define MMEX_WEBSERVER for optiondialog.cpp

- src/CMakeLists.txt
- src/constants.cpp
- src/constants.h
- src/model/Model_Usage.cpp
- src/util.cpp
- src/util.h
Mongoose will be used for webserver only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1851)
> refactor(SendStatsThread): replace mongoose with libcurl

- src/import_export/univcsvdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1855)
> fix(#1853): csv fields improvements

- po/mmex.pot
- po/ru.po
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1856)
> fix(i18n): pot update

- po/de.po
More optimizations and changes to the German translation - followup to #1843.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1858)
> cleanup(translations): adding and optimizing german translations

- src/filtertransdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1860)
> fix(#1777): account id cleaning

- src/db/DB_Upgrade.h
fixes #1872
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1873)
> fix(DB_upgrade): revert changes from 9f8f9b6

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1874)
> chore(travis): update to the latest image

- src/mmreportspanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1877)
> fix(#1861): choose proper date

- .appveyor.yml
- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1875)
> chore(appveyor): update libcurl to 7.62 for windows packages

- CMakeSettings.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1879)
> fix(#1878): Replace unsupported comment in json with simple field.

- CMakeSettings.json
fix last fix :sweat_smile:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1880)
> fix(Dev.Config): replace end prop separator

- src/reports/transactions.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1892)
> fix(#1732): total amount

- src/billsdepositsdialog.cpp
- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1893)
> fix(#1591): disable freq used button if list is empty

- .appveyor.yml
- .travis.yml
- src/option.cpp
- src/option.h
see [ChangeLog](https://raw.githubusercontent.com/wxWidgets/wxWidgets/v3.1.2/docs/changes.txt) for details
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1896)
> chore(ci): upgrade wxWidgets to 3.1.2 for Mac and Windows builds

- .travis.yml
- dockers/ubuntu.disco.x86/Dockerfile
- dockers/ubuntu.disco/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1901)
> chore(travis): build Ubuntu Disco packages

- .codacy.yml
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1907)
> add Codacy configuration and badge

- src/reports/transactions.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1910)
> fix(#1909): totals calculation

- po/mmex.pot
- po/ru.po
- src/assetdialog.cpp
- src/mmTips.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1911)
> chore(i18n): update

- po/it.po
- po/ru.po
from poeditor.com
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1914)
> chore(i18n): italian update

- src/reports/transactions.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1915)
> fix(#1909): speedup

- docs/index.html
- docs/js/back_to_top.js
- docs/js/toc.js
- docs/js/translations.js
- docs/js/translator.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1932)
> JavaScript and docs fixes

- .travis.yml
See https://validator.w3.org/nu/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1941)
> feat(travis): validate all HTML/CSS/SVG files using Nu HTML Checker

- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1952)
> fix(#1833): split negative amount

- src/mmhelppanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1955)
> fix(#1938): about:blank

- src/reports/categexp.cpp
- src/reports/forecast.cpp
- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/incexpenses.cpp
segmentShowStroke: false
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1962)
> fix(#1734): white border

- crowdin.yml
- src/mmex.cpp
- src/mmex.h
- src/mmframe.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1969)
> fix(#1950): private var

- src/mmreportspanel.cpp
- src/reports/cashflow.cpp
- src/reports/cashflow.h
- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/reportbase.cpp
- src/reports/reportbase.h
- src/reports/summarystocks.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1976)
> fix(#1975): cash flow diagram

- src/billsdepositsdialog.cpp
- src/categdialog.cpp
- src/categdialog.h
- src/filtertransdialog.cpp
- src/mmframe.cpp
- src/payeedialog.cpp
- src/relocatecategorydialog.cpp
- src/splitdetailsdialog.cpp
- src/transactionsupdatedialog.cpp
- src/transdialog.cpp
- src/usertransactionpanel.cpp
More improvements to #1942
- hide `Select` button when not used
- change `Cancel` button label depending on dialog context
- disable `Delete` button and display detailed reason in the tooltip
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1978)
> categdialog: UX improvements

- .remarkrc.yml
https://github.com/remarkjs/remark-lint/blob/master/doc/rules.md#list-of-rules
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1979)
> feat(codacy): add configuration for remark-lint

- po/pl_PL.po
- util/update-po-files.sh
@vomikan Crowdin updates can still downgrade existing translations (replace already translated string with an empty one).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1982)
> fix Polish translations

- INSTALL.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1994)
> Fixed minor grammar

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1993)
> fix(#1991): crowdin badges

- src/billsdepositsdialog.cpp
- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1998)
> fix(#1968): bold font for mandatory fields

- src/assetdialog.h
- src/assetspanel.cpp
- src/assetspanel.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1999)
> fix(#1950): public variables

- po/pt_BR.po
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2001)
> fix(i10n): update

- .eslintrc.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2022)
> fix(codacy): add eslint config

- .appveyor.yml
https://curl.haxx.se/changes.html#7_64_0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2021)
> chore(appveyor): update libcurl to 7.64 for windows packages

- docs/en/index.html
*This PR is a work in progress*
Initial work towards updating documentation with new features (from https://github.com/moneymanagerex/moneymanagerex/issues/1298)
Here is a list of features I hope to document in the next couple weeks, with accompanying forum posts and/or GitHub issues:
I may need more guidance on features involving SQL (e.g. https://github.com/moneymanagerex/moneymanagerex/issues/1883).
P.S. - this is my first contribution/pull request to an open source project, so I apologize about any mistakes/errors that I make in the process. Thank you in advance for your patience!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1936)
> fix(#1697): update index.html with new features

- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/payee.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2024)
> fix(#1980): payee pie chart colors

- po/de_DE.po
- po/he_IL.po
- po/hu_HU.po
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2029)
> fix(l10n): update

- dockers/archlinux/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2035)
> fix(docker): archlinux repo moved

- INSTALL.md
I've built 1.3.3 snap packages and published at Snap Store. This will allow to install and run MMEX stable on over 19 Linux distributions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2038)
> chore(doc): update INSTALL.md

- src/import_export/qif_import.h
- src/import_export/qif_import_gui.cpp
- src/import_export/qif_import_gui.h
- src/import_export/univcsvdialog.cpp
- src/import_export/univcsvdialog.h
- src/mmSimpleDialogs.cpp
- src/mmSimpleDialogs.h
- src/util.cpp
- src/util.h
#2033
#2032
#2016
#1963
#1700 ??
#1122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2040)
> fix(#1122): bulk fixes

- po/bg_BG.po
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2042)
> fix(l10n): bg

- src/mmhomepagepanel.cpp
Easy fix for #2044 using HTML title attribute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2049)
> fix(#2044): add transaction notes as tooltip

- .editorconfig
- .gitattributes
- .gitignore
- .snapcraft.yaml
- INSTALL.Ubuntu.md
#2038 related
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2039)
> feat(snap): build Linux snap packages

- src/mmframe.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2052)
> fix(#2041): fix invalid menu item type

- src/reports/cashflow.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2054)
> fix(#2047): daily rates

- src/filtertransdialog.cpp
For Notes an Number fileds
- Seching not empty values with '*' placeholder;
- Searching empty values;
- '?' also working.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2056)
> fix(#2043): matches and empty notes and number

- src/reports/categovertimeperf.cpp
- src/reports/categovertimeperf.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2055)
> fix(#2048): report parameters for future use

- src/budgetentrydialog.cpp
- src/budgetentrydialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2060)
> fix(#1708): none frequency

- src/billsdepositsdialog.cpp
- src/payeedialog.cpp
- src/payeedialog.h
+ chore(UI): more convenient payee chooser
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2059)
> fix(#2010): monthly default

- src/mmex.cpp
this will fix #2025 with workaround for #1899
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2053)
> fix(#2025): detailed info when translation is missing

- src/mmreportspanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2064)
> fix(#2063): next previous period single date

- src/reports/categovertimeperf.cpp
- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/incexpenses.cpp
- src/util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2067)
> fix(#2065): bar chart added

- src/reports/cashflow.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2071)
> fix(#2057): exchange rate

- src/budgetingpanel.cpp
- src/model/Model_Category.cpp
- src/model/Model_Category.h
- src/reports/budgetcategorysummary.cpp
- src/reports/budgetingperf.cpp
- src/reports/cashflow.cpp
- src/reports/categexp.cpp
- src/reports/categovertimeperf.cpp
- src/reports/incexpenses.cpp
- src/reports/payee.cpp
- src/reports/reportbase.cpp
- src/reports/reportbase.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2072)
> fix(#2069): accounts chooser

- src/assetspanel.cpp
- src/budgetentrydialog.cpp
- src/filtertransdialog.cpp
- src/import_export/qif_import_gui.cpp
- src/import_export/univcsvdialog.cpp
- src/import_export/univcsvdialog.h
- src/mmcheckingpanel.cpp
- src/mmcustomdata.h
- src/model/Model_Category.cpp
- src/paths.cpp
- src/payeedialog.cpp
- src/reports/payee.cpp
- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2074)
> Fix warnings

- src/model/Model.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2077)
> style(sources): use printf %zu for size_t

- src/general_report_manager.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2079)
> fix(#2066): splitter added

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2086)
> chore(travivs): update Xcode to 10.2 beta 2

- src/CMakeLists.txt
- src/assetdialog.cpp
- src/assetspanel.cpp
- src/import_export/univcsvdialog.cpp
- src/sharetransactiondialog.cpp
- src/transdialog.cpp
- src/util.cpp
- src/wx_compat.h
- util/update-po-files.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2103)
> fix(#2099): use wxGETTEXT_IN_CONTEXT() for abbreviations

- .appveyor.yml
- src/CMakeLists.txt
- src/billsdepositspanel.cpp
- src/constants.cpp
- src/maincurrencydialog.cpp
- src/mmframe.cpp
- src/optionsettingsview.cpp
- src/reports/budgetcategorysummary.cpp
- src/reports/htmlbuilder.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2104)
> fix(#2093): fix unicode string literals

- po/mmex.pot
- src/appstartdialog.cpp
- src/maincurrencydialog.cpp
- src/mmex.cpp
- src/option.cpp
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2107)
> fix(#1950): format

- .appveyor.yml
- BUILD.md
- src/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2110)
> fix(#1307): VS2013 is req for variadic templates

- .appveyor.yml
- src/CMakeLists.txt
- src/billsdepositspanel.cpp
- src/constants.cpp
- src/db/Table_Currencyformats.h
- src/maincurrencydialog.cpp
- src/mmframe.cpp
- src/optionsettingsview.cpp
- src/reports/budgetcategorysummary.cpp
- src/reports/htmlbuilder.cpp
- util/sqlite2cpp.py
Now CMake will use UTF-8 for /source-charset and /execution-charset to fix #2097
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2111)
> fix(#2097): force MSVC to use UTF-8

- docs/de/index.html
- docs/en/index.html
- docs/es/index.html
- docs/fr/index.html
- docs/hu/index.html
- docs/index.html
- docs/it/index.html
- docs/js/lang_menu.js
- docs/manual.css
- docs/pl/index.html
- docs/ru/index.html
Now it's possible to print User Manual from HTML sources with formatting adopted to printed media.
See [MMEX_User_Manual.pdf](https://github.com/moneymanagerex/moneymanagerex/files/2999686/MMEX_User_Manual.pdf)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2116)
> User Manual

- .appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2121)
> chore(appveyor): update libcurl to 7.64.1

- CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2122)
> fix(cmake): fix broken libcurl include dirs

- src/import_export/qif_export.cpp
- src/import_export/qif_export.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2124)
> fix(#2123): wrong %ld specifier in mmExportQIF

- src/import_export/univcsvdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2127)
> fix(#2126): hide digit delimiter

- src/import_export/univcsvdialog.cpp
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2128)
> fix(#2126): cleanup

- src/import_export/qif_export.cpp
- src/import_export/qif_import_gui.cpp
- src/import_export/univcsvdialog.cpp
- src/model/Model_Infotable.cpp
- src/model/Model_Infotable.h
- src/option.cpp
- src/optionsettingsgeneral.cpp
- src/reports/reportbase.cpp
- src/util.cpp
- src/util.h
test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2125)
> fix(#2098): locale short date fmt

- .snapcraft.yaml
- Makefile.in
- build/bakefiles/mmex.bkl
fix for 1.4.x in #1326 already
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2136)
> fixed translations for 1.3.x

- src/billsdepositspanel.cpp
- src/customfieldlistdialog.cpp
- src/general_report_manager.cpp
- src/import_export/qif_import_gui.cpp
- src/mmhomepagepanel.cpp
- src/reports/cashflow.cpp
per @milotype request
this is a partial solution for #2019
@vomikan could you check this at Crowdin?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2139)
> feat(i18n): add some wxPLURAL to sources

- po/mmex.pot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2140)
> fix(i10n): #2019

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/budgetyearentrydialog.cpp
- src/mmframe.cpp
- src/model/Model_Billsdeposits.cpp
- src/payeedialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2150)
> fix(#2026): refactoring and bulk fixes

- src/billsdepositspanel.cpp
- src/billsdepositspanel.h
- src/mmhomepagepanel.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Billsdeposits.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2144)
> fix(#2142) simplification

- src/billsdepositsdialog.cpp
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2151)
> fix(#2137): sizing

- src/transdialog.cpp
Reserve enough space for displaying all names
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2160)
> fix(#2157): calculate WeekDayNameMaxSize

- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
One cast is missing in #2156
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2161)
> fix(#2156): fix TABLE_CELL_SPAN

- src/billsdepositsdialog.cpp
- src/transdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2164)
> chore(dialogs): aligment

- src/billsdepositsdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2165)
> fix(#2154): trx date

- src/attachmentdialog.cpp
- src/stockdialog.cpp
- src/stockdialog.h
- src/stockspanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2167)
> fix(#1751): refactoring

- src/stockdialog.cpp
- src/stockdialog.h
- src/stockspanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2170)
> fix(#1751): price calculation

- po/mmex.pot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2171)
> fix(#1751): pot update

- src/general_report_manager.cpp
- src/general_report_manager.h
- src/mmreportspanel.h
- src/model/Model_Report.cpp
- src/model/Model_Report.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2173)
> fix(#2169): refactoring

- src/model/Model_Account.cpp
- src/stockdialog.cpp
- src/stockdialog.h
- src/stockspanel.cpp
- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2180)
> fix(#2178): empty name

- src/accountdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2181)
> fix(#1950): undefined behavior

- po/mmex.pot
- src/stockspanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2182)
> fix(#2168): gettext

- .appveyor.yml
- .travis.yml
- util/fake.py
- util/sqlite2cpp.py
- util/sqliteupgrade2cpp.py
fixes and optimization for `sqlite2cpp` and `sqliteupgrade2cpp` python scripts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2183)
> Python stable dates

- .travis.yml
- dockers/ubuntu.artful.x86/Dockerfile
- dockers/ubuntu.artful/Dockerfile
- dockers/ubuntu.eoan.armhf/Dockerfile
- dockers/ubuntu.eoan.x86/Dockerfile
- dockers/ubuntu.eoan/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2184)
> chore(docker): update Ubuntu images

- src/mmframe.cpp
- src/splitdetailsdialog.cpp
- src/splittransactionsdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2189)
> fix(#2188, #478, #2137): minor changes

- resources/money.xpm
- src/aboutdialog.cpp
- src/billsdepositsdialog.cpp
- src/billsdepositspanel.cpp
- src/dbcheck.cpp
- src/mmcustomdata.cpp
- src/mmex.cpp
- src/mmframereport.cpp
- src/mmhomepagepanel.cpp
- src/model/Model_Billsdeposits.cpp
- src/model/Model_Usage.cpp
- src/option.cpp
- src/reports/cashflow.cpp
- src/reports/categovertimeperf.cpp
- src/reports/reportbase.cpp
- src/reports/summary.cpp
- src/stockdialog.cpp
- src/stockspanel.cpp
- src/usertransactionpanel.cpp
- src/wizard_update.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2192)
> style(sources): fix Codacy and GCC warnings

- po/bg_BG.po
- po/cs_CZ.po
- po/de_DE.po
- po/el_GR.po
- po/es_ES.po
- po/fr_FR.po
- po/he_IL.po
- po/hr_HR.po
- po/hu_HU.po
- po/it_IT.po
- po/ja_JP.po
- po/lt_LT.po
- po/nl_NL.po
- po/pl_PL.po
- po/pt_BR.po
- po/ru_RU.po
- po/sk_SK.po
- po/sq_AL.po
- po/tr_TR.po
- po/zh_CN.po
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2194)
> fix(n10l): update

- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2201)
> fix(#1959): version

- src/general_report_manager.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2204)
> fix(#1928): try for ExecuteQuery

- src/filtertransdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2210)
> fix(#2209): subcategory name parser

- src/mmhomepagepanel.cpp
- src/stockspanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2211)
> fix(#2208): stock currency

- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2212)
> fix(#2202): news title

- docs/en/grm.html
Manual synced with #2173 to close #2169
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2216)
> fix(#2169): update GRM doc

- src/reports/categovertimeperf.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2219)
> fix(#2215): monthes

- src/import_export/univcsvdialog.cpp
- src/maincurrencydialog.cpp
- src/maincurrencydialog.h
- src/mmframe.cpp
- src/mmframe.h
- src/mmhomepagepanel.cpp
- src/stockspanel.cpp
- src/stockspanel.h
- src/util.cpp
- src/util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2237)
> Global rates update

- src/import_export/univcsvdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2239)
> fix(#227): amount delimiter issue

- po/mmex.pot
- src/assetspanel.cpp
- src/assetspanel.h
- src/billsdepositspanel.cpp
- src/billsdepositspanel.h
- src/constants.cpp
- src/constants.h
- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
- src/mmcustomdata.cpp
- src/optionsettingsview.cpp
- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2242)
> fix(#2240 #2238 #2235 #2234 #2233): multiple fixes

- src/payeedialog.cpp
- src/payeedialog.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2243)
> fix(#2226): payee rename issue

- po/mmex.pot
- src/optionsettingsattachment.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2244)
> fix(#2229): wxgettranslation missing

- src/accountdialog.cpp
- src/attachmentdialog.cpp
- src/attachmentdialog.h
- src/filtertransdialog.cpp
- src/filtertransdialog.h
- src/mmcheckingpanel.cpp
- src/model/Model_Attachment.cpp
- src/model/Model_Attachment.h
- src/optionsettingsattachment.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2254)
> fix(#2229 #2234): prefixes

- src/stockspanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2256)
> fix(#2255): currency value initialization

- src/assetspanel.cpp
- src/billsdepositspanel.cpp
- src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2267)
> small GUI fixes

- .appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2268)
> update submodules and dependencies

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2272)
> chore(travis): update Xcode to 11.0

- src/stockspanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2278)
> fix(#2255); totals

- .appveyor.yml
- .travis.yml
- BUILD.md
- CMakeLists.txt
- src/mmex.cpp
- util/FindwxWidgets.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2280)
> chore(wxwidgets): update to wxWidgets 3.1.3

- src/general_report_manager.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2283)
> fix(#2282) grm help page

- .travis.yml
- dockers/debian.bullseye.x86/Dockerfile
- dockers/debian.bullseye/Dockerfile
- dockers/el.8/Dockerfile
use Xcode 11.2 to build macOS package and add Debian Bullseye and CentOS 8 (el8) Linux packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2286)
> Update travis script

- src/mmframe.cpp
Fixes #2300
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2303)
> fix(#2300): Provide <Cmd> + <,> shortcut for options on Mac

- src/mmhomepagepanel.cpp
Fixes #2309.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2310)
> Save crypto wallets toggle state

- src/mmhomepagepanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2311)
> fix(#2308): simplification

- .appveyor.yml
- src/currencydialog.cpp
- src/mmTextCtrl.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2325)
> fix(#2320): empty decimal char

- po/el_GR.po
- po/tr_TR.po
- po/zh_CN.po
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2364)
> L10n master

- src/payeedialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2398)
> fix(v134): payee selection enhancement

- CMakeLists.txt
- src/constants.cpp
- src/payeedialog.cpp
- src/reports/htmlbuilder.cpp
- src/wizard_update.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2400)
> fix(#2395): responsive

- util/FindwxWidgets.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2438)
> Fix FindwxWidgets.cmake for VS2017

- src/mmframe.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2440)
> fix(#2435): Fix on wrong DB Version

- src/attachmentdialog.cpp
- src/attachmentdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2441)
> feat(#2224): Add attachments Drag&Drop

- src/webapp.cpp
@vomikan could you check if it solves #2443 for you as well?
Now it's working for me with russian characters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2452)
> fix(#2443): Convert to UTF8

- src/filtertransdialog.cpp
- src/mmframe.cpp
- src/mmhomepage.cpp
- src/mmreportspanel.cpp
- src/model/Model.h
- src/model/Model_Checking.cpp
- src/model/Model_Usage.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2463)
> fix(#2462): Fix UTF8

- src/mmframe.cpp
- src/webapp.cpp
- src/webappdialog.cpp
- src/webappdialog.h
Fixes #2413 and #2465 
It locks main MMEX window to don't let users open other windows and modal guarantee that it's always finished and closed before recurring transactions starts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2467)
> fix(#2413): New WebApp autostart

- src/billsdepositsdialog.cpp
- src/categdialog.cpp
- src/categdialog.h
- src/filtertransdialog.cpp
- src/mmframe.cpp
- src/payeedialog.cpp
- src/relocatecategorydialog.cpp
- src/splitdetailsdialog.cpp
- src/transdialog.cpp
- src/usertransactionpanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2486)
> fix(#2478): fix categories selection

- src/constants.cpp
- src/constants.h
- src/currencydialog.cpp
- src/currencydialog.h
- src/maincurrencydialog.cpp
- src/maincurrencydialog.h
- src/mmhomepage.cpp
- src/model/Model_CurrencyHistory.cpp
- src/option.cpp
- src/option.h
- src/optionsettingsgeneral.cpp
- src/optionsettingsgeneral.h
- src/reports/incexpenses.cpp
- src/reports/summary.cpp
- src/reports/summarystocks.cpp
- src/stockdialog.cpp
- src/util.cpp
@vomikan could you check if download rates it's still working (should be fine I've just changed save to DB)?
I was not able to test because my dev machine has some troubles and HTTP request goes timeout..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2490)
> fix(#2456): currency rates fixes

- src/constants.cpp
- src/optiondialog.cpp
- src/optiondialog.h
- src/optionsettingsattachment.cpp
- src/optionsettingsattachment.h
- src/optionsettingsbase.h
- src/optionsettingsgeneral.cpp
- src/optionsettingsgeneral.h
- src/optionsettingsmisc.cpp
- src/optionsettingsmisc.h
- src/optionsettingsnet.cpp
- src/optionsettingsnet.h
- src/optionsettingsview.cpp
- src/optionsettingsview.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2491)
> fix(#2488): attachments folder fix

- src/assetdialog.cpp
- src/mmreportspanel.cpp
- src/sharetransactiondialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2495)
> fix(#2484): definitive fix

- src/accountdialog.cpp
- src/accountdialog.h
- src/mmhomepage.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2504)
> feat(135): add WWW to HomePage

- src/maincurrencydialog.cpp
- src/model/Model_CurrencyHistory.cpp
- src/optionsettingsgeneral.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2515)
> fix(#2512): currency history improvement

- crowdin.yml
- src/maincurrencydialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2516)
> fix(#2512): hide unused panel

- po/bg_BG.po
- po/cs_CZ.po
- po/de_DE.po
- po/el_GR.po
- po/es_ES.po
- po/fr_FR.po
- po/he_IL.po
- po/hr_HR.po
- po/hu_HU.po
- po/it_IT.po
- po/ja_JP.po
- po/lt_LT.po
- po/mmex.pot
- po/nl_NL.po
- po/pl_PL.po
- po/pt_BR.po
- po/ru_RU.po
- po/sk_SK.po
- po/sq_AL.po
- po/sv_SE.po
- po/tr_TR.po
- po/zh_CN.po
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2519)
> fix(i10n): #2503

- src/aboutdialog.cpp
- src/appstartdialog.cpp
- src/attachmentdialog.cpp
- src/customfieldlistdialog.cpp
- src/import_export/qif_import_gui.cpp
- src/import_export/univcsvdialog.cpp
- src/mmframe.cpp
- src/optionsettingsview.cpp
- src/payeedialog.cpp
- src/stockdialog.cpp
- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2522)
> fix(i10n): #2520

- CMakeLists.txt
- src/constants.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2525)
> fix(v135): RC.2

- src/dbwrapper.cpp
- src/mmframe.cpp
- src/reports/bugreport.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2529)
> fix(i10n): fix strings

- src/attachmentdialog.cpp
- src/model/Model_Report.cpp
- src/reports/budgetcategorysummary.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2546)
> fix(#2544): cleanup

- src/categdialog.cpp
- src/categdialog.h
- src/filtertransdialog.cpp
- src/import_export/univcsvdialog.cpp
- src/mmTextCtrl.cpp
- src/optionsettingsattachment.cpp
- src/reports/budget.cpp
- src/reports/categexp.cpp
- src/reports/incexpenses.cpp
- src/reports/summary.cpp
- src/stockdialog.cpp
- src/usertransactionpanel.cpp
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2545)
> fix(135): cleanup

- src/attachmentdialog.cpp
- src/maincurrencydialog.cpp
- src/mmcheckingpanel.cpp
- src/mmframe.cpp
- src/mmframe.h
- src/mmframereport.cpp
- src/mmpanelbase.cpp
- src/model/Model_Attachment.cpp
- src/model/Model_Attachment.h
- src/optionsettingsmisc.cpp
- src/payeedialog.cpp
- src/splittransactionsdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2547)
> fix(135): more cleanup

- src/reports/summarystocks.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2551)
> fix(#2549): Stocks Performance Charts

- src/reports/summarystocks.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2558)
> fix(#2556): Stocks Performance Charts repeats tikers

- src/mmcheckingpanel.cpp
- src/reports/summarystocks.cpp
- src/stockspanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2559)
> fix(#2554): stock name update

- CMakeLists.txt
Using the file "/etc/arch-release" to detect an Arch distro.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2563)
> fix(CMakeList.txt): Fix to detect Arch Linux

- po/hr_HR.po
- src/mmframe.cpp
- src/mmframereport.cpp
- src/reports/budget.cpp
- src/reports/budgetcategorysummary.cpp
- src/reports/budgetingperf.cpp
- src/reports/cashflow.cpp
- src/reports/cashflow.h
- src/reports/categexp.cpp
- src/reports/forecast.cpp
- src/reports/incexpenses.cpp
- src/reports/myusage.cpp
- src/reports/payee.cpp
- src/reports/reportbase.cpp
- src/reports/reportbase.h
- src/reports/summary.cpp
- src/reports/summarystocks.cpp
fix(#2561): stage 1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2567)
> fix(#2566): #2565 budget issues 

- src/mmreportspanel.cpp
- src/reports/reportbase.cpp
- src/reports/reportbase.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2569)
> fix(#2561): restore

- src/reports/budget.cpp
- src/reports/budgetcategorysummary.cpp
- src/reports/budgetcategorysummary.h
- src/reports/budgetingperf.cpp
- src/reports/budgetingperf.h
- src/reports/bugreport.h
- src/reports/cashflow.cpp
- src/reports/cashflow.h
- src/reports/categexp.cpp
- src/reports/categexp.h
- src/reports/forecast.cpp
- src/reports/forecast.h
- src/reports/incexpenses.cpp
- src/reports/incexpenses.h
- src/reports/myusage.cpp
- src/reports/myusage.h
- src/reports/payee.cpp
- src/reports/payee.h
- src/reports/reportbase.cpp
- src/reports/reportbase.h
- src/reports/summary.cpp
- src/reports/summarystocks.cpp
- src/reports/summarystocks.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2572)
> fix(#2561): stage 2

- src/mmframereport.cpp
- src/mmreportspanel.cpp
- src/reports/reportbase.cpp
- src/reports/reportbase.h
- src/util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2574)
> fix(#2571): navigation tree settings ignore some collapsed items

- po/sv_SE.po
- src/util.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2576)
> fix(#2575): Panels not working anymore

- src/mmreportspanel.cpp
- src/reports/budget.cpp
- src/reports/budgetcategorysummary.cpp
- src/reports/budgetingperf.cpp
- src/reports/cashflow.cpp
- src/reports/categexp.cpp
- src/reports/forecast.cpp
- src/reports/incexpenses.cpp
- src/reports/myusage.cpp
- src/reports/payee.cpp
- src/reports/reportbase.cpp
- src/reports/reportbase.h
- src/reports/summary.cpp
- src/reports/summarystocks.cpp
- src/util.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2581)
> fix(#2561): reports settings save

- src/reports/cashflow.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2582)
> fix(#2579): add years for cash flow report labels

- src/mmTips.h
- src/stockspanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2584)
> fix(#2583): tips

- CMakeLists.txt
- docs/js/toc.js
- src/billsdepositsdialog.cpp
- src/constants.cpp
- src/option.cpp
true by default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2598)
> fix(#2512): lost all currency exchange rates

- src/budgetingpanel.cpp
- src/mmframereport.cpp
- src/mmhomepage.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2600)
> fix(#2599): Transaction Report doesn't work anymore

- contrib.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2607)
> fix(contributors): update

- src/mmex.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2609)
> fix(#2608): browser emulation

- CMakeLists.txt
- src/mmreportspanel.cpp
- src/reports/reportbase.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2612)
> fix(#2611): test

- src/mmreportspanel.cpp
- src/reports/htmlbuilder.cpp
- src/reports/reportbase.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2622)
> fix(#2621): graphs text encoding

- src/relocatepayeedialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2623)
> fix(#2620): Crash when selecting "Relocate Payee"

- src/import_export/qif_export.cpp
- src/import_export/qif_import_gui.cpp
- src/import_export/univcsvdialog.cpp
- src/option.cpp
- src/option.h
- src/optionsettingsgeneral.cpp
- src/stockdialog.cpp
- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2633)
> fix(#2632): Unable to Change Date Format

- src/currencydialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2638)
> fix(#2604): more validation for grp and decimal

- contrib.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2641)
> fix(l10n): update 

- src/webapp.cpp
- src/webapp.h
- src/webappdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2643)
> fix(#2639): add detailed errors

- CMakeLists.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2655)
> [Feat] Use MultiCore when building with VisualStudio

- src/import_export/univcsvdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2664)
> fix(#2662): export to CSV balance field format

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- src/import_export/univcsvdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2665)
> fix(git): bug report template

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2666)
> fix(git): templates

- po/mmex.pot
- src/mmframe.cpp
- src/stockspanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2667)
> fix(#2654): Zero number shares ico

- src/reports/categexp.cpp
- src/reports/categexp.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2668)
> fix(#2570): cleanup

- src/stockspanel.cpp
- src/stockspanel.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2678)
> fix(#2674): gain loss sort order

- .github/ISSUE_TEMPLATE/bug_report.md
- src/reports/mmDateRange.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2679)
> fix(#2673): Over Time start date

- .appveyor.yml
- .travis.yml
- BUILD.md
- CMakeLists.txt
- dockers/archlinux/Dockerfile
- src/constants.cpp
- util/Doxyfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2680)
> fix(1.3.6): upgrade

- src/mmex.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2700)
> fix(#2694): MMEX Window is off screen

- po/en_US.po
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2722)
> fix(en_us.po): Fixed spelling of Jewellery

- po/mmex.pot
- src/categdialog.cpp
- src/currencydialog.cpp
- src/currencydialog.h
- src/maincurrencydialog.cpp
- src/maincurrencydialog.h
- src/mmframereport.cpp
- src/mmreportspanel.cpp
- src/reports/cashflow.cpp
- src/reports/cashflow.h
- src/reports/categexp.cpp
- src/reports/forecast.cpp
- src/reports/incexpenses.cpp
- src/reports/myusage.cpp
- src/reports/payee.cpp
- src/reports/reportbase.cpp
- src/reports/reportbase.h
- src/reports/summary.cpp
- src/reports/summarystocks.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2734)
> fix(v1.3.6): #2730 #2573

- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/import_export/univcsvdialog.cpp
- src/model/Model_Category.cpp
- src/reports/categexp.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2737)
> fix(#2715): categories of splitted transactions

- src/constants.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2739)
> fix(#2738): mmex architecture

- .appveyor.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2741)
> fix(#2740): The application could not be started correctly (0x000007b)

- .appveyor.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2742)
> fix(#2740): test libcurl upgrade

- src/general_report_manager.cpp
- src/mmhomepagepanel.cpp
- src/mmhomepagepanel.h
- src/mmreportspanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2747)
> fix(#2746): attachments

- src/accountdialog.cpp
- src/mmhomepage.cpp
- src/mmhomepagepanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2756)
> fix(#2746): uri validator and handler

- src/currencydialog.cpp
- src/mmhomepage.cpp
- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2763)
> fix(#2761): enable more then 3 characters as curency symbol

- CMakeLists.txt
- po/mmex.pot
- po/ru_RU.po
- src/constants.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2764)
> fix(v1.3.6): release

- CMakeLists.txt
- src/constants.cpp
- src/reports/cashflow.cpp
- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2773)
> chore(v1.3.7): v1.3.7-beta.1

- src/budgetingpanel.cpp
- src/model/Model_Budget.cpp
- src/model/Model_Budget.h
- src/reports/budgetcategorysummary.cpp
- src/reports/budgetingperf.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2778)
> fix(#2775): map::at: key not found

- src/model/Model_Category.cpp
- src/optionsettingsview.cpp
- src/optionsettingsview.h
- src/reports/budgetingperf.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2779)
> fix(#2626): category: subcategory

- src/dbupgrade.cpp
- src/filtertransdialog.cpp
- src/import_export/univcsvdialog.cpp
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2786)
> fix(#2662): export to CSV amount field format

- resources/home_page.htt
- resources/master.css
- src/mmhomepage.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2788)
> chore(home): cosmetic changes

- resources/master.css
- src/mmhomepage.cpp
- src/reports/budgetcategorysummary.cpp
- src/reports/budgetingperf.cpp
- src/reports/cashflow.cpp
- src/reports/categexp.cpp
- src/reports/forecast.cpp
- src/reports/htmlbuilder.cpp
- src/reports/htmlbuilder.h
- src/reports/incexpenses.cpp
- src/reports/myusage.cpp
- src/reports/payee.cpp
- src/reports/summary.cpp
- src/reports/summarystocks.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2790)
> fix(home): stock widget fix for shadow container

- src/import_export/univcsvdialog.cpp
- src/reports/summarystocks.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2796)
> fix(#2785): CSV AMOUNT field value

- src/splitdetailsdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2797)
> fix(#2795): Split Deposit amount

- resources/home_page.htt
- src/mmhomepage.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2799)
> fix(#2798): Empty frame on home page

- src/mmhomepage.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2800)
> chore(#2448): Currency Exchange Rates

- src/attachmentdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2801)
> fix(#2759): Attach file without extension

- src/import_export/univcsvdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2804)
> fix(moneymanagerex#2785): CSV AMOUNT field value

- src/splitdetailsdialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2805)
> fix(moneymanagerex#2795): Split Deposit amount

- po/mmex.pot
- src/mmcheckingpanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2806)
> fix(#2257): Locked transaction to date

- po/mmex.pot
- src/reports/forecast.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2811)
> fix(i18n): typo fix

- CMakeLists.txt
- contrib.txt
- license.txt
- src/constants.cpp
> chore(ver.): 1.3.7-RC.1

- developers.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2815)
> docs(developers.html): added self

- src/aboutdialog.cpp
- src/aboutdialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2818)
> fix(#2817): first run user consent for stats

- src/reports/budgetingperf.cpp
- src/reports/budgetingperf.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2841)
> fix(#2830): Budget year name

- po/mmex.pot
- po/ru_RU.po
- src/CMakeLists.txt
- src/mmcheckingpanel.cpp
- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
- src/optionsettingsnet.cpp
- src/transactionsupdatedialog.cpp
- src/transactionsupdatedialog.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2842)
> fix(#2840): multi transactions update

- src/budgetingpanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2849)
> fix(#2846): Crash when viewing budget (under debug build)

- src/mmcheckingpanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2852)
> fix(#2847): Alert when deleting multiple transactions could be better

- src/mmcheckingpanel.cpp
- src/mmcombobox.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2853)
> fix(#2850): New Payee not possible when editing multiple transactions

- src/billsdepositsdialog.cpp
- src/billsdepositspanel.cpp
- src/model/Model_Budget.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2856)
> fix(#1549): Bi-weekly/monthly clarification

- po/en_US.po
- src/mmex.cpp
Have tested the multiple monitor setup on MacOS and seems to work fine. Only have single monitor setup on my Windows test rig but logic should work independently of OS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2857)
> Translation & Monitor location fix on startup

- src/mmex.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2859)
> fix(#2826): Need to cast as unsigned int

- src/mmex.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2861)
> fix(#2860): Detected memory leaks!

- src/mmcheckingpanel.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2862)
> FIX(#2844): Copy transactions with multi line notes

- CMakeLists.txt
- po/mmex.pot
- src/constants.cpp
- src/mmchecking_list.cpp
- src/mmchecking_list.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2864)
> fix(#2217): Multi-select for checking panel is broken

- resources/master.css
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2868)
> chore(css): hover shadow

- resources/master.css
- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2871)
> chore(css): hover div shift

- resources/home_page.htt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2875)
> fix(#2874): Common color scheme for widgets

- src/reports/htmlbuilder.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2876)
> fix(#1980): increased size of color palette

- resources/master.css
- src/reports/htmlbuilder.cpp
Works on MacOS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2879)
> What about this? 

- po/mmex.pot
- src/billsdepositsdialog.cpp
- src/billsdepositsdialog.h
- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
main changes:
- mark selected transactions  status by key press
- copy / past selected transactions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2884)
> fix(#2848): multi-transactions refactoring

- CMakeLists.txt
- contrib.txt
- src/CMakeLists.txt
- src/build.h
- src/constants.cpp
- src/constants.h
- src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2885)
> fix(#2881): build date/time in about.cpp

- src/reports/budgetingperf.cpp
- src/reports/reportbase.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2889)
> fix(#2829): account choice for budget performance

- src/constants.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2890)
> fix(moneymanagerex#2881): version refactoring

- src/model/Model_Checking.cpp
- src/model/Model_Checking.h
- src/transactionsupdatedialog.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2892)
> fix(#2851): stage 1

- contrib.txt
- license.txt
- src/aboutdialog.cpp
- src/mmframereport.cpp
- src/mmreportspanel.cpp
- src/reports/bugreport.h
- src/reports/transactions.cpp
- src/util.cpp
- src/util.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2895)
> chore(lic): simplification

- contrib.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2896)
> chore(contrib): at the request of the donator

- src/mmchecking_list.cpp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2897)
> fix(#2848): EVT_LEFT_DOWN

- src/mmchecking_list.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2900)
> fix(#2848): should be much more resilent now

- src/transactionsupdatedialog.cpp
- src/transactionsupdatedialog.h
Hopefully resolves the payee issue and fixes a category selection issue  (at least on Mac) that I found.
Tested on MacOS and Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2906)
> fix(#2850): payee/category processing changes

- src/mmchecking_list.cpp
- src/mmchecking_list.h
- src/mmcheckingpanel.cpp
- src/mmcheckingpanel.h
- src/mmframe.cpp
- src/transactionsupdatedialog.cpp
- src/transactionsupdatedialog.h
Bulk of work done... A few outstanding issues identified in https://github.com/moneymanagerex/moneymanagerex/issues/2893
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2907)
> fix(#2893): First pass for review
