moneymanagerex/moneymanagerex

src/assetdialog.cpp, src/assetdialog.h, src/billsdepositsdialog.cpp, src/billsdepositsdialog.h, src/budgetentrydialog.cpp, src/budgetentrydialog.h, src/currencydialog.cpp, src/maincurrencydialog.cpp, src/sharetransactiondialog.cpp, src/stockdialog.cpp, src/stockdialog.h, src/usertransactionpanel.cpp, src/usertransactionpanel.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4962)
=> fix(#4946):mmTextCtrl changes part 2

src/billsdepositsdialog.cpp, src/currencydialog.cpp, src/filtertransdialog.cpp, src/mmTextCtrl.cpp, src/splittransactionsdialog.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4966)
=> fix(#4946): event test

src/mmTextCtrl.cpp, src/mmcustomdata.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4967)
=> fix(#4946): focus event.Skip()

src/accountdialog.cpp, src/assetspanel.cpp, src/billsdepositsdialog.cpp, src/billsdepositspanel.cpp, src/filtertransdialog.cpp, src/filtertransdialog.h, src/reports/transactions.cpp, src/stocks_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4972)
=> fix(#4946): latest fixes

src/mmcustomdata.cpp, src/mmcustomdata.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4973)
=> fix(#4955): Decimal handling

src/mmcustomdata.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4974)
=> fix(#4955): zero decimal places fix

src/billsdepositspanel.cpp, src/mmchecking_list.cpp, src/mmchecking_list.h, src/mmcheckingpanel.cpp, src/mmcustomdata.cpp, src/model/Model_Checking.cpp, src/model/Model_Checking.h, src/model/Model_CustomField.cpp, src/model/Model_CustomField.h, src/reports/htmlbuilder.cpp, src/reports/transactions.cpp, src/util.cpp, src/util.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4979)
=> fix(#4868): custom field presentation

src/filtertrans.cpp, src/reports/htmlbuilder.cpp, src/reports/htmlbuilder.h, src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4980)
=> fix(#4868): trans report header alignment

src/stocks_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4981)
=> fix(#4978): skip col zero

src/filtertransdialog.cpp, src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4984)
=> fix(#4982): save advanced settings

src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4988)
=> fix(#4982): filter switch fix

src/mmchecking_list.cpp, src/mmcustomdata.cpp, src/mmcustomdata.h, src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4996)
=> fix(#4987): tidy

src/mmcustomdata.cpp, src/mmcustomdata.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5002)
=> fix(#4999): radio gaga

src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5004)
=> fix(#5003): date fixes

src/splittransactionsdialog.cpp, src/splittransactionsdialog.h, src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5006)
=> fix(#5005): split trans dialog test

src/splittransactionsdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5007)
=> fix(#5005): add/remove splir processing

src/splittransactionsdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5008)
=> fix(#5005): restrict scroll size

src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5009)
=> fix(#5000): fix

src/splittransactionsdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5010)
=> fix(#5005): header tidy

src/splittransactionsdialog.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5013)
=> fix(#5012): fix

contrib.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5029)
=> chore(contrib.txt): add sponsors

contrib.txt, po/de_DE.po
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5030)
=> hore(contrib.txt): add sponsors

.circleci/config.yml, src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5034)
=> fix(#5033): fix

src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5043)
=> fix(#5035): fix

src/categdialog.cpp, src/categdialog.h, src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5044)
=> fix(#4989): enhancement

src/model/Model_Stock.cpp, src/stockspanel.cpp
Fix crash on SHAREINFO not exists for CHECKINGID (issue: #5042)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5045)
=> Fix crash on SHAREINFO not exists for CHECKINGID

src/categdialog.cpp, src/categdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5048)
=> fix(#4989): show all fix

src/mmSimpleDialogs.cpp, src/optionsettingsview.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5052)
=> fix(#5051): tootip naming

src/mmchecking_list.cpp, src/mmchecking_list.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5053)
=> fix(#4690): sorting

src/assetspanel.cpp, src/categdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5060)
=> fix(#5059): min width

src/categdialog.cpp
Fixes issue #5056
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5061)
=> fix(#5056):Focus on newly added categories

src/categdialog.cpp, src/categdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5065)
=> fix(#4549): drag and drop

src/constants.cpp, src/constants.h, src/mmframereport.cpp, src/mmreportspanel.cpp, src/model/Model_Budget.cpp, src/model/Model_Budget.h, src/option.cpp, src/option.h, src/optionsettingsview.cpp, src/optionsettingsview.h, src/reports/budgetcategorysummary.cpp, src/reports/budgetingperf.cpp, src/reports/budgetingperf.h, src/reports/incexpenses.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5075)
=> fix(#4214): merge budgets

src/stockdialog.cpp, src/stocks_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5079)
=> fix(#4807): no crash

src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5087)
=> fix(#4954): category autoselection

src/assetdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5088)
=> fix(#4412): assetdialog crash fix

src/budgetingpanel.cpp, src/budgetingpanel.h, src/model/Model_Budget.cpp, src/model/Model_Category.cpp, src/reports/budget.cpp, src/reports/categexp.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5089)
=> fix(#5077): offset handling correction

contrib.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5094)
=> chore(contrib.txt): sponsors

.appveyor.yml, CMakeLists.txt, resources/home_page.htt, src/mmhomepage.cpp, src/mmhomepage.h, src/mmhomepagepanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5105)
=> fix(#5091): totals

src/budgetingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5107)
=> fix(#5106): add year in actuals calc

src/mmchecking_list.cpp, src/mmchecking_list.h, src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5110)
=> fix(#4690): 1st/2nd col sorting

resources/home_page.htt, src/mmhomepage.cpp, src/mmhomepage.h, src/mmhomepagepanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5112)
=> fix(#5111): asset widget detail

src/relocatecategorydialog.cpp, src/relocatecategorydialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5113)
=> fix(#5109): improve category search

docs/css/manual.css
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5118)
=> fix(#4545): color scheme detection

src/mmhomepage.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5119)
=> fix(#5111): omit if no assets

src/model/Model_Translink.h, src/stocks_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5126)
=> fix(#5125): Initialize avg share price

src/mmchecking_list.cpp, src/mmcheckingpanel.cpp, src/mmcheckingpanel.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5133)
=> fix(#5122): sort order fixes

src/reports/budget.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5140)
=> fix(#5137): monthly actuals range fix

src/filtertransdialog.cpp, src/filtertransdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5144)
=> fix(#4631): regex in notes filter

src/stockdialog.cpp, src/stockdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5143)
=> fix(#3554): share account for stock date

src/mmcustomdata.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5146)
=> fix(#5145): custom field saving

src/budgetentrydialog.cpp, src/budgetentrydialog.h, src/budgetingpanel.cpp, src/budgetingpanel.h, src/filtertransdialog.cpp, src/mmcustomdata.cpp, src/mmcustomdata.h, src/model/Model_Budget.cpp, src/model/Model_Budget.h, src/reports/budgetcategorysummary.cpp, src/reports/budgetingperf.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5148)
=> fix(#5147): custom field changed indication

src/billsdepositsdialog.cpp, src/mmSimpleDialogs.cpp, src/mmSimpleDialogs.h, src/model/Model_Payee.cpp, src/model/Model_Payee.h, src/payeedialog.cpp, src/payeedialog.h, src/transactionsupdatedialog.cpp, src/transdialog.cpp, src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5152)
=> fix(#4280): payee info fields

src/payeedialog.h
=> fix(#4280): linux build fix

src/model/Model_Payee.cpp, src/model/Model_Payee.h, src/payeedialog.cpp, src/payeedialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5154)
=> fix(#1390): inactive now hidden

src/accountdialog.cpp, src/payeedialog.cpp, src/util.cpp, src/util.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5155)
=> fix(#1390): tidy validation and error

src/reports/budget.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5157)
=> fix(#5137): month date end bug

src/billsdepositsdialog.cpp, src/categdialog.cpp, src/categdialog.h, src/mmSimpleDialogs.cpp, src/mmSimpleDialogs.h, src/mmframe.cpp, src/model/Model_Category.cpp, src/model/Model_Category.h, src/model/Model_Payee.cpp, src/payeedialog.cpp, src/relocatecategorydialog.cpp, src/relocatepayeedialog.cpp, src/splitdetailsdialog.cpp, src/splittransactionsdialog.cpp, src/transactionsupdatedialog.cpp, src/transdialog.cpp, src/usertransactionpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5162)
=> fix(#4730): hide categories

CMakeLists.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5169)
=> chore(CMakelists): beta2

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5173)
=> fix(#5170: check for existing cat/subcat

src/currencydialog.cpp, src/currencydialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5179)
=> fix(#1158): currency dialog improvements

.gitmodules, 3rd/CMakeLists.txt, README.md, src/CMakeLists.txt, src/images_list.cpp, src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5187)
=> fix(#3779): remove lunasvg dependency

contrib.txt, src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5194)
=> fix(#5193): skip range setup if not present

src/model/Model_Translink.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5199)
=> fix(#5198): Include "Transfer" asset transactions in asset value

src/mmframe.cpp, src/wizard_newdb.cpp, src/wizard_newdb.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5207)
=> fix(#5205): gracefully handle cancel

po/el_GR.po, po/it_IT.po, src/mmframe.cpp, src/wizard_newdb.cpp, src/wizard_newdb.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5208)
=> Get latest commits

src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5212)
=> fix(#5210): range dates fix

src/assetdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5224)
=> fix(#5222): refresh nav tree

CMakeLists.txt, contrib.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5227)
=> chore(v1.6.0): release

CMakeLists.txt, contrib.txt, src/assetdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5228)
=> v1.6.0 final

src/assetdialog.cpp, src/filtertransdialog.cpp, src/import_export/qif_export.cpp, src/import_export/univcsvdialog.cpp, src/mmchecking_list.cpp, src/mmcheckingpanel.cpp, src/mmhomepage.cpp, src/model/Model_Category.cpp, src/model/Model_Checking.cpp, src/model/Model_Checking.h, src/model/Model_Translink.cpp, src/reports/incexpenses.cpp, src/reports/payee.cpp, src/reports/transactions.cpp, src/sharetransactiondialog.cpp, src/transdialog.cpp, src/usertransactionpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5236)
=> feat(#2963): deleted transactions view

src/mmchecking_list.cpp, src/mmchecking_list.h, src/model/Model_Checking.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5246)
=> feat(#2963): Display DELETEDTIME in deleted transactions view

src/mmSimpleDialogs.cpp, src/mmSimpleDialogs.h, src/splittransactionsdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5252)
=> fix(#5250): check before add new split

src/mmchecking_list.cpp, src/model/Model_Checking.cpp, src/model/Model_Splittransaction.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5262)
=> fix(#5251): Notes concatenation

po/mmex.pot, src/filtertransdialog.cpp, src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5268)
=> fix(#5267): not deleted

src/transdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5271)
=> fix(#5251): typo

src/splittransactionsdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5274)
=> fix(#5273): total update

src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5277)
=> fix(#5276): notes panel change

src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5284)
=> fix(#5234): Category quick entry using ":"

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5286)
=> fix(#5211): toolbar status update

src/model/Model_Checking.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5288)
=> fix(#2963): correct payee name for deleted

src/billsdepositspanel.cpp, src/filtertransdialog.cpp, src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5295)
=> #5281 / #5292

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5301)
=> fix(#5298): Return to Home from Deleted Trans view

src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5309)
=> fix(#5234): fix Linux crash

po/zh_CN.po
Hi, I added some missing translations strings and optimized Simplified Chinese translations.
Refereces
1. [GitHub Docs_Receiving sponsorships through GitHub Sponsors](https://docs.github.com/cn/sponsors/receiving-sponsorships-through-github-sponsors)
2. [GitHub Docs_Commits](https://docs.github.com/cn/rest/commits)
3. [GitHub Docs_About branches](url)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5313)
=> Updated Simplified Chinese translations

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5319)
=> fix(#5299): Select Transaction Report node when toolbar button is selected

src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5321)
=> fix(#5320): notes fix

src/assetdialog.cpp, src/sharetransactiondialog.cpp, src/usertransactionpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5325)
=> fix(#5324): check for date < account opening

src/billsdepositsdialog.cpp, src/filtertransdialog.cpp, src/payeedialog.cpp, src/relocatecategorydialog.cpp, src/splittransactionsdialog.cpp, src/transactionsupdatedialog.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5335)
=> fix(#5132): Another performance improvement

src/model/Model_Category.cpp, src/model/Model_Payee.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5336)
=> fix(#5296): fix for DELETEDTIME = NULL

CMakeLists.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5337)
=> chore(CMakeLists.txt): Beta.2

src/mmframe.cpp, src/model/Model_Translink.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5340)
=> fix(#5339): crash fix for asset/stock deletion

src/model/Model_Asset.cpp, src/model/Model_Asset.h, src/reports/summary.cpp, src/reports/summary.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5341)
=> fix(#5197): add assets to summary report

CMakeLists.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5342)
=> chore(v1.6.1): v1.6.1

CMakeLists.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5345)
=> chore(v1.6.2): starting base for v1.6.2

src/model/Model_Asset.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5349)
=> fix(#5346): fix current value when no asset transactions

3rd/CMakeLists.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5354)
=> fix(#5302): Non-win build options

README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5357)
=> fix(#5356): fix linux/mac build status in README

src/model/Model_Stock.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5358)
=> fix(#5352): fix crash on stock balance calc

src/reports/categexp.cpp, src/reports/categexp.h
Fix C-style casting on categexp report
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5362)
=> feat(#1477): nested categories

src/transactionsupdatedialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5366)
=> fix(#5364): multi-transaction edit

src/assetspanel.cpp, src/billsdepositspanel.cpp, src/budgetingpanel.cpp, src/mmchecking_list.cpp, src/mmpanelbase.cpp, src/mmpanelbase.h, src/stocks_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5365)
=> fix(#5360): icon text

src/categdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5369)
=> fix(#1477): fix category drag & drop

src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5371)
=> fix(#5370): reconciled check

src/reports/categexp.cpp, src/reports/myusage.cpp, src/reports/payee.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5374)
=> fix(#4295): sort pie charts

src/reports/categexp.cpp, src/reports/myusage.cpp, src/reports/payee.cpp
auto not supported for lambda on C++ version used for Mac/Linux builds... Perhaps look at updating build at a later date.
See: https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/217/workflows/52b9b5bb-6ba5-4156-b1e0-322a4aefc530/jobs/216
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5376)
=> fix(#4295): build on Mac/Linux

src/splittransactionsdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5379)
=> fix(#5377): Check data prior to add/remove

src/mmcustomdata.cpp, src/optionsettingsattachment.cpp, src/optionsettingsgeneral.cpp, src/optionsettingshome.cpp, src/optionsettingsmisc.cpp, src/optionsettingsnet.cpp, src/optionsettingsview.cpp, src/splittransactionsdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5385)
=> fix(#5382): scroll test

src/model/Model_Asset.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5388)
=> fix(#5381): apply forex rate to asset curr value

CMakeLists.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5389)
=> chore(CMakeLists.txt): v1.6.2 Beta 1

src/filtertransdialog.cpp, src/filtertransdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5398)
=> fix(#5392): fix special chars in trans report categ filter

src/accountdialog.cpp, src/import_export/qif_import_gui.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5409)
=> fix(#5334): initial date

contrib.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5418)
=> contrib.txt

src/maincurrencydialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5420)
=> fix(#5416): symbol->code

src/mmex.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5421)
=> fix(#5386): memory leak fix

src/optiondialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5423)
=> fix(#5415): text alignment in options dialog

CMakeLists.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5440)
=> chore(CMakeLists.txt): v1.6.2

src/categdialog.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5445)
=> fix(#5444): disable selection of hidden categories

src/reports/cashflow.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5446)
=> fix(#5437): exclude void txns from cashflow report

src/mmex.cpp, src/mmex.h, src/mmframe.cpp, src/mmframe.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5450)
=> fix(#5386): shared pointer

src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5453)
=> fix(#5428): tidy formatting

po/mmex.pot, src/attachmentdialog.cpp, src/categdialog.cpp, src/dbupgrade.cpp, src/import_export/export.cpp, src/mmTips.h, src/mmframe.cpp, src/model/Model_Billsdeposits.cpp, src/optionsettingsattachment.cpp, src/payeedialog.cpp, src/reports/bugreport.h, src/webapp.cpp, src/wizard_newaccount.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5477)
=> fix(#5462): arrows

license.txt, po/mmex.pot, src/optionsettingsmisc.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5485)
=> fix(#5468): labels

src/import_export/qif_import_gui.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5487)
=> fix(#5474): memo split

src/reports/forecast.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5494)
=> fix(#5489): forecast report currency conversion

src/assetdialog.cpp, src/attachmentdialog.cpp, src/attachmentdialog.h, src/billsdepositsdialog.cpp, src/stockdialog.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5493)
=> fix(#5466): attachments on recurring txns

contrib.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5513)
=> chore(contrib.txt): new sponsors

src/filtertransdialog.cpp, src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5515)
=> fix(#4698): txn filter for split categories

src/model/Model_Checking.cpp, src/model/Model_Checking.h, src/option.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5519)
=> fix(#5467): deletedtime

src/model/Model_Checking.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5523)
=> fix(#5467): simplification

src/model/Model_Checking.cpp, src/model/Model_Checking.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5526)
=> fix(#5521): update lastupdatedtime on trx save

src/model/Model_Report.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5535)
=> fix(#5530) toutc removed

src/import_export/qif_export.cpp, src/import_export/qif_export.h, src/mmframe.cpp, src/optionsettingsmisc.cpp, src/optionsettingsnet.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5540)
=> fix(chore): cleanup

src/mmreportspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5548)
=> fix(#5514): apply date range filter to linked reports

src/attachmentdialog.cpp, src/mmcustomdata.cpp, src/model/Model_Checking.cpp, src/model/Model_Checking.h, src/model/Model_Shareinfo.cpp, src/model/Model_Splittransaction.cpp, src/sharetransactiondialog.cpp, src/usertransactionpanel.cpp, src/usertransactionpanel.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5547)
=> fix(#5521): LASTUPDATEDTIME for attachments + refactor

po/mmex.pot, src/import_export/qif_import_gui.cpp, src/model/Model_Setting.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5558)
=> fix(#4341): empty file name

src/transdialog.cpp
=> fix(#5571): refactoring

src/mmreportspanel.cpp
Added a check if a date range is included in the report, otherwise GetClientData throws a debug assertion fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5575)
=> fix(#5514): date range filter

src/mmframe.cpp, src/mmframe.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5578)
=> fix(#5576): sync on start

src/splittransactionsdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5584)
=> fix(#5559): performance improvement

src/assetdialog.cpp, src/assetdialog.h, src/assetspanel.cpp, src/mmframe.cpp, src/mmframe.h, src/model/Model_Splittransaction.cpp, src/reports/myusage.cpp, src/stockdialog.h, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5585)
=> Some Cleanups

src/constants.cpp, src/mmframe.cpp, src/mmframe.h
This reverts commit 0106b5df32f80c410629d84214a52250c7db7eeb.
=> Revert "fix(twitter): gone"

src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5603)
=> fix(#5602): new date mask

src/categdialog.cpp, src/categdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5609)
=> fix(#5606): category dialog filter

src/categdialog.cpp, src/categdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5610)
=> fix(#5606): refactor for performance

src/categdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5612)
=> fix(#5606): match category full name

src/mmchecking_list.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5616)
=> fix(#5615): ignore shift button

po/mmex.pot, src/optionsettingsgeneral.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5635)
=> fix(#5626): maybe it will help

src/billsdepositsdialog.cpp, src/billsdepositspanel.cpp, src/mmhomepage.cpp, src/model/Model_Billsdeposits.cpp, src/reports/cashflow.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5639)
=> fix(#5614): recurring transaction execute options

src/import_export/univcsvdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5646)
=> fix(#5640): tab

src/mmframe.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5647)
=> fix(#5626): labels

docs/ru_RU/index.html, po/mmex.pot, src/constants.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5651)
=> fix(#5650): ellipsis

po/mmex.pot, src/appstartdialog.cpp, src/general_report_manager.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5652)
=> fix(#5636): fix

src/model/Model_Budget.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5664)
=> fix(#5573): fix budget summary report crash

src/mmchecking_list.cpp, src/model/Model_Checking.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5665)
=> fix(#5630): refactor

src/relocatecategorydialog.cpp, src/relocatepayeedialog.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5672)
=> fix(#5668): resizeable dialogs

src/billsdepositsdialog.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5677)
=> fix(#5668): fix min dialog width

src/transdialog.cpp, src/usertransactionpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5678)
=> fix(#5670): ignore transfers for last payee selection

src/filtertransdialog.cpp, src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5693)
=> fix(#2361): report tx rate

src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5694)
=> fix(#2361): only xfers

src/billsdepositsdialog.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5696)
=> fix(#5668): fix hidden split button

src/assetdialog.cpp, src/assetspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5703)
=> fix(#5683): crash fix

src/billsdepositsdialog.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5701)
=> fix(#5668): fix hidden buttons

src/mmchecking_list.cpp, src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5699)
=> fix(#5698): format timestamps

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5710)
=> fix(#5709): app title

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5717)
=> fix(#5709): simplification

src/aboutdialog.cpp, src/appstartdialog.cpp
https://github.com/moneymanagerex/moneymanagerex/issues/5709#issuecomment-1447836335
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5718)
=> fix(https://github.com/moneymanagerex/moneymanagerex/issues/5709#issuecomment-1447836335): simplification

src/appstartdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5726)
=> fix(#5709): fix dialog width

src/relocatecategorydialog.cpp, src/relocatecategorydialog.h, src/relocatepayeedialog.cpp, src/relocatepayeedialog.h, src/transdialog.cpp, src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5733)
=> fix(#5668): save dialog size

README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5728)
=> Unlimited nested multi-level category support, screenshots heading, supported platforms, etc.

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5745)
=> fix(#5367): debug mode for mmdbg

src/appstartdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5742)
=> fix(#5727): translate button text on Linux

po/mmex.pot, src/appstartdialog.cpp, src/constants.cpp, src/constants.h, src/mmSimpleDialogs.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5746)
=> fix(#5727): single chooser button labels

src/import_export/qif_import_gui.cpp, src/payeedialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5749)
=> fix(#3148): utf8 support

src/payeedialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5753)
=> feat(#3148): use bitmap arrow buttons

src/filtertransdialog.cpp, src/filtertransdialog.h, src/mmchecking_list.cpp, src/mmcheckingpanel.cpp, src/model/Model_Checking.cpp, src/model/Model_Checking.h, src/reports/transactions.cpp
implements enhancement #5465 and fixes #5752
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5756)
=> fix(#5465): apply filters to splits & display matches

src/filtertransdialog.cpp, src/mmcheckingpanel.cpp, src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5758)
=> fix(#5465): check main note in splits

src/import_export/univcsvdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5761)
=> feat(#3148): remove row limit of CSV import preview

src/mmframe.cpp, src/optionsettingsmisc.cpp, src/optionsettingsmisc.h, src/stockdialog.cpp
#5759 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5762)
=> fix(#5759): update stock prices on startup

src/import_export/univcsvdialog.cpp, src/payeedialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5765)
=> fix(#3148): payee debug assert & crash fix

src/mmchecking_list.cpp, src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5766)
=> fix(#5465): correct extra transaction data

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5767)
=> fix(#5759): fix when db filename passed as param

src/import_export/univcsvdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5773)
=> fix(#5772): use user defined type as deposit

src/model/Model_Currency.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5775)
=> fix(#5774): reset locale on database change

src/stocks_list.cpp
#1691 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5788)
=> fix(#1691): disable stock web page if no selection

src/import_export/qif_import_gui.cpp, src/import_export/qif_import_gui.h, src/import_export/univcsvdialog.cpp, src/import_export/univcsvdialog.h, src/mmframe.cpp, src/mmframe.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5789)
=>  fix(#3684): drag and drop file import 

src/import_export/univcsvdialog.cpp, src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5793)
=> fix(#3684): allow drop files in All Transactions

src/import_export/univcsvdialog.cpp, src/import_export/univcsvdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5796)
=> fix(#5790): csv presets by name & acct defaults

src/import_export/univcsvdialog.cpp, src/import_export/univcsvdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5799)
=> fix(#5790): layout change & other fixes

.github/CONTRIBUTING.md, src/themes.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5811)
=> fix #5810 theme extention in theme import dialog

src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5804)
=> fix(#5792): add date format DD-Mon-YY

src/import_export/univcsvdialog.cpp, src/import_export/univcsvdialog.h, src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5803)
=> fix(#5790): persistent column widths

contrib.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5816)
=> chore(contrib.txt): new sponsor

src/filtertransdialog.cpp, src/filtertransdialog.h, src/mmcheckingpanel.cpp, src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5815)
=> fix(#5813): filter splits by all txn fields

src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5818)
=> fix(#5808): fix dialog size for linux

src/import_export/univcsvdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5819)
=> fix(#5790): minor cosmetic fixes

src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5820)
=> fix(#5817): don't store acct in checking panel txn filter

src/filtertransdialog.cpp, src/filtertransdialog.h, src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5821)
=> fix(#5812): txn report option combine splits

src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5826)
=> fix(#5809): fix combobox button disabled on linux

src/stockspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5827)
=>  fix(#5823): view stock transaction dialog layout 

src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5840)
=> fix(#5832): fix min width custom field panel

src/model/Model_Translink.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5844)
=> fix(#5843): sort records by date for stock valuation

src/mmhomepage.cpp, src/model/Model_Stock.cpp, src/model/Model_Stock.h, src/reports/summarystocks.cpp, src/reports/summarystocks.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5845)
=> fix(#5833): fix FX gain/loss calculation in stock valuation

src/stockspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5849)
=> fix(#5823): sort stock transactions by date

src/mmhomepage.cpp, src/mmhomepagepanel.cpp
…worth
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5850)
=> fix(#5834): include asset and share account balances in homepage net worth

src/platfdep_unix.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5863)
=> fix(#5861): detect dark mode

src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5871)
=> fix(#5870): no ssl check

src/constants.cpp, src/constants.h, src/wizard_update.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5872)
=> fix(#5870): speedup

contrib.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5878)
=> chore(contrib.txt): Added sponsor

src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5888)
=> fix txn filter dialog width

src/budgetentrydialog.cpp, src/model/Model_Category.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5895)
=> fix(#5892): display full name and remove subcategory

po/mmex.pot, src/constants.cpp, src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5898)
=> fix(#5894): switch to yahoo v6 api

src/budgetentrydialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5900)
=> fix(#5892): use unicode ellipsis char

src/maincurrencydialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5902)
=> fix(#5901): autosize columns

src/maincurrencydialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5905)
=> fix(#5901): autosize date & price columns

src/reports/htmlbuilder.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5918)
=> fix(#5904): reformat pie chart legend

src/model/Model_Currency.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5933)
=> fix(#5852): crash fix

src/constants.cpp, src/util.cpp, src/util.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5958)
=> fix(#5894): Yahoo Finance v7 API fix

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5957)
=> fix(#5948): check db is open

src/mmframe.cpp, src/mmframe.h, src/util.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5959)
=> fix(#5857): txn report crash fix

src/relocatecategorydialog.cpp, src/relocatepayeedialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5956)
=> fix(#5938): fix dialog minimum size

src/import_export/univcsvdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5955)
=> fix(#5947): fix dup subcategory creation

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5961)
=> fix(#5857): reselect under previous parent when possible

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5968)
=> fix(#5966): select root only on home page

src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5965)
=> fix linux build

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5974)
=> fix(#5973): respect hide share accounts in favorites

src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5986)
=> fix(#5975): fix payee arrow on stock/asset withdrawal txn

po/he_IL.po, po/mmex.pot, src/util.cpp
https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.6.3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5995)
=> fix(#4058): hyperlink for closed issues

src/filtertransdialog.cpp, src/filtertransdialog.h, src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6001)
=> fix(#5885): transaction filter dialog height

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6011)
=> fix(#3684): refresh checking panel data after drag & drop import

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6014)
=> fix(#6013): crash fix

resources/dist/linux/share/mime/packages/org.moneymanagerex.MMEX.mime.xml
Fixes: https://github.com/moneymanagerex/moneymanagerex/issues/1254
```
$ cp resources/dist/linux/share/mime/packages/org.moneymanagerex.MMEX.mime.xml ~/.local/share/mime/packages/org.moneymanagerex.MMEX.mime.xml
$ update-mime-database ~/.local/share/mime
$ xdg-mime query filetype mmexdb.mmb 
application/x-mmb
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6021)
=> Improve mimetypes coverage on Linux

3rd/CMakeLists.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6023)
=> fix(#5963): add arm64

3rd/CMakeLists.txt
Fixes https://github.com/moneymanagerex/moneymanagerex/issues/5953 and regression from https://github.com/moneymanagerex/moneymanagerex/pull/6017
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6024)
=> Enable compiler flags for any target that is not ARM Linux

CMakeLists.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6028)
=> Use cmake's built-in host info detection when available

contrib.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6031)
=> chore(contrib.txt): sponsor

src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6052)
=> fix(#6040): fix stock refresh for GDPR countries

src/model/Model_Budget.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6053)
=> fix(#5464): fix budget override in perf report

src/import_export/univcsvdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6067)
=> fix(#6064): reinit

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6081)
=> fix(#6079): add integrity check during database debug

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6087)
=> fix(#6079): switch to FindWindow

src/assetspanel.h, src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6090)
=> fix(#6089): asset crash fix

src/model/Model_Tag.cpp, src/tagdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6092)
=> tag dialog fixes

src/tagdialog.cpp, src/tagdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6093)
=> tagdialog refactor & minor fixes

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6094)
=> fix(#6079): add program icon to db check dlg

src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6097)
=> fix(#6069): extend checking panel search field

src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6099)
=> fix(#5439): various fixes for tagTextCtrl

src/mmhomepage.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6106)
=> fix(#6102): exclude deleted txns from homepage counts

src/optionsettingshome.cpp, src/optionsettingshome.h, src/reports/mmDateRange.cpp, src/reports/mmDateRange.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6104)
=> fix(#6072): add "Last N Days" to home panel options

src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6107)
=> fix(#6071): display 0 amount txns as withdrawal/deposit according to TRANSCODE

src/assetspanel.cpp, src/attachmentdialog.cpp, src/budgetingpanel.cpp, src/categdialog.cpp, src/images_list.cpp, src/import_export/qif_import_gui.cpp, src/import_export/univcsvdialog.cpp, src/maincurrencydialog.cpp, src/mmTips.h, src/mmcheckingpanel.cpp, src/mmcustomdata.cpp, src/mmframe.cpp, src/model/Model_Attachment.cpp, src/model/Model_Billsdeposits.cpp, src/model/Model_Report.cpp, src/payeedialog.cpp, src/relocatecategorydialog.cpp, src/relocatecategorydialog.h, src/relocatepayeedialog.cpp, src/relocatepayeedialog.h, src/relocatetagdialog.cpp, src/relocatetagdialog.h, src/reports/htmlbuilder.cpp, src/stockspanel.cpp, src/tagdialog.cpp, src/util.cpp, src/wizard_newdb.cpp
https://github.com/moneymanagerex/moneymanagerex/issues/5439#issuecomment-1636655697 point 1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6113)
Closes https://github.com/moneymanagerex/moneymanagerex/issues/6063
Closes https://github.com/moneymanagerex/moneymanagerex/issues/5881
Thank you
=> `relocate`→`merge`; `favourite`→`favorite`; Strings ordering `%s`→`%1$s`, `%i`→`%1$i`; Remove `Dialog` and `Window` from source strings

src/mmSimpleDialogs.cpp, src/mmframe.cpp, src/model/Model_Attachment.cpp, src/util.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6118)
=> fix(#6113): fix compile errors

src/billsdepositsdialog.cpp, src/mmSimpleDialogs.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6119)
=> fix(#5439): handle numpad enter

src/import_export/univcsvdialog.cpp, src/import_export/univcsvdialog.h, src/mmSimpleDialogs.h, src/util.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6120)
=> fix(#6057): case insensitive payee/categ search

po/mmex.pot, src/images_list.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6130)
=> fix(#6063): positional parameter required

src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6144)
=> fix(#6140): MacOS handling fix

src/mmSimpleDialogs.cpp, src/mmSimpleDialogs.h, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6145)
=> feat(#5439): tag dropdown & fixes

src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6149)
=> fix(#6140): tidy - remove debug code

src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6147)
=> feat(#5439): use native text control as panel background

src/billsdepositsdialog.cpp, src/filtertransdialog.cpp, src/filtertransdialog.h, src/mmSimpleDialogs.cpp, src/mmSimpleDialogs.h, src/mmchecking_list.cpp, src/mmcheckingpanel.cpp, src/model/Model_Checking.cpp, src/reports/transactions.cpp, src/splittransactionsdialog.cpp, src/transactionsupdatedialog.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6160)
=> fix(#5439): fix tag filtering

po/CMakeLists.txt, po/common.po, src/appstartdialog.cpp, src/mmex.cpp, src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6172)
=> fix(#5410): common translations of UI languages

src/appstartdialog.cpp, src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6174)
=> fix(#5410): remove duplicate language

po/common.po
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6176)
=> Homogenize with Thunderbird list

po/mmex.pot, src/filtertransdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6186)
=> fix(#6183): utf-8 issue

src/billsdepositsdialog.cpp, src/mmSimpleDialogs.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6187)
=> Redudancies and possible dangling references removed 

src/billsdepositspanel.cpp, src/budgetingpanel.cpp, src/budgetingpanel.h, src/filtertransdialog.cpp, src/filtertransdialog.h, src/mmcheckingpanel.cpp, src/mmcheckingpanel.h, src/mmpanelbase.cpp, src/mmpanelbase.h, src/mmreportspanel.cpp, src/mmreportspanel.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6206)
=> Fixed warning and some cleanups

src/tagdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6219)
=> fix(#5439): fix tag dialog layout for linux & mac

src/filtertransdialog.cpp, src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6221)
=> fix(#5439): fix tooltip for tag control

src/general_report_manager.cpp, src/general_report_manager.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6224)
=> fix(#6185): right click anywhere in GRM

src/mmchecking_list.cpp, src/mmchecking_list.h, src/mmframe.cpp, src/mmframe.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6223)
=> feat(#4232): add "Find all transactions with..." to context menu

src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6227)
=> fix(#4232): fix refresh on all transactions view

.appveyor.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6238)
=> fix(#5989): wx3.2.3

.circleci/config.yml, org.moneymanagerex.MMEX.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6239)
=> Add flatpak CI build target

.circleci/config.yml, org.moneymanagerex.MMEX.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6249)
=> fix(#6246): CircleCI just builds flatpak now

NEWS
Changelog lines derived from the following output:
```
$ gh issue list --repo="moneymanagerex/moneymanagerex" --limit=100 --state="closed" --milestone="v1.7.0" 
Showing 35 of 35 issues in moneymanagerex/moneymanagerex that match your search
#6212  Transaction Report crashes if category starts with `+`                                                               bug, fixed                                about 15 days ago
#6203  Refresh Stock Prices from Yahoo error "url using bad/illegal format or missing url" in version 1.7.0 beta.1          bug, duplicate                            about 27 days ago
#6201 …
```
=> Add milestones for v1.7.0 Beta and v1.6.4 to NEWS

src/mmex.cpp
refer #6256  for detail clang_format configuration
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6260)
=> follow clang_format and refine c style cast to static_cast

src/constants.cpp, src/model/Model_Usage.cpp
to address #6247
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6262)
=> init GA4 integration

src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6264)
=> apply clang-format for src/filtertransdialog.cpp

src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6265)
=> Show system locale and user application language in About dialog

po/common.po
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6268)
=> fix(#6266): translate sl-SI in language list

po/en_US.po, po/mmex.pot, src/util.cpp
Addresses https://github.com/moneymanagerex/moneymanagerex/issues/5213
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6267)
=> Add english translation for Locale and User Interface Language strings

src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6273)
=> fix(#5215): center txn filter dialog

src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6272)
=> Move desktop_environment string into Linux ifdef block

src/attachmentdialog.cpp, src/mmframe.cpp, src/wizard_update.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6271)
=> String updates

src/model/Model_Usage.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6277)
=> send page_view.engagement_time_msec to GA4

src/constants.cpp, src/constants.h, src/model/Model_Usage.cpp, src/model/Model_Usage.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6278)
=> use amplitude to better track and understand mmex desktop usage

src/filtertransdialog.cpp, src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6279)
=> fix(#6270): reorder hidden fields

src/constants.cpp, src/constants.h, src/model/Model_Usage.cpp, src/model/Model_Usage.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6282)
=> clean up ga4 code and add event_properties to track page title&path

CMakeLists.txt, src/paths.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6283)
Fixes https://github.com/moneymanagerex/moneymanagerex/issues/6269
=> Have license.txt be translatable

src/model/Model_Usage.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6287)
=> send plt to measure performance

src/assetspanel.cpp, src/mmreportspanel.cpp, src/model/Model_Usage.cpp, src/model/Model_Usage.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6291)
=> Plt4report

src/constants.cpp, src/model/Model_Usage.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6293)
=> send events via main_stats_v2

src/mmcheckingpanel.cpp
https://github.com/moneymanagerex/moneymanagerex/issues/6281
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6300)
=> fix(#6281) Update mmcheckingpanel.cpp

src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6316)
=> fix(#6280): fix drop arrow on Linux

src/accountdialog.cpp, src/billsdepositsdialog.cpp, src/billsdepositspanel.cpp, src/budgetentrydialog.cpp, src/budgetingpanel.cpp, src/budgetyeardialog.cpp, src/budgetyearentrydialog.cpp, src/categdialog.cpp, src/currencydialog.cpp, src/general_report_manager.cpp, src/import_export/qif_export.cpp, src/import_export/qif_import_gui.cpp, src/import_export/univcsvdialog.cpp, src/maincurrencydialog.cpp, src/mmSimpleDialogs.cpp, src/mmhomepagepanel.cpp, src/mmreportspanel.cpp, src/optiondialog.cpp, src/relocatecategorydialog.cpp, src/relocatepayeedialog.cpp, src/relocatetagdialog.cpp, src/sharetransactiondialog.cpp, src/stockdialog.cpp, src/stockspanel.cpp, src/tagdialog.cpp, src/transactionsupdatedialog.cpp, src/transdialog.cpp
fix, It was returning TRUE when it should return true.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6318)
=> fix, It was returning TRUE when it should return true.

src/constants.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6320)
=> Revert "Update constants.cpp"

src/mmcheckingpanel.cpp, src/mmcheckingpanel.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6324)
=> fix(#6311): credit limit presentation

.appveyor.yml, .circleci/config.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6327)
=> fix(#6322): wx3.2.4

src/mmSimpleDialogs.cpp, src/mmSimpleDialogs.h, src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6331)
=> fix(#6280): correct tag dropdown position

src/mmhomepage.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6330)
=> fix(#6323): Correct conversion rate calculation

src/aboutdialog.cpp, src/aboutdialog.h, src/util.cpp, src/util.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6334)
=> fix(#6332): add copy to clipboard

src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6337)
=> fix(#6332): fix ID

src/mmSimpleDialogs.cpp, src/mmSimpleDialogs.h, src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6345)
=> fix(#5439): use organize tags dialog instead of dropdown on macOS

src/stockdialog.h, src/themes.cpp, src/transactionsupdatedialog.cpp
Appveyor build config needs updating to /std:c++latest or /std:c++17
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6347)
=> Revert "Cleanups"

src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6350)
=> fix(#5439): tag control fixes for macOS

src/mmchecking_list.cpp, src/mmchecking_list.h, src/transactionsupdatedialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6351)
=> fix(#6346): fix menu IDs

src/mmSimpleDialogs.cpp, src/tagdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6352)
=> fix(#5439): allow cancel in tag dialog during txn entry

src/model/Model_Currency.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6353)
=> fix(#6074): fix currency format on Linux

src/import_export/export.cpp, src/import_export/export.h, src/import_export/qif_export.cpp, src/import_export/univcsvdialog.cpp, src/import_export/univcsvdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6357)
=> feat(#5439): tags in import/export

src/import_export/export.cpp, src/import_export/qif_import_gui.cpp, src/import_export/qif_import_gui.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6362)
=> fix(#5439): tags in QIF import/export

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6367)
=> fix(#6333): always show full path in recent files

src/import_export/export.cpp, src/import_export/qif_import_gui.cpp, src/import_export/univcsvdialog.cpp, src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6370)
=> fix(#5439): fix tag im/export on QIF transfer txns

src/import_export/qif_import_gui.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6378)
=> fix(#5439): fix QIF import error on "Opening Balance"

NEWS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6379)
=> v1.7.0 RC 1

NEWS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6385)
=> v1.7.0-Linux NEWS.md fix

src/mmSimpleDialogs.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6414)
=> fix(#6405): disable panel

CMakeLists.txt
Fixes https://github.com/moneymanagerex/moneymanagerex/issues/6386
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6415)
=> Add validation to the metainfo file generated at build time

CMakeLists.txt
Reverts moneymanagerex/moneymanagerex#6418
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6419)
=> Revert "Revert "Add validation to the metainfo file generated at build time""

CMakeLists.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6420)
=> Add hotfix for developer ID in metainfo

resources/dist/linux/share/metainfo/org.moneymanagerex.MMEX.metainfo.xml.in
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6423)
=> Fix typo in developer field

src/import_export/parsers.cpp, src/mmSimpleDialogs.cpp, src/model/Model_CurrencyHistory.cpp, src/model/Model_CustomField.cpp, src/model/Model_Report.cpp, src/model/Model_Splittransaction.cpp, src/model/Model_StockHistory.cpp, src/model/Model_Usage.cpp, src/reports/htmlbuilder.cpp, src/reports/summary.cpp, src/util.cpp, src/util.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6416)
=> Delete unnecessary ";"

src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6430)
=> fix(#6400): fix linux crash on right click

src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6426)
=> fix(#6424): clone tags on txn copy/paste

src/model/Model_Stock.cpp, src/reports/summarystocks.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6429)
=>  fix(#6428): fix stock value@date calculation when no share txns exist 

BUILD.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6427)
=> fix Windows CURL build command to enable HTTPS

src/filtertransdialog.cpp, src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6432)
=> fix(#6408): Rate naming

src/reports/mmDateRange.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6433)
=> fix(#6391): fix missing date range translation

src/reports/transactions.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6442)
=> fix(#5685): move chart to the top

.appveyor.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6447)
=> fix(#6434): use VS2022 build image & update curl to 8.5.0

src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6455)
=> fix(#6139): fix crash on txn right click delete

src/attachmentdialog.cpp, src/categdialog.cpp, src/categdialog.h, src/maincurrencydialog.cpp, src/maincurrencydialog.h, src/mmTips.h, src/mmframe.cpp, src/optionsettingsgeneral.cpp, src/payeedialog.cpp, src/sharetransactiondialog.cpp, src/stockdialog.cpp, src/tagdialog.cpp, src/tagdialog.h, src/transdialog.cpp, src/usertransactionpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6459)
=> Organize Noun (plural) → Noun (singular) Manager

contrib.txt, src/mmchecking_list.cpp, src/mmchecking_list.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6461)
=> fix(#6457): copy transaction data

src/budgetingpanel.cpp, src/constants.cpp, src/customfieldlistdialog.cpp, src/filtertransdialog.h, src/general_report_manager.cpp, src/general_report_manager.h, src/mmTips.h, src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6460)
=> Budget Setup → Budget Planner

src/constants.cpp, src/tagdialog.cpp
@rmelillo76, @n-stein, @whalley Please advise if there are any other changes required. Thank you
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6467)
=> (fix#6460): revert some strings

CMakeLists.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6472)
=>  fix(#6465): fix beta builds on Ubuntu LTS releases 

src/appstartdialog.cpp, src/appstartdialog.h, src/reports/summarystocks.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6479)
=> fix(#6471): skip closed investment accounts

contrib.txt, license.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6488)
=> fix(#6487): copyright and sponsors

src/reports/transactions.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6492)
=> feat(#5685): add statistics

src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6498)
=> fix(#6497): apply right click filter in All Transactions

src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6500)
=> fix(#5685): fix decimal values

src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6501)
=> fix(#5685): fix cast

src/mmframe.cpp, src/mmframe.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6505)
=> fix(#3681): redock tool/nav panels

src/assetdialog.cpp, src/billsdepositsdialog.cpp, src/filtertrans.cpp, src/filtertransdialog.cpp, src/import_export/qif_export.cpp, src/import_export/qif_import_gui.cpp, src/import_export/univcsvdialog.cpp, src/mmSimpleDialogs.cpp, src/mmSimpleDialogs.h, src/mmchecking_list.cpp, src/mmchecking_list.h, src/mmcheckingpanel.cpp, src/mmcustomdata.cpp, src/mmframe.cpp, src/model/Model_Billsdeposits.cpp, src/model/Model_Billsdeposits.h, src/model/Model_Checking.cpp, src/model/Model_Checking.h, src/model/Model_Translink.cpp, src/reports/cashflow.cpp, src/stockdialog.cpp, src/transactionsupdatedialog.cpp, src/transdialog.cpp, src/usertransactionpanel.cpp, src/webapp.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6508)
=> feat(#2729): add transaction time

src/filtertransdialog.cpp, src/reports/mmDateRange.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6514)
=> fix(#2729): fix max date to UTC

src/mmchecking_list.cpp, src/reports/cashflow.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6519)
=> fix(#2729): fix for datetime handling

src/import_export/univcsvdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6525)
=> fix(#6524): fix addition of payee match details to notes

src/customfieldeditdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6533)
=> fix(#4320): require choices on 'selection' type custom fields

src/filtertrans.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6543)
=> fix(#2729): fix range start date check

src/import_export/qif_export.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6563)
=> fix(#6554): correct dialog title for csv export

src/billsdepositsdialog.cpp, src/billsdepositspanel.cpp, src/mmframe.cpp, src/model/Model_Billsdeposits.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6571)
=> fix(#6570): scheduled transaction fixes

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6577)
=> fix(#6573): fix nav tree context menu position

src/transactionsupdatedialog.cpp, src/transactionsupdatedialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6582)
=> fix(#6581): separate date/time controls in multi txn update

src/import_export/univcsvdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6580)
=> fix(#6050): add scroll window to CSV import dlg 

src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6590)
=> fix(#6589): fix txn filter date check

.appimage-builder.yml, .github/workflows/ubuntu-ci.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6598)
=> fix(#6360): add ubuntu ci build for .deb & AppImage

src/billsdepositsdialog.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6597)
=> fix(#6595): fix event binding for freq notes

contrib.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6599)
=> chroe(contrib.txt): new sponsor

src/mmhomepage.cpp, src/model/Model_Translink.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6611)
=> fix(#6610): fix asset "initial value" & VALUE calculation

README.md, resources/dist/linux/share/metainfo/org.moneymanagerex.MMEX.metainfo.xml.in
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6606)
=> Update screenshots in README.md and metadata files before upcoming release

src/import_export/export.cpp, src/wizard_newdb.cpp, src/wizard_newdb.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6622)
=> Small warning fixes

docs/budget.html, docs/grm.html, docs/index.html, docs/stocks_and_shares.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6623)
=> Sort alphabetically

docs/en_US/index.html
https://github.com/moneymanagerex/moneymanagerex/issues/1992#issuecomment-560599578
label:doc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6634)
=> fix(#1992): Create Scheduled Transaction from an existing transaction

src/model/Model_Stock.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6649)
=> fix(#6639): exclude deleted txns from investment value

src/import_export/univcsvdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6650)
=> fix(#6642): sort by date to fix balance calc

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6673)
=> fix(#6672): save tags for autoexecuted scheduled txns

NEWS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6679)
=> chore(NEWS): Update version and add feature/bug list

src/budgetingpanel.cpp, src/filtertransdialog.cpp, src/mmhomepage.cpp, src/model/Model_Stock.cpp, src/relocatecategorydialog.cpp, src/splittransactionsdialog.cpp, src/splittransactionsdialog.h, src/validators.h
Just some warning fixes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6682)
=> Some warning fixes

NEWS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6692)
=> chore(v1.8.0)

src/accountdialog.cpp, src/customfieldeditdialog.cpp, src/db/DB_Table_Category_V1.h, src/mmSimpleDialogs.cpp, src/mmchecking_list.cpp, src/mmframe.cpp, src/mmframereport.cpp, src/mmhomepage.cpp, src/optiondialog.cpp, src/optionsettingshome.cpp, src/reports/budgetcategorysummary.cpp, src/reports/incexpenses.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6549)
=> miscellaneous update

contrib.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6712)
=> chore(contrib.txt)

docs/css/manual.css, src/appstartdialog.cpp, src/categdialog.cpp, src/constants.cpp, src/filtertransdialog.h, src/maincurrencydialog.cpp, src/mmframe.cpp, src/optionsettingsmisc.cpp, src/relocatecategorydialog.cpp, src/relocatecategorydialog.h, src/relocatepayeedialog.cpp, src/relocatepayeedialog.h, src/relocatetagdialog.cpp, src/relocatetagdialog.h
* Update Help font to black
* Update keyboard shortcuts which have collisions
* Update `Reassign` to `Merge`
* Update `Merge lowercase` to `Merge Capitalize Every Letter` to consistence with other dialog boxes
* Update `Transaction Report Filter` to `Customize Transaction Report`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6699)
=> Miscellaneous

src/billsdepositsdialog.cpp, src/billsdepositsdialog.h, src/images_list.cpp, src/images_list.h, src/mmSimpleDialogs.cpp, src/mmSimpleDialogs.h, src/mmTextCtrl.cpp, src/mmTextCtrl.h, src/transdialog.cpp, src/transdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6718)
=>  fix(#6703): add calculator in txn dialogs 

.github/workflows/ubuntu-ci.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6707)
=> Sign .deb and AppImage with Sigstore in GitHub Actions CI

.github/workflows/ubuntu-ci.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6728)
=> Fix Ubuntu CI Permissions Issue

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6755)
=> fix(#5887): remove current type from account reallocation

resources/home_page.htt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6754)
=> fix(#6733): float dashboard net worth table

src/billsdepositsdialog.cpp, src/mmSimpleDialogs.cpp, src/mmSimpleDialogs.h, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6753)
=> fix(#6703): display fixes for calculator widget

src/mmreportspanel.cpp, src/reports/budget.cpp, src/reports/budgetcategorysummary.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6751)
=> fix(#6743): monthly budgets on category summary rpt

src/general_report_manager.cpp, src/mmchecking_list.cpp, src/mmframe.cpp, src/optionsettingsview.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6749)
=> Navigation → Navigator F5

src/filtertransdialog.cpp, src/mmex.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6734)
=> Small cleanups

src/mmchecking_list.cpp, src/mmcheckingpanel.cpp, src/mmhomepage.cpp, src/reports/cashflow.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6750)
=> fix(#6745): handle future transactions according to time

src/diagnostics.cpp, src/mmframe.cpp, src/optiondialog.cpp, src/optiondialog.h, src/optionsettingsattachment.cpp, src/optionsettingsmisc.cpp, src/optionsettingsnet.cpp, src/optionsettingsview.cpp, src/relocatecategorydialog.cpp, src/relocatepayeedialog.cpp, src/relocatetagdialog.cpp, src/themes.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6757)
=> Keyboard shortcuts/accelerators

src/optionsettingsmisc.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6758)
=> Update file extension to `bak`

README.md
https://github.com/moneymanagerex/moneymanagerex/issues/6773
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6783)
=> `Customize Transaction Report ` screenshot (attempt 3)

docs/en_US/index.html
https://github.com/moneymanagerex/moneymanagerex/issues/5439#issuecomment-2139810706
https://github.com/moneymanagerex/moneymanagerex/issues/5439#issuecomment-2140271072
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6784)
=> [Help] Is the MMEX database structure documented somewhere?

docs/en_US/index.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6788)
=> [Help] Is the MMEX database structure documented somewhere? (attempt 2)

.appveyor.yml, .circleci/config.yml, .github/workflows/ubuntu-ci.yml, org.moneymanagerex.MMEX.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6800)
=> fix(#6799): wxWidgets 3.2.5

src/filtertransdialog.cpp, src/mmchecking_list.cpp, src/mmchecking_list.h, src/optiondialog.cpp, src/optionsettingsview.cpp, src/optionsettingsview.h, src/themes.cpp, src/themes.h, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6807)
=> Some warning cleanups

src/accountdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6832)
=> fix(#6158): allow case change in acct name

contrib.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6834)
=> chore(contrib.txt) New sponsors

src/reports/cashflow.cpp
This PR fixes the repetition of scheduled transactions in `mmReportCashFlow::getTransactions()`, in accordance with `Model_Billsdeposits::completeBDInSeries()`.
The functions in `cashflow.cpp` have several more problems, e.g.,
- The initial balance in `mmReportCashFlow::getTransactions()` ignores `foreignTransactionAsTransfer` (trasfters to `AS_TRANSFER`), which is inconsistent with `Model_Account::balance()`.
- `mmReportCashFlow::trueAmount()` ignores transfer transactions if both `ACCOUNTID` and `TOACCOUNTID` are in `m_account_id`, probably assuming that the net amount is zero, but this is not always true.
- The scheduled transaction dates in `mmReportCashFlow::getTransactions()` are based on `NEXTOCCURRENCEDATE` instead of `TRANSDATE`.
- Residual scheduled transaction (with date earler …
=> fix(#6827): cashflow (REPEATS, NUMOCCURRENCES)

resources/dist/linux/share/metainfo/org.moneymanagerex.MMEX.metainfo.xml.in
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6872)
=> Attempt to localize screenshot `<caption>` tags at Flathub

.circleci/config.yml, org.moneymanagerex.MMEX.yml
Reverts moneymanagerex/moneymanagerex#6891
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6893)
=> Revert "Update Gnome SDK to latest version in flatpak manifest"

.appveyor.yml, .circleci/config.yml, .github/workflows/ubuntu-ci.yml, BUILD.md, org.moneymanagerex.MMEX.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6895)
=> fix(#6892): wx3.2.6

src/filtertransdialog.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6901)
=> fix(#6882): wxunused

src/attachmentdialog.cpp, src/attachmentdialog.h, src/billsdepositsdialog.h, src/budgetyearentrydialog.h, src/categdialog.h, src/customfieldlistdialog.cpp, src/customfieldlistdialog.h, src/diagnostics.h, src/filtertransdialog.h, src/images_list.cpp, src/import_export/qif_export.h, src/import_export/qif_import_gui.h, src/import_export/univcsvdialog.h, src/maincurrencydialog.h, src/mmTextCtrl.h, src/mmcheckingpanel.h, src/mmcombobox.h, src/mmcustomdata.h, src/optionsettingsgeneral.h, src/payeedialog.h, src/recentfiles.cpp, src/relocatecategorydialog.cpp, src/relocatecategorydialog.h, src/relocatetagdialog.h, src/sharetransactiondialog.h, src/splittransactionsdialog.h, src/stockdialog.h, src/stockspanel.h, src/transdialog.h, src/wizard_newdb.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6904)
=> static analysis warnings

src/mmframe.cpp, src/reports/mmDateRange.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6933)
=> fix(#6847): fix wxWidgets debug assertion failures

src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6936)
=> fix(#6935): use constant for right click filter type

src/filtertransdialog.cpp, src/import_export/univcsvdialog.cpp, src/import_export/univcsvdialog.h, src/mmSimpleDialogs.cpp, src/mmSimpleDialogs.h, src/payeedialog.h, src/relocatepayeedialog.cpp, src/relocatepayeedialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6939)
=> Cleanups: Dangling pointers, unused variables, signness

contrib.txt, src/filtertrans.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6955)
=> fix(#6954): split notes reporting for transaction detail

src/assetspanel.cpp, src/assetspanel.h, src/billsdepositspanel.cpp, src/billsdepositspanel.h, src/mmchecking_list.cpp, src/mmchecking_list.h, src/mmcheckingpanel.cpp, src/mmpanelbase.cpp, src/mmpanelbase.h, src/stocks_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6959)
=> fix(#6847): fixes for Windows drag & drop

src/mmSimpleDialogs.cpp, src/option.cpp, src/optionsettingshome.cpp, src/payeedialog.cpp, src/payeedialog.h, src/relocatecategorydialog.cpp, src/relocatecategorydialog.h, src/reports/budgetcategorysummary.cpp, src/splittransactionsdialog.cpp, src/splittransactionsdialog.h, src/stockspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6961)
=> Warning fixes, cleanups

src/mmreportspanel.cpp
https://github.com/moneymanagerex/moneymanagerex/issues/6898
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6899)
=> fix(#6898): Drop down remove colons

src/model/Model_Checking.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6983)
=> new(#6860): fix bug in account_flow

src/dbwrapper.cpp, src/util.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6984)
=> fix(#6971): prompt to auto rekey encrypted db with new cipher algorithm

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6991)
=> fix(#6990): mark string for translation

src/accountdialog.cpp, src/assetspanel.cpp, src/attachmentdialog.cpp, src/billsdepositsdialog.cpp, src/billsdepositspanel.cpp, src/customfieldlistdialog.cpp, src/filtertrans.cpp, src/filtertransdialog.cpp, src/import_export/export.cpp, src/import_export/qif_import_gui.cpp, src/import_export/univcsvdialog.cpp, src/mmchecking_list.cpp, src/mmcheckingpanel.cpp, src/mmhomepage.cpp, src/mmreportspanel.cpp, src/model/Model_Checking.cpp, src/option.cpp, src/reports/budgetcategorysummary.cpp, src/reports/budgetingperf.cpp, src/reports/categexp.cpp, src/reports/payee.cpp, src/reports/summary.cpp, src/reports/transactions.cpp, src/stocks_list.cpp, src/util.cpp, src/webapp.cpp, src/webappdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6994)
=> fix(#6966): correct int64 format specifier

.github/ISSUE_TEMPLATE/bug_report.md
In Navigator tree, align Dashboard to other top-level items.
- Add a non-visible root item.
- Dashboard is the first child of the root item (it was the root before).
- Adjust spacing of open/close symbols (a little more compact layout, the symbols still show clearly the hierarchy).
- Tested on macOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6995)
=> fix navtree

README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7000)
=> Add download links for iPhone, iPad, and Android

src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6999)
=> fix(#6998): fix crash on nav tree ctrl reset

contrib.txt, src/payeedialog.h, src/relocatepayeedialog.cpp, src/relocatepayeedialog.h, src/relocatetagdialog.cpp, src/relocatetagdialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7007)
=> fix(#6992): payee id should be int64

src/db/DB_Table.h, src/db/DB_Table_Accountlist_V1.h, src/db/DB_Table_Assets_V1.h, src/db/DB_Table_Attachment_V1.h, src/db/DB_Table_Billsdeposits_V1.h, src/db/DB_Table_Budgetsplittransactions_V1.h, src/db/DB_Table_Budgettable_V1.h, src/db/DB_Table_Budgetyear_V1.h, src/db/DB_Table_Category_V1.h, src/db/DB_Table_Checkingaccount_V1.h, src/db/DB_Table_Currencyformats_V1.h, src/db/DB_Table_Currencyhistory_V1.h, src/db/DB_Table_Customfield_V1.h, src/db/DB_Table_Customfielddata_V1.h, src/db/DB_Table_Infotable_V1.h, src/db/DB_Table_Payee_V1.h, src/db/DB_Table_Report_V1.h, src/db/DB_Table_Setting_V1.h, src/db/DB_Table_Shareinfo_V1.h, src/db/DB_Table_Splittransactions_V1.h, src/db/DB_Table_Stock_V1.h, src/db/DB_Table_Stockhistory_V1.h, src/db/DB_Table_Tag_V1.h, src/db/DB_Table_Taglink_V1.h, src/db/DB_Table_Translink_V1.h, src/db/DB_Table_Usage_V1.h, util/sqlite2cpp.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6964)
=> SUID support

contrib.txt, src/customfieldlistdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7013)
=> fix(#7012): int64 cast fix

src/attachmentdialog.cpp, src/maincurrencydialog.cpp, src/stockdialog.cpp, src/webappdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7014)
=> fix(#6966): few more int64 casts

.github/workflows/ubuntu-ci.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7020)
=> fix: ubuntu-ci sign on push

src/filtertransdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7023)
=> fix(#7018): fix txn report acct filter

src/mmreportspanel.cpp, src/reports/budgetingperf.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7016)
=> fix(#6967): budget link fixes?

contrib.txt, src/reports/transactions.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7026)
=> fix(#7018): comparison fix

src/mmchecking_list.h, src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7034)
=> fix(#7033): remove duplicate column creation

src/import_export/parsers.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7037)
=> cleanup: Could not → Unable to

src/accountdialog.cpp, src/categdialog.cpp, src/currencydialog.cpp, src/dbwrapper.cpp, src/mmchecking_list.cpp, src/mmcheckingpanel.cpp, src/mmframe.cpp, src/tagdialog.cpp
{cannot, can't} → unable to
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7048)
=> cleanup: {cannot, can't} → unable to

src/assetspanel.cpp, src/billsdepositspanel.cpp, src/general_report_manager.cpp, src/import_export/qif_export.cpp, src/import_export/qif_import_gui.cpp, src/import_export/univcsvdialog.cpp, src/mmchecking_list.cpp, src/mmcheckingpanel.cpp, src/mmframe.cpp, src/mmhomepage.cpp, src/stocks_list.cpp, src/stockspanel.cpp
@n-stein
1. Separate PR as you requested at https://github.com/moneymanagerex/moneymanagerex/pull/7045#issuecomment-2557953881
2. Can you please help with https://github.com/moneymanagerex/moneymanagerex/pull/7045#issuecomment-2557882381 as these changes are done in web browser. Feel free to take over this PR. If this is just merged, should be easy to update in Crowdin as there is translation history.
@vomikan fyi
Thank you
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7050)
=> cleanup: 3-to-1 character ellipses

.github/workflows/update-po-template.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7056)
=> fix: merge master to l10n

src/constants.cpp, src/constants.h, src/mmframe.cpp, src/mmframe.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7067)
=> MMEX for iOS

src/assetspanel.cpp, src/billsdepositspanel.cpp, src/general_report_manager.cpp, src/images_list.cpp, src/import_export/qif_export.cpp, src/import_export/qif_import_gui.cpp, src/import_export/univcsvdialog.cpp, src/mmchecking_list.cpp, src/mmcheckingpanel.cpp, src/mmframe.cpp, src/mmhomepage.cpp, src/mmreportspanel.cpp, src/stocks_list.cpp, src/stockspanel.cpp, util/update-po-files.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7057)
=> fix(#7055): fix translations with unicode

src/mmcheckingpanel.cpp
Fix minor bug in `mmCheckingPanel::updateExtraTransactionData()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7061)
=> fix(#7059): minDate in mmCheckingPanel

src/mmchecking_list.cpp, src/mmcheckingpanel.cpp, src/mmcheckingpanel.h, src/mmframe.cpp, src/mmframe.h, src/mmpanelbase.cpp, src/reports/budgetcategorysummary.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7068)
=> Usual cleanups

src/mmreportspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7089)
=> fix(#7082): fix txn report links for int64 ids

src/payeedialog.cpp, src/payeedialog.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7091)
=> fix(#7088): fix id storage in payee dialog

src/import_export/univcsvdialog.cpp, src/mmreportspanel.cpp, src/payeedialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7098)
=> fix(#7097), fix(#7090): corrections for CSV import

src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7103)
=> fix(#7102): fix linux crash on right click

src/filtertransdialog.cpp, src/mmchecking_list.cpp, src/mmcheckingpanel.cpp, src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7113)
=> cleanup(#7112): fix build warnings

NEWS, src/reports/cashflow.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7158)
=> fix(#7157): cash flow bug fix

src/mmcheckingpanel.cpp, src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7179)
=> fix(#7178): fix unicode char handling in JSON formatted db entries

NEWS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7181)
=> chore(v1.9.0): new version

src/billsdepositsdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7196)
=> fix(#7195): field size

src/db/DB_Table.h, util/sqlite2cpp.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7207)
=> fix(#7174): ensure SUID has unique time component

src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7230)
=> fix(#7229): set range max

docs/en_US/index.html, docs/fr_FR/index.html
removed "strike through" as emb database is available
explained how to switch between mmb and emb databases
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7228)
=> Correction of the user manuals en_US and fr_FR about emb files

src/assetspanel.cpp, src/assetspanel.h, src/billsdepositspanel.cpp, src/billsdepositspanel.h, src/budgetingpanel.cpp, src/budgetingpanel.h, src/import_export/qif_import_gui.cpp, src/import_export/qif_import_gui.h, src/mmchecking_list.cpp, src/mmchecking_list.h, src/mmcheckingpanel.cpp, src/mmcheckingpanel.h, src/mmpanelbase.cpp, src/mmpanelbase.h, src/stocks_list.cpp, src/stocks_list.h, src/stockspanel.cpp
This is only a refactor (preparation to refine mmListCtrl).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7238)
=> refine mmListCtrl (part 1)

util/update-po-files.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7258)
=> fix(#7247): support additional macros

src/mmcheckingpanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7263)
=> new(#7150), part 6: fix bug in loadFilterSettings()

src/budgetentrydialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7273)
=> fix(crowdin): Address comment on Crowdin.

src/budgetentrydialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7274)
=> budgetentrydialog.cpp: cleanup

src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7278)
=> fix(#7277): utf8 strings

src/mmTreeItemData.h, src/mmframe.cpp, src/reports/incexpenses.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7280)
=> Stock: mmTreeItemData::STOCK to INVESTMENT to reflect well

src/filtertransdialog.cpp, src/mmcustomdata.cpp, src/mmcustomdata.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7281)
=> fix(#7272): custom field indexing

src/mmframe.cpp, src/stockdialog.cpp, src/stockspanel.cpp, src/usertransactionpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7286)
=> Stock: leverage link between STOCKNAME and ACCOUTNAME

src/assetdialog.cpp, src/stockdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7303)
=> Stock & Asset: streamline stock & asset creation

po/common.po
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7300)
=> fix(#7292): add languages da-DK, fo-FO, fa-IR

src/reports/summarystocks.cpp, src/stockspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7306)
=> Stock: v1.5, add Total Account Value and use Market Value

src/reports/summarystocks.cpp, src/stockdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7307)
=> Stock: v1.5, always link share transaction

src/stockspanel.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7309)
=> Stock: v1.5 tiny bugfix

src/model/Model_Checking.cpp, src/model/Model_Checking.h, src/stocks_list.cpp, src/stockspanel.cpp, src/usertransactionpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7311)
=> Stock: v1.5 WITHDRAWAL ==> Buy, DEPOSIT ==> Sell

src/model/Model_Account.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7315)
=> Stock: v1.5, handle shares:stock = 1:m case

src/stockspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7317)
=> Stock: refine panel metrics and only display the stock assigned trans

src/mmchecking_list.cpp, src/model/Model_Stock.cpp, src/model/Model_Stock.h, src/model/Model_Translink.cpp, src/model/Model_Translink.h, src/sharetransactiondialog.cpp, src/stocks_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7318)
=> Stock: Model_Translink::UpdateStockValue => Model_Stock::UpdatePosition

src/model/Model_Account.cpp, src/stockspanel.cpp
to polish #7286 
- #7286
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7319)
=> Stock: restore trigger from TransLink to display stock details

src/mmframe.cpp, src/mmhomepage.cpp, src/sharetransactiondialog.cpp, src/stockdialog.cpp, src/transdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7320)
=> Stock: v2, Investment Account -> Stock directly, and skip Shares Account

docs/en_US/stocks_and_shares.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7325)
=> Investment: v2.0 update doc

src/assetdialog.cpp, src/mmchecking_list.cpp, src/sharetransactiondialog.cpp, src/usertransactionpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7332)
=> Stock: v2, ignore TOACCOUNTID and refine TRANSACTIONNUMBER

src/stocks_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7338)
=> Stock: v2, disable Adjust Trade for zero share

docs/en_US/stocks_and_shares.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7343)
=> Stock: v2, fix typo and refine

src/sharetransactiondialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7344)
=> Stock: v2, reinforce share lot with STOCKID

src/mmpanelbase.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7346)
=> fix(#7345): fix mmListCtrl::savePreferences()

src/model/Model_Shareinfo.cpp, src/model/Model_Shareinfo.h, src/model/Model_Splittransaction.cpp, src/model/Model_Splittransaction.h, src/sharetransactiondialog.cpp, src/sharetransactiondialog.h, src/stockdialog.cpp, src/stockspanel.cpp, src/usertransactionpanel.cpp, src/usertransactionpanel.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7347)
=> Stock: v2, introduce Deductible Comm. split

src/sharetransactiondialog.cpp, src/usertransactionpanel.cpp, src/usertransactionpanel.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7350)
=> Stock: v2, split for investment cash transaction (still hide)

src/assetdialog.cpp, src/assetdialog.h, src/assetspanel.cpp, src/mmcheckingpanel.cpp, src/mmhomepage.cpp, src/model/Model_Account.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7351)
=> Asset: refine homepage and show Curr.Val. for reference

src/assetspanel.cpp, src/mmhomepagepanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7356)
=> Asset: link from asset portfolio view to asset cash flow ledger view

src/model/Model_Asset.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7365)
=> Asset: unify initial val and market val calculation

src/assetdialog.cpp, src/model/Model_Asset.cpp, src/model/Model_Checking.cpp, src/model/Model_Translink.cpp, src/sharetransactiondialog.cpp, src/usertransactionpanel.cpp, src/usertransactionpanel.h
to impl 
- #7363 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7366)
=> Asset: Revaluation via Self Transfer

src/assetdialog.cpp, src/usertransactionpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7370)
=> Asset: refine INITIALDATE/STARTDATE and OnTransCategoryCombobox

src/model/Model_Asset.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7374)
=> Asset: skip deleted txn

src/model/Model_Asset.cpp, src/model/Model_Asset.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7377)
=> Asset: refine value calc

src/assetdialog.cpp, src/assetspanel.cpp, src/model/Model_Account.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7378)
=> Asset: v2, ASSETTYPE to ACCOUNTNAME linkage

src/usertransactionpanel.cpp, src/usertransactionpanel.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7380)
=> Asset&Stock: refine usertransactionpanel with Bind

src/assetspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7383)
=> Asset: fix a condition bug to view asset transactions

src/assetspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7386)
=> Asset: try to re-use existing i18n

src/stockspanel.cpp, src/stockspanel.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7393)
=> Stock: V2 refine ViewStockTransactions

src/assetspanel.cpp, src/assetspanel.h
Just like 
- #7393
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7394)
=> Asset: v2 refine ViewAssetTrans

src/assetspanel.cpp, src/stockspanel.cpp
performance is TBD
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7396)
=> Investment: tune asset/stock transaction list width and sort by invested capital

.appveyor.yml, .circleci/config.yml, .github/workflows/ubuntu-ci.yml, BUILD.md, org.moneymanagerex.MMEX.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7400)
=> fix(#7372): wx3.2.7

src/reports/summary.cpp, src/reports/summary.h
to solve
- #7412
1. Replace `Share Accounts` with `Investment Accounts`' cash balance
2. The stocks column still shows its market value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7413)
=> Stock v2: refine Reports -> Summary of Accounts

src/reports/summary.cpp
contine refinement 
- #7412 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7415)
=> Stock v2: always calc cash bal

src/reports/summary.cpp
to fix accaccumulated counting issue mentioned in #7412 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7417)
=> Stock v2: declare local balancePerDay locally..

src/mmreportspanel.cpp
Fix issue 6: drop dwon list  from 
- #7412
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7418)
=> Stock v2: show investment in various drop-down list

src/mmhomepage.cpp, src/mmhomepage.h, src/reports/reportbase.cpp
Fix issue 5:  Add the market value and the cash balance (in addition to showing the sum of both)
- #7412
and refine issue 6
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7419)
=> Stock v2: add stock market value and cash bal to Dashboard

src/filtertransdialog.cpp, src/mmreportspanel.cpp, src/option.cpp, src/optionsettingshome.cpp, src/reports/mmDateRange.cpp, src/reports/mmDateRange.h
https://forum.moneymanagerex.org/viewtopic.php?p=26445#p26445
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7420)
=> Predefined date range: support Year before last

src/sharetransactiondialog.cpp, src/stocks_list.cpp, src/stockspanel.cpp, src/stockspanel.h
to refine item 3 and 7 from #7412 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7422)
=> Stock v2: refine share transaction number and support basic filter

src/mmhomepage.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7424)
=> Asset: v2, add cash bal and total to Dashboard (follow Stock v2)

src/assetspanel.cpp
contine refining Asset Seach
- #7188 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7425)
=> Asset:search & highlight, auto next by enter

src/assetdialog.cpp, src/model/Model_Checking.cpp, src/model/Model_Translink.cpp, src/usertransactionpanel.cpp
to fix `AsTransfer` issue from 
- #7412
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7432)
=> Investment v2: restore AsTransfer back with a refined way

.appveyor.yml, .circleci/config.yml, .github/workflows/ubuntu-ci.yml, BUILD.md, CMakeLists.txt, src/stockspanel.cpp
to address 
- #7433
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7431)
=> Infra: use c++17

BUILD.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7438)
=> fix typo in BUILD.md

src/budgetingpanel.cpp, src/general_report_manager.cpp, src/mmchecking_list.cpp, src/model/Model_Category.cpp, src/model/Model_Report.cpp, src/reports/categexp.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7440)
=> Infra: use emplace_back where possible

src/mmframe.cpp, src/reports/transactions.cpp, src/reports/transactions.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7446)
=> Infra: refine Transaction Report

.appveyor.yml, .circleci/config.yml, .github/workflows/ubuntu-ci.yml, BUILD.md, CMakeLists.txt, README.md, src/categdialog.cpp
to address 
- #7433 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7447)
=> Infra: C++20 w/ a tiny example

src/maincurrencydialog.cpp, src/stockdialog.cpp, util/sqlite2cpp.py
Issue #7450
Issue #7451
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7452)
=> Fix bug where test of the first parameter was missing and Memeory Exception in Currency/Stock History price

src/db/DB_Table.h, util/sqlite2cpp.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7454)
=> Infra: fix folding expressions

src/usertransactionpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7455)
=> Investment v2: use std size to display category

.appveyor.yml, .circleci/config.yml, .github/workflows/ubuntu-ci.yml, BUILD.md, org.moneymanagerex.MMEX.yml, src/mmex.cpp, src/webappdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7459)
=> restore branch

src/db/DB_Table.h, src/db/DB_Table_Accountlist_V1.h, src/db/DB_Table_Assets_V1.h, src/db/DB_Table_Attachment_V1.h, src/db/DB_Table_Billsdeposits_V1.h, src/db/DB_Table_Budgetsplittransactions_V1.h, src/db/DB_Table_Budgettable_V1.h, src/db/DB_Table_Budgetyear_V1.h, src/db/DB_Table_Category_V1.h, src/db/DB_Table_Checkingaccount_V1.h, src/db/DB_Table_Currencyformats_V1.h, src/db/DB_Table_Currencyhistory_V1.h, src/db/DB_Table_Customfield_V1.h, src/db/DB_Table_Customfielddata_V1.h, src/db/DB_Table_Infotable_V1.h, src/db/DB_Table_Payee_V1.h, src/db/DB_Table_Report_V1.h, src/db/DB_Table_Setting_V1.h, src/db/DB_Table_Shareinfo_V1.h, src/db/DB_Table_Splittransactions_V1.h, src/db/DB_Table_Stock_V1.h, src/db/DB_Table_Stockhistory_V1.h, src/db/DB_Table_Tag_V1.h, src/db/DB_Table_Taglink_V1.h, src/db/DB_Table_Translink_V1.h, src/db/DB_Table_Usage_V1.h, util/sqlite2cpp.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7464)
=> Infra: use spaceship operator

org.moneymanagerex.MMEX.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7466)
=> Infra: cpp20 for Flathub

src/assetspanel.cpp, src/mmframe.cpp, src/util.cpp, src/wizard_update.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7473)
=> Infra: cpp20 Range-based for statements with initializer

.appveyor.yml, .circleci/config.yml, .github/workflows/ubuntu-ci.yml, BUILD.md, org.moneymanagerex.MMEX.yml
to fix #7467 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7480)
=> upgrade to wxWidgets v3.2.8

.appveyor.yml, .circleci/config.yml, .github/workflows/ubuntu-ci.yml, BUILD.md, CMakeLists.txt, org.moneymanagerex.MMEX.yml, src/webappdialog.cpp
to address 
- #7441 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7443)
=> Infra: use --enable-std_containers

src/stockspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7486)
=> fix(#7485): fix sizer flags in stock panel

src/stockdialog.cpp
Fix missing cast as noted by [georgeef](https://github.com/georgeef)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7494)
=> Fix missing cast

src/mmchecking_list.cpp
https://wxwidgets.org/news/2025/06/wxwidgets-3.3.0-released/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7529)
=> wx3.3: prepration by wxPLURAL_U8 to wxPLURAL

src/assetdialog.cpp, src/assetdialog.h, src/assetspanel.cpp, src/budgetingpanel.cpp, src/budgetingpanel.h, src/filtertransdialog.cpp, src/import_export/qif_import_gui.cpp, src/maincurrencydialog.cpp, src/mmSimpleDialogs.cpp, src/mmchecking_list.cpp, src/mmex.cpp, src/mmframe.cpp, src/mmhomepage.cpp, src/mmreportspanel.cpp, src/model/Model_Stock.cpp, src/stockdialog.cpp, src/stockdialog.h, src/stocks_list.cpp, src/stockspanel.cpp, src/webapp.cpp, src/wizard_newdb.cpp, src/wizard_newdb.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7533)
=> Cleanup: removed unused variable

contrib.txt, src/mmreportspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7537)
=> fix(#7532): int64 id fix

.appveyor.yml, .circleci/config.yml, .github/workflows/ubuntu-ci.yml, org.moneymanagerex.MMEX.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7556)
=> fix(#7530): wx3.3.1

po/de_DE.po, po/mmex.pot, src/CMakeLists.txt, src/constants.cpp, src/constants.h, src/daterangedialog.cpp, src/daterangedialog.h, src/daterangeeditdialog.cpp, src/daterangeeditdialog.h, src/filtertransdialog.cpp, src/filtertransdialog.h, src/maincurrencydialog.cpp, src/maincurrencydialog.h, src/mmSimpleDialogs.cpp, src/mmSimpleDialogs.h, src/mmcheckingpanel.cpp, src/mmcheckingpanel.h, src/mmframe.cpp, src/mmframe.h, src/mmreportspanel.cpp, src/mmreportspanel.h, src/model/Model_Infotable.cpp, src/model/Model_Infotable.h, src/option.cpp, src/option.h, src/optionsettingsmisc.cpp, src/optionsettingsmisc.h
See issue #7577 for description.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7578)
=> Feature#7577: Unified date handling

po/de_DE.po, po/mmex.pot, src/constants.cpp, src/constants.h, src/mmchecking_list.cpp, src/model/Model.cpp, src/optionsettingsgeneral.cpp, src/optionsettingsgeneral.h, src/transdialog.cpp
Changes for  "Enhancement: Use default status after copy/paste or duplicate" #7588
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7589)
=> Feature (#7588): Use default status after copy/paste or duplicate

src/webappdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7592)
=> Compilation Fix for Fedora 41 systems

src/daterangedialog.cpp
See comment in #7577
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7598)
=> Feature (#7577): Autosize Added  to column creation

src/import_export/export.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7599)
=> fix(#7192): export correction

po/de_DE.po, po/mmex.pot, src/mmpanelbase.cpp, src/mmpanelbase.h
Implementation for #7604
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7607)
=> Feature (#7604): Menu option Move colums to beginning/end

.appveyor.yml, CMakeLists.txt, src/general_report_manager.cpp, src/mmSimpleDialogs.cpp, src/mmframereport.cpp, src/mmhomepagepanel.cpp, src/platfdep_win.cpp, src/reports/bugreport.h, src/reports/htmlbuilder.cpp, src/util.cpp, src/util.h, src/wizard_update.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7617)
=> fix(#5124): use Edge backend for WebView in MSW

NEWS, contrib.txt, src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7630)
=> fix(#7557): font fix

src/mmchecking_list.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7640)
=> fix(#7595): unicode fix

src/mmcheckingpanel.cpp, src/mmreportspanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7652)
=> fix(#7577): filters per account/report

src/constants.cpp, src/constants.h, src/daterange2.cpp, src/mmcheckingpanel.cpp, src/mmcheckingpanel.h, src/mmreportspanel.cpp, src/mmreportspanel.h, src/model/Model_Report.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7660)
=> fix(#7577): updates

src/mmchecking_list.cpp, src/mmcheckingpanel.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7671)
=> fix(#7577): fixes

contrib.txt, src/reports/reportbase.cpp, src/webappdialog.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7704)
=> fix(#7685): UTF8 change

.github/workflows/ubuntu-ci.yml, src/mmframe.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7741)
=> fix(#7737): account right-click menu for stock portfolios

contrib.txt, src/mmreportspanel.cpp, src/reports/cashflow.cpp
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7768)
=> fix(#7765): start and end datetime calculation fix
